### ISSUE TITLE
There is no way to control anchor creation only when localized. Also no way to query if anchor is localized

### ISSUE THREAD

**Issue by arghyasur1991** [google-ar/arcore-unity-sdk#10]
SessionManager.Instance.MotionTrackingManager.IsLocalized ( Not exposed as an api) is used to create localized anchors but everything is done internally. What if the user only wants to create anchors when localization is achieved, or at least query which anchors are unstable(non localized)? There are no apis to do that.

**Comment by small-potatoes** [comment]
You are correct that localization is not something we surface in the developer preview.  Localization and mapping is a complex subject and it was decided that the simplistic model you reference was not appropriate to expose/support externally right now.  We really appreciate your feedback and will work on ways to expose such information in the future to help developers make better decisions about placing anchors.
