### ISSUE TITLE
Camera plugin should probably be moved out of Examples

### ISSUE THREAD

**Issue by stella3d** [google-ar/arcore-unity-sdk#103]
The [native camera plugin](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/ComputerVision/Plugins/libarcore_camera_utility.so) is useful in general, not just for the example it's included in.  
It should probably be moved to the Plugins folder under `SDK`.

It's common for users to delete the examples entirely - we just had this error in our [experimental "AR Interface" repo](https://github.com/Unity-Technologies/experimental-ARInterface), where background rendering functionality broke for users that deleted the ComputerVision example.  The error is not too straightforward to diagnose when this happens.

**Comment by eAi** [comment]
As someone who did exactly this, I support this change.

**Comment by small-potatoes** [comment]
Closing as the native camera plugin is superfluous since the ARCore SDK supports getting high resolution camera image bytes via Camera Configuration since version 1.4.
