### ISSUE TITLE
Error running on OnePlus 5T, A5010, Android 8.0.0

### ISSUE THREAD

**Issue by alchemz** [google-ar/arcore-unity-sdk#105]
Compiled HelloAR.apk successfully from Unity, yet it shows as incompatible when trying to download ARCore 1.0 from the play store.

OnePlus 5, A5000, is listed as supported device on google website, and how could OnePlus 5T not be listed? https://developers.google.com/ar/discover/#supported_devices

**Comment by pablisho** [comment]
As you stated OnePlus 5T is not part of the supported devices list, and though is not currently supported. Although being part of the same line, OnePlus 5T is a different device to OnePlus 5 (with different screen, different chipset, etc) and it will require specific work to be included into the supported devices.

**Comment by alchemz** [comment]
@pablisho Thanks for the explanation. The OnePlus 5 and OnePlus 5T are different models, and I just did get it why they choose to calibrate the old model first.
