### ISSUE TITLE
Editor scene tree

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#110]
Any possibility(current or planned) to see scene tree in unity editor during execution?

Is InstantPreviewInput meant only for apps which have arcore optional or is gonna be useful for full arcore apps as well?

**Comment by pablisho** [comment]
Thanks for the feature request.  Could you provide more details about exactly what you would like to have as "scene tree in unity editor during execution". InstantPreviewInput is not related to arcore optional.

**Comment by chaosemer** [comment]
I think InstantPreview satisfies much of your goals here -- quick iteration without having to build. I'm closing this issue.
