### ISSUE TITLE
Camera calibration params

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#112]
Any chance to expose camera calibration params?
`fx, fy, cx, cy` can be for now taken from projection matrix.
It would be really convenient to have it directly accessible.

What about distortion?
Are textures already undistorted?
If not, how to get distortion parameters?

**Comment by pablisho** [comment]
Hi, [ARCore Unity SDK v1.3.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.3.0) lets you obtain the camera intrinsics through [Frame.ImageIntrinsics](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Frame.cs#L331) and [Frame.TextureIntrinsics](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Frame.cs#L311).
