### ISSUE TITLE
Unity 2018.1b does not build HelloAR

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#114]
I tested on Unity `2018.1.0b6` and Unity `2018.1.0b8`.
There are multiple issues:

- `IPreprocessBuild.OnPreprocessBuild` changed parameters from version 2017.3 and `class BuildHelper` does not implement interface `IPreprocessBuild` anymore.

- Gradle Error: Colliding Attributes The attribute meta-data#com.google.ar.core@value=optional in :google_ar_required: collides with another value
(See the Console for details)

- com.unity.package-manager-ui/Editor/ sources cannot be found, but it is expectable

I understand that it is just beta, but it would be really convenient for developers to try out new features of unity and ARCore at once.

**Comment by stella3d** [comment]
The overlap between our users that are building AR apps and those interested in trying out the beta is significant, especially since with Unity 2018 there are a lot of new features. 

I was able to build HelloAR in the Unity 2018.0 beta just by using the fix linked to above, which i accepted into our repository as a temporary fix.  of course, ideally such a fix would go in here.

**Comment by pablisho** [comment]
Thanks for the report. We'll be taking a look into this for future releases.

**Comment by mat-lo** [comment]
Unity changed the interface from 2017.3 ([docs](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Build.IPreprocessBuild.OnPreprocessBuild.html)) to 2018.1b ([docs](https://docs.unity3d.com/2018.1/Documentation/ScriptReference/Build.IPreprocessBuild.OnPreprocessBuild.html)).

To make it compile, while you wait for the official update you can just change two lines this file in the SDK:
`/Users/mloglio/Unity/GoldenCircle/Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs`

add this at the top
`using UnityEditor.Build.Reporting;  `

then change line 42 from
`public void OnPreprocessBuild(BuildTarget target, string path)`
to
`public void OnPreprocessBuild(BuildReport report)`

and it should compile

**Comment by joduffy** [comment]
The error shows up in 2018.1.6

To fix it. You will need to change line 33 in the:
`GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs`
from:
`    public class BuildHelper : IPreprocessBuild`
to
`    public class BuildHelper : IPreprocessBuildWithReport`

**Comment by pablisho** [comment]
Hi @joduffy thanks for the report. I verified what you mention and it's a warning. I added it to our tracking to fix it for next releases.

**Comment by vitorfreire** [comment]
Hi Sorry i don't have GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs
only "AssetHelper.cs"
and in this file I couldn't find the line mentioned.
Any ideas?
