### ISSUE TITLE
Dependency conflicts with Google VR SDK

### ISSUE THREAD

**Issue by ZLJasonG** [google-ar/arcore-unity-sdk#116]
Various components of the ARCore SDK for unity prevent it being imported alongside the Google VR SDK without hacks.
 
instant_preview_unity_plugin.dll & instant_preview_shared.dll exist in both SDK's (despite not being the same)

The items in arcore_client.aar\classes.jar\com\google\android\aidl\ exist in both and appear to be the same

Workaround:
Rename the dll's with something the same length, then modify instant_preview_unity_plugin.dll with a hex editor to reference the renamed dll, and update InstantPreviewManager.InstantPreviewNativeApi

arcore_client.aar can be opened in 7zip and the files in classes.jar\com\google\android\aidl\ can be deleted.

**Comment by pablisho** [comment]
Thanks for the bug report. I added it to our internal tracking.

**Comment by peachpieproductions** [comment]
Any idea when this will be fixed?

**Comment by pablisho** [comment]
Hi, I believe this issue is note reproducible anymore using Unity 2017.4 and ARCore SDK for Unity 1.4. Feel free to comment if you still experience the issue.
