### ISSUE TITLE
Capture image through Android plugin?

### ISSUE THREAD

**Issue by cgfarmer4** [google-ar/arcore-unity-sdk#119]
Is there any way to access the Surface renderer thread so I can dump the pixel buffer into a bitmap in my java class?

https://stackoverflow.com/questions/48191513/how-to-take-picture-with-camera-using-arcore

https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/ComputerVision/Scripts/ComputerVisionController.cs

https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/ComputerVision/Scripts/ComputerVisionController.cs

**Comment by pablisho** [comment]
For feature requests on the ARCore Android SDK please refer to https://github.com/google-ar/arcore-android-sdk/issues

**Comment by cgfarmer4** [comment]
@pablisho this was a feature request for Unity though?

**Comment by pablisho** [comment]
Hi, sorry I misunderstood your request then. Could you please provide more details about the feature request? The link you provided talks about ARCore Camera Java class in the Android plugin.

**Comment by cgfarmer4** [comment]
I've found a different path. Thanks for reopening this to discuss.
