### ISSUE TITLE
InstantPreview

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#120]
Can somebody explain please what InstantPreview is and how to enable/use it?

**Comment by pablisho** [comment]
InstantPreview didn't get into ARCore 1.0 release. I cannot give a timeline but stay tuned for future releases, meanwhile you can take a look at the VR InstantPreview https://developers.google.com/vr/tools/instant-preview
I will leave this open as feature request.

**Comment by pablisho** [comment]
Hi, [InstantPreview](https://developers.google.com/ar/develop/unity/instant-preview) is part of [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0)
