### ISSUE TITLE
Build helper breaks builds if path has changed

### ISSUE THREAD

**Issue by mtschoen-unity** [google-ar/arcore-unity-sdk#123]
The new build helper script https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs relies on the plugin files existing in Assets/GoogleARCore. If I move the files (say to a libs/vendor folder), the .aar files do not exist at the hardcoded path, and the build fails.

Consider using AssetDatabase.FindAssets (https://docs.unity3d.com/ScriptReference/AssetDatabase.FindAssets.html) to search for these .aar files instead of using hardcoded paths.

**Comment by pablisho** [comment]
Thanks for the report. I added it to our internal tracking.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0). Feel free to reopen if you still experience the issue.

**Comment by mtschoen-unity** [comment]
Thanks! I'll check this out soon.
