### ISSUE TITLE
Log message: Unable to find Anchor component for handle

### ISSUE THREAD

**Issue by afedorychak** [google-ar/arcore-unity-sdk#124]
ARCore prints this message for every destroyed anchor, if you call `Trackable.GetAllAnchors`: 
```text
Unable to find Anchor component for handle -1066608160
```

If anchors are queried every frame this leads to it spamming logs with these messages.

**Comment by pablisho** [comment]
Thanks for the report. I added it to our internal tracking.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0). Feel free to reopen if you still experience the issue.
