### ISSUE TITLE
Searching for surfaces forever

### ISSUE THREAD

**Issue by guo787269125** [google-ar/arcore-unity-sdk#13]
It always shows "Searching for surfaces" forever. Nothing else, no more actions to appear in the "HelloAR" example. I run it on Pixel with Android 8.0.0

**Comment by nathanmartz** [comment]
You may need to point the phone at the ground or table top and look or move around to find the plane. Whatever you look at also has to have some texture/detail. If you only see a very few blue points then ARCore isn't finding enough features.

**Comment by guo787269125** [comment]
I have downloaded the Android Studio Version(Not the unity version), it works very well. And I'm using Unity2017.2 b10, with the example downloaded, no code editing, just some settings and build, not work.
I;m quite sure how to use this app. And by the way, I'm in China, is that the problem? And also I'm using Pixel and Android 8.0.0

**Comment by nathanmartz** [comment]
Ahh. There is a bug in unity b10 that breaks ARCore. Use b9 instead.

**Comment by guo787269125** [comment]
Thanks, I'll try
