### ISSUE TITLE
_AreVerticesListsEqual will be always return true.

### ISSUE THREAD

**Issue by ReiiYuki** [google-ar/arcore-unity-sdk#130]
I think `_AreVerticesListsEqual` in `TrackedPlaneVisualizer` will be always return true. Because before calls `_AreVerticesListsEqual`, it calls `GetBoundaryPolygon` which always return the boudary vertices. So I think we might not need `_AreVerticesListsEqual` anymore.

**Comment by pablisho** [comment]
It's true that GetBoundaryPolygon will return the latest vertices. The idea of checking if the vertices are equal to the last one rendered is to avoid wasting time and not generate garbage every frame if the plane was not updated.
