### ISSUE TITLE
ARCore with Cardboard tracking issues

### ISSUE THREAD

**Issue by JulianCortes** [google-ar/arcore-unity-sdk#134]
Anchored objects doesn't have the same precision when built for Cardboard.

**Comment by chaosemer** [comment]
Could you please provide a video of the issue you are seeing? That'll make it so we can investigate and diagnose.

Thanks!

**Comment by JulianCortes** [comment]
https://youtu.be/XHEtluTjuzU

Here is a video. 
It's been built with Unity 2017.3.0f3 with the Cardboard integrated plugin with ARCore package from here.

The device is a Samsung S8, with ARCore alone it works great, tho.

Thanks.

**Comment by bmitchinson** [comment]
We're in the middle of a hack-a-thon, hoping to win the AR category, and have the same issue :(

**Comment by chaosemer** [comment]
Thanks for the video! It looks like Cardboard's lens-driven FOV is conflicting with ARCore's camera-driven FOV setting. This causes objects to move an incorrect amount and appear to not be tracking. This is expected, you'll need to place the ARCore camera image on a plane in 3D to have the rendering appear correct.

I'm updating the title to reflect this. I'm happy to help you out with placing a plane, which is the best you'll be able to do.

**Comment by JulianCortes** [comment]
@chaosemer So you're saying that i need 2 cameras:
-  _ARCore_ rendering on an image texture on a plane. 
- _Cardboard_ camera that sees the plane but with a correct FOV.

TIA.

**Comment by chaosemer** [comment]
You only need the Cardboard camera. You would put the texture for the ARCore [Camera image texture](https://developers.google.com/ar/reference/unity/class/GoogleARCore/Frame/CameraImage) on a plane you position in the world.

The size of the plane would be such that the FOV for the image is correct in Cardboard. We don't expose the FOV directly, you'd have to deduce it from the projection matrix returned from Frame.CameraImage.GetCameraProjectionMatrix.

**Comment by SFBAWashable** [comment]
@chaosemer 

Can you please elaborate more on how to add this plane in Unity, and the deduction of the FOV?

Thanks in advance.

**Comment by SFBAWashable** [comment]
@JulianCortes Thanks for the detailed reply.

I am a bit confused about the first point. I do not see Target Display option in the camera. This option disappears when I switch build settings to Android platform.

Is there a Cardboard camera object in Unity? I only have camera with ARCoreBackgroundRenderer?

Sorry if my questions are too naive, I am a newbie.

**Comment by JulianCortes** [comment]
You have to activate the VR part... take look at [this](https://docs.unity3d.com/Manual/VROverview.html), it explains how to implement Google Cardboard on a Unity project.

**Comment by JulianCortes** [comment]
@jondyne IIRC even solving the FOV issue, i had the same "issue". The project i was working on was halted and that issue wasn't a gamebreaker.

**Comment by smohanty92** [comment]
@JulianCortes  - thanks for listing your methodology. Would it be possible to list exactly what you did to alleviate the issue? TIA

**Comment by jondyne** [comment]
We developed a work around in Unity which allows for ARcore experiences to be used in a headset see the implementation here - https://github.com/jondyne/ARcore_mobileVRHeadset/
For a bit of background on the project see - https://medium.com/@jon_54445/augmented-reality-for-mobile-vr-headsets-adc6d5ed11fe

**Comment by XaviFields** [comment]
@jondyne thanks for that project. It works pretty well.
I noticed it doesn't have ARCoreSessionConfig where I can configure the AugmentedImageDatabase.
Is there another way of setting an image database to work with?

I have an AR project that uses Augmented Images and we want to use VR glasses to be hands-free.

**Comment by Zumbalamambo** [comment]
@JulianCortes Im using Google ARCORE and GVR. I could not be able to find an option with Target Display option. Could you please suggest me how I can enable it?

**Comment by JulianCortes** [comment]
@Zumbalambo Sorry no, it's been a while since I worked with Unity projects so I'm a bit outdated.

**Comment by Zumbalamambo** [comment]
@JulianCortes Could you please share with us the code that you have been working on so as to help us understand the underlying method?

**Comment by JulianCortes** [comment]
@Zumbalamambo I don't have access to that solution anymore.

**Comment by Zumbalamambo** [comment]
@jondyne I tried the solution that you have suggested. its such a simple and best solution. However the camera is black when I tried to run your code with the latest version of ArFoundation and unity 2018.3. Could you please suggest a solution?
