### ISSUE TITLE
TextureReader in SDK

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#135]
~~I was wondering why the texture reader in the computer vision example, why the buffer format is either `GL_RED` or `GL_RGBA`, I think it should be `GL_RED` or `GL_RGB`, since alpha is not used at all.
Another option is to pass the GL format from the C# script, keep it flexible (one could choose another format without having to recompile the texture reader utility)~~ Totally forgot about frame buffer formats, nevermind, but feel free to correct me if I'm wrong.

=> Also, could the texture be part of the SDK instead of the example? I think that makes a bit more sense.
Thanks.

**Comment by chaosemer** [comment]
Thanks for the feature request.

Getting CPU access to the underlying texture is a very highly asked for feature. We're looking into it.

**Comment by iBicha** [comment]
Thanks!

**Comment by iBicha** [comment]
@chaosemer just a small pointer, if the future implementation will be based on reading PBOs from previous frames, we might need a timestamp with each frame, just to know how old it is (one might choose to not get these pixel buffers every frame)
Cheers

**Comment by iBicha** [comment]
I thought it would return the buffer index where the frame would be stored (which would be 0 or 1 since the buffer count is 2) But I think I see what you mean, one could store a timestamp separately every time SubmitFrame is called, and return it when AcquireFrame is called.

**Comment by chaosemer** [comment]
Yeah, exactly what you said.

Also, you are correct that SubmitFrame will reuse IDs.

**Comment by pablisho** [comment]
Hi, [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0) supports CPU image access in its API via [Frame.AcquireCameraImageBytes](https://github.com/google-ar/arcore-unity-sdk/blob/v1.1.0/Assets/GoogleARCore/SDK/Scripts/Frame.cs#L311).
