### ISSUE TITLE
Session.CheckApkAvailability never returns

### ISSUE THREAD

**Issue by ryan-motive** [google-ar/arcore-unity-sdk#138]
Running on an HTC U11 with Android 7.1.1. I'm making a call to Session.CheckApkAvailability, but "ThenAction" never gets called. I've put several log messages throughout LifecycleManager, including "OnCheckApkAvailabilityResultTrampoline", but they are never called either.

**Comment by pablisho** [comment]
Hi, thanks for the report. HTC U11 is an unsupported device so you won't be able to use it with ARCore, although Session.CheckApkAvailability should be returning UnsupportedDeviceNotCapable.
Could you provide a log of your run? That way we could track better what's going on with your device. Thanks.

**Comment by ryan-motive** [comment]
Hi Pablo,

Yes I was testing on this device to verify our fallback behaviour. I will try to get you a repro soon. Thanks for the quick response!

Ryan

**Comment by Edorne** [comment]
I have a similar problem on Unity:  Session.CheckApkAvailability () doesn't return anything... could you tell me how to use it ? Thanks.

**Comment by pablisho** [comment]
Thanks for the report. I added it to our internal tracker. We'll be looking into it for next releases, but if you have any logcat that will help too.

**Comment by Edorne** [comment]
I found it with czpublic help: this Code is Ok with Unity and tested on Samsung Galaxy S7 edge:
All you need is to call StartCoroutine(CheckCompatibility()); from Start method (_ShowAndroidToastMessage method taken from ComputerVisionController class)

private IEnumerator CheckCompatibility()
 {
     AsyncTask<ApkAvailabilityStatus> checkTask = Session.CheckApkAvailability();
     CustomYieldInstruction customYield = checkTask.WaitForCompletion();
     yield return customYield;
     ApkAvailabilityStatus result = checkTask.Result;
     switch (result)
     {
         case ApkAvailabilityStatus.SupportedApkTooOld:
             _ShowAndroidToastMessage("Supported apk too old");
             break;
         case ApkAvailabilityStatus.SupportedInstalled:
             _ShowAndroidToastMessage("Supported and installed");
             break;
         case ApkAvailabilityStatus.SupportedNotInstalled:
             _ShowAndroidToastMessage("Supported, not installed, requesting installation");
             Session.RequestApkInstallation(false);
             break;
         case ApkAvailabilityStatus.UnknownChecking:
             _ShowAndroidToastMessage("Unknown Checking");
             break;
         case ApkAvailabilityStatus.UnknownError:
             _ShowAndroidToastMessage("Unknown Error");
             break;
         case ApkAvailabilityStatus.UnknownTimedOut:
             _ShowAndroidToastMessage("Unknown Timed out");
             break;
         case ApkAvailabilityStatus.UnsupportedDeviceNotCapable:
             _ShowAndroidToastMessage("Unsupported Device Not Capable");
             break;
     }
 }

**Comment by EgoAnt** [comment]
A quick amendment to the code @Edorne provided above. I needed to alter the first line to be:
GoogleARCore.AsyncTask<ApkAvailabilityStatus> checkTask = Session.CheckApkAvailability();

**Comment by ryan-motive** [comment]
This seems to be working in Unity 2017.4.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0). Feel free to reopen if you still experience the issue.
