### ISSUE TITLE
Allow installation on Android < 7.0

### ISSUE THREAD

**Issue by ryan-motive** [google-ar/arcore-unity-sdk#139]
Is it possible to install a Unity build with option ARCore support on Android versions < 7.0? We have a fallback AR implementation that works well on lower-end devices, but would like to use ARCore if it's present. If I uncheck "AR Core" from the XR settings things really fall apart.

**Comment by rramprasad** [comment]
This thread would help https://github.com/google-ar/arcore-android-sdk/issues/213

**Comment by pablisho** [comment]
Hi, did you try disabling ARCoreRequired in ProjectSettings->ARCore->ArCoreRequired ? I believe that should allow you to install it in previous versions of Android, although you'll have to check with Session.CheckApkAvailability before doing any other operation with ARCore.
Let me know if that fixes your problem, if it doesn't then this is a bug and we'll be looking at it for future releases.

**Comment by ryan-motive** [comment]
Unity wouldn’t deploy it to my Android 6 device. I didn’t dig in too much however. Is there a build step I can bypass? Possibly I could just deploy it manually.

**Comment by pablisho** [comment]
I think that's ok if you have ARCoreRequired enabled. But if you don't select that option (It's not in player settings, it is in Edit-> ProjectSettings-> ARCore->ARCoreRequired) you shouldn't have that problem. Please confirm me that with that option disabled you still repro de issue.

**Comment by pablisho** [comment]
Hi, this issue is fixed in Unity 2017.3.1p4: https://unity3d.com/unity/qa/patch-releases/2017.3.1p4

**Comment by ryan-motive** [comment]
I can confirm this is working in Unity 2017.4 on a Samsung S6 running Android 6.0.1. Thanks for the fix!
