### ISSUE TITLE
PointCloud feature in ARCoreSessionConfig

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#142]
Enabling `PointCloud` should be an option in the session configuration, as a lot of the apps out there don't even use them.

Getting a point cloud involves several API calls, so this should improve performance where it's not used

**Comment by pablisho** [comment]
Hi, there's no performance overhead for always exposing the current point cloud. The Poincloud API calls are only done if you access Frame.Pointcloud, if you don't need the point cloud, you just shouldn't access that class.

**Comment by iBicha** [comment]
I could be wrong (or maybe the overhead is too small) I was referring to [this ](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Api/NativeSession.cs#L144) which looks like acquiring and releasing a point cloud every frame

**Comment by pablisho** [comment]
Yes, but that operation shouldn't be expensive, it's not copying the point cloud nor calculating anything. It's just giving you the pointcloud object on which you can then perform the operations.
