### ISSUE TITLE
Change First Position of FirstPersonCamera

### ISSUE THREAD

**Issue by ReiiYuki** [google-ar/arcore-unity-sdk#145]
The default first position of FirstPersonCamera is always (0,0,0). Can I change the position of it at the first time entering the scene.

**Comment by pablisho** [comment]
Hi, thanks for the feature request. I think this is currently not possible because all the ARCore objects are relative to the initial position which is (0,0,0).

**Comment by christougher** [comment]
I also am interested in being able to how to reposition the origin point.  Say for example tapping a point on a plane that then that hitpoint becomes the new 0,0,0.  I'm working on a game that depends on the base level being at y = 0.

**Comment by chaosemer** [comment]
The First Person Camera moves relative to its parent (see the "Use Relative Transform" checkbox). If you move its parent, the ARCore Device, the default position of the camera will change.

Note that plane positions and anchor positions will still be reported with (0,0,0) as the origin. You would need to update TrackedPlaneVisualizer and the Anchor logic to be relative to ARCore Device as well.
