### ISSUE TITLE
Camera.main field return null.

### ISSUE THREAD

**Issue by TakuKobayashi** [google-ar/arcore-unity-sdk#146]
Hello.
By calling Camera.main field, I can get the currently enabled Camera class in Unity.
But, in ARCore, always return null.
Would you fix it so that Camera class will be returned when Camera.main is called?
Thanks.

**Comment by pablisho** [comment]
Hi, thanks for the report. We'll be looking into it for next releases.

**Comment by iBicha** [comment]
Make sure your camera is tagged "MainCamera" in order for `Camera.main` to find it.
![Main camera tag](https://docs.microsoft.com/en-us/windows/mixed-reality/images/maincamera-350px.png)

**Comment by TakuKobayashi** [comment]
@iBicha Thanks, I have applied that.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0). Feel free to reopen if you still experience the issue.
