### ISSUE TITLE
ARCore 1.0 - models jump around.

### ISSUE THREAD

**Issue by freeschool** [google-ar/arcore-unity-sdk#147]
Hi, 

Is there any way to restart the ARCore?

ARCore 1.0 is quite unstable comparing to ARCore 0.8.  Models are jumping again and again after some minutes.  I would like to reset the ARCore not to jump around. 
Destroying and Creating new session didn't work.

Many thanks.

Han.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.1.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.1.0). Feel free to reopen if you still experience the issue.
