### ISSUE TITLE
Front Camera not Playing when ARCore Session is Running

### ISSUE THREAD

**Issue by talothman** [google-ar/arcore-unity-sdk#15]
There seems to be an issue with `ARCore` not allowing other camera devices to be accessed when it's running. For example, trying to play the feed from the front camera on a Pixel returns a black texture. Below is a quad with the camera feed from the front camera trying to render to it. Black screen if `ARCore` is running, renders properly if `ARCore` is off. Unity Build

![screenshot_20170911-225135](https://user-images.githubusercontent.com/5286101/30306065-2add0c9a-9744-11e7-9688-d4346f478bc4.png)

**Comment by nathanmartz** [comment]
This is a known limitation. Many Android phones do not allow you to open both cameras at once, and ARCore needs to use the rear-facing camera for tracking.
