### ISSUE TITLE
Transform 3D points from PointCloud to corresponding 2D screen coordinates

### ISSUE THREAD

**Issue by alexwzk** [google-ar/arcore-unity-sdk#150]
https://github.com/google-ar/arcore-android-sdk/issues/204
Dear staff, I found the solution of a similar problem for the Android SDK. I checked the Unity APK yet I couldn't find the Pose class. Nor could I find a corresponding class. I need to transform points from point cloud to corresponding 2D screen coordinates. I tried the CameraImage.GetCameraProjectionMatrix but I failed. The format of points kinda puzzled me. Under what coordinate does ARCore describe a point in the PointCloud? Say if it's the local space then is it the Viewport space? Could you kindly give me a hand? Thank you in advance.

This is how I calculate the transformation now:
Matrix4x4 transMatrix = Frame.CameraImage.GetCameraProjectionMatrix(m_Camera.nearClipPlane, m_Camera.farClipPlane);
m_Points[i] = Frame.PointCloud.GetPoint(i);
Vector3 point2D = transMatrix.MultiplyPoint(m_Points[i]);

**Comment by alexwzk** [comment]
Update: This seems working:
                    m_Points[i] = Frame.PointCloud.GetPoint(i);
                    Vector3 point2D = m_Camera.WorldToScreenPoint(transform.TransformPoint(m_Points[i]));
But I'd still love to figure out under which local space the points in the point cloud is provided. Also what is the correct way to use the camera projection matrix.

**Comment by chaosemer** [comment]
Your code looks right.

The point cloud is exposed in world space, not in local space.

**Comment by minnes09** [comment]
Hello, I´m trying to do the same thing. I´m using the same approach, but the position of the points in the screen change a lot at each frame: I noticed that they move from left to right.
Frame.PointCloud.CopyPoints(cloudPoints);
//for loop
Vector4 v = cloudPoints[i];
Vector3 vectTransform = transform.TransformPoint(v);
Vector3 screenCoords = cam.WorldToScreenPoint(vectTransform);
Vector2 uv = new Vector2(screenCoords.x, screenCoords.y);

Thanks in advance for the help

**Comment by lvonasek** [comment]
Try after the line:
Vector4 v = cloudPoints[i];
put this:
v.w = 1.0f;

**Comment by softlion** [comment]
See unproject in [this code](https://github.com/ThomasGorisse/sceneform-android-sdk/blob/master/core/src/main/java/com/google/ar/sceneform/Camera.java)
