### ISSUE TITLE
Unable to run previously working project (or HelloAR)

### ISSUE THREAD

**Issue by Beclamide** [google-ar/arcore-unity-sdk#152]
I've just tried building a previously working project (built a few weeks ago) and it launches, displays surface detection message in the SnackBar, no camera image in background. It pauses for a few seconds, then crashes.

I tried building a whole new project from HelloAR and exactly the same thing happens.

In LogCat there's two outstanding errors:
```
03-26 17:31:06.061 31517-31556/? E/Unity: Unable to find unitygar
03-26 17:31:09.298 31517-31556/? E/Unity: Unable to find instant_preview_unity_plugin
```

I'm testing on a Samsung Galaxy S7 Edge
ARCore version 1.0.180129153
Unity version 2017.3.1f1
Unity SDK version 1.0.0

**Comment by pablisho** [comment]
Hi, can you reproduce it with the unmodified HelloAR example? I think you may have done modifications to it that could be causing the issue to not find unitygar.

**Comment by Beclamide** [comment]
Hi @pablisho I did try it again with the unmodified HelloAR example and it does seem to work now. It may have been a setting I missed in the build settings, or could have been my phone playing up. Either way, thanks for the help.
