### ISSUE TITLE
(Unity) Disable/enable ARCore in more laconic way

### ISSUE THREAD

**Issue by romanunit** [google-ar/arcore-unity-sdk#153]
Hi. I have some problem and i can`t find how resolve it. If i have in one scene 2 cameras(1 from unity and second one from ARCore) and i switch it. In default, ARcore camera is disable and Unity camera - enable. When i disable unity camera and enable ARCore camera it seems like broken.  My app crash and don`t whant work properly. Mb i need do this in other way? Mb i can disable/enable ARCore in more laconic way? What u can say me?

And i have one more question. How i can check in start scene if android support ARCore?

**Comment by pablisho** [comment]
Hi, to check if ARCore is supported you can use Session.CheckApkAvailability(). You don't need to have an ARCoreDevice nor ARCoreSession yet.
To Pause/Resume ARCore you have to disable/enable the ARCoreSession object, not the camera. That would also stop the background rendering.
Let me know if this helped.
