### ISSUE TITLE
Allow ARCore support checking without a session

### ISSUE THREAD

**Issue by eAi** [google-ar/arcore-unity-sdk#155]
I'd like to be able to check if ARCore is supported without having to ask for camera permission. We'd like to hide an 'AR' button in our game if the device doesn't support ARCore, but currently we have to ask for camera permission before we can do this - which seems quite counter-intuitive. 

Currently the flow is often something like this:

1. Launch app
2. Ask for camera permission (as it's out of the blue this is often rejected)
3. Check if AR is supported (or can be on the device) show AR button
4. If button is pressed, check to see if AR is installed, and if not, launch the install flow. 
5. Request camera permission again if required

**Comment by pablisho** [comment]
Hi, You shouldn't need an ARCoreSession to check if ARCore is Supported. From one scene (without an ARCoreDevice prefab nor an ARCoreSession script) you could use Session.CheckApkAvailability(), that would return an [ApkAvailabilityStatus](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/ApkAvailabilityStatus.cs).
Depending on that result, you can transition to an ARCore Scene which will have the ARCoreDevice prefab and will request the camera permission.
Let me know if this helps.

**Comment by RS360build** [comment]
Can you provide some more information on how to do this. I have the same problem but am not following.

**Comment by vinayak-vc** [comment]
Hii
@pablisho 

Can you give some code snippets?

**Comment by GameDevKaran** [comment]
```cs
string WhichSceneToload;
var result = GoogleARCore.Session.CheckApkAvailability().Result;
            if (result.Equals(100))
            {
                WhichSceneToload = "NonAR";
            }
            else
            {
                switch (result)
                {
                    case 201:
                        {
                            Debug.Log("The device and Android version are supported, but AR (ARCore) is not installed");
                            break;
                        }
                    case 202:
                        {
                            Debug.Log("Google Play Services for AR (ARCore) is installed, but app version is too old");
                            break;
                        }
                    case 203:
                        {
                            Debug.Log("Google Play Services for AR (ARCore) is supported, installed, and available to use.");
                            WhichSceneToload = "AR";
                            break;
                        }
                }
            }
```

**Comment by chaosemer** [comment]
@GameDevKaran, thanks for helping people out here. The code snippet you posted looks great, though I'd recommend using the enum values from [ApkAvailabilityStatus](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/ApkAvailabilityStatus.cs) like `ApkAvailabilityStatus.SupportedInstalled` instead of `203`.

**Comment by GameDevKaran** [comment]
> @GameDevKaran, thanks for helping people out here. The code snippet you posted looks great, though I'd recommend using the enum values from [ApkAvailabilityStatus](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/ApkAvailabilityStatus.cs) like `ApkAvailabilityStatus.SupportedInstalled` instead of `203`.

Right!!, i have updated my answer with your suggestion

**Comment by GameDevKaran** [comment]
Better Solution is Here : https://answers.unity.com/questions/1481890/how-to-use-arcore-sessioncheckapkavailability.html
