### ISSUE TITLE
Lenovo Mirage Solo support in ARCore?

### ISSUE THREAD

**Issue by reed-alpert** [google-ar/arcore-unity-sdk#156]
Mirage release date is May 6, will ARCore detect the WorldSense support and extra cameras and integrate that info into its position and rotation information?

**Comment by chaosemer** [comment]
ARCore is focused on Smartphone AR and will not run on the Lenovo Mirage Solo.

The same core tracking algorithms that power ARCore have been tuned for VR to power WorldSense.

**Comment by andybak** [comment]
Shame. I can think of a whole class of VR applications that would be opened up if there was slightly lower-level access to the SLAM data. Daydream is such a black box.

**Comment by chaosemer** [comment]
I agree, there's a lot of XR potential when tying experiences to the real world. However, ARCore is focused on enabling people to ship apps to the most widely used platform: Android smartphones.
