### ISSUE TITLE
Confidence Value of Frame.PointCloud is always zero

### ISSUE THREAD

**Issue by nydej2** [google-ar/arcore-unity-sdk#159]
I am trying to persist a PointCloud for some reasons. Because of that, i'd like to cull out all feature Points below a certain confidence Value. 
However, when I get the Points via Frame.PointCloud.GetPoint(i) inside the Update() function of Unity, the 4th value of the vec4 Point is always zero. I am working with ARCore 1.0.

**Comment by pablisho** [comment]
Hi, thanks for the report. Are you using ARCore 1.0 or 1.1?

**Comment by nydej2** [comment]
I am currently working with ARCore 1.0

**Comment by pablisho** [comment]
In v1.0, GetPoint returns a Vector3, if you are using a Vector4 I believe you are getting an implicit conversion which is setting to 0 the last component. Please feel free to reopen if you can repro in v1.1.

**Comment by nydej2** [comment]
Thanks! It works just fine with 1.1.
