### ISSUE TITLE
S8 stretching

### ISSUE THREAD

**Issue by gnistregn** [google-ar/arcore-unity-sdk#16]
The background video view is horisontally stretched on my S8, making it mismatch the rendered content. The S8 screen has a really wide aspect ratio that doesn't match the camera aspect. But instead of zooming to fill the screen (or using black borders on the sides) it stretches horisontally to fill. 
Also, the demo scene is running at around 30 fps, which seems to be because that's the framerate of the background video feed, but not entirely sure.

**Comment by nathanmartz** [comment]
Thanks for the bug report. This is a known issue and we're working w/ Unity
to get it resolved.

**Comment by eisenbruch** [comment]
Confirming this is also an issue on Pixel 2 XL

**Comment by fredsa** [comment]
This issue is reported as fixed in the Unity 2017.3.0b5 [release notes](https://unity3d.com/unity/beta/unity2017.3.0b5):

> XR: Background image for ARCore apps are no longer stretched when running a Samsung S8

**Comment by chaosemer** [comment]
I'm closing this as this is now fixed in recent versions of Unity. Please reopen if you're still having this issue.
