### ISSUE TITLE
How to Convert Vector 3 to AR Core Pose?

### ISSUE THREAD

**Issue by RajkumarRepo** [google-ar/arcore-unity-sdk#161]
I'm working on unity AR-Core SDK.  I want to place object  anywhere on the place based on touch. Is there any way to convert to Vector 3 co-ordinates to  Pose in AR-core?
I was used this code to place the anchor of object any where in the position in the camera?

```
Vector3 p = new Vector3();
 Camera c = Camera.main;
 Event e = Event.current;
 Vector2 mousePos = new Vector2();

 mousePos.x = e.mousePosition.x;
 mousePos.y = c.pixelHeight - e.mousePosition.y;

p = c.ScreenToWorldPoint(new Vector3(mousePos.x, mousePos.y, c.nearClipPlane));


Pose pose = new Pose(p, transform.rotation);
Anchor anchor = Session.CreateAnchor(pose, null);


fighterObject = (GameObject)Instantiate(fighter, pose.position, pose.rotation);
Vector3 cameraPositionSameY = m_firstPersonCamera.transform.position;
cameraPositionSameY.y = pose.position.y;
fighterObject.transform.LookAt(cameraPositionSameY, fighterObject.transform.up);
fighterObject.transform.parent = anchor.transform;
```

**Comment by pablisho** [comment]
Hi,
To place objects in the world you just have to use world coordinates. Creating an anchor is the right way to go. A Pose is just position + orientation, so if you have a Vector3 (just position) you have to somehow define how you want your object to be oriented in your scene.

**Comment by pablisho** [comment]
I'm closing because the question was answered. Feel free to reopen if you still have questions regarding how to do this.

**Comment by RajkumarRepo** [comment]
I got the solution.Thanks for your response.

**Comment by thomasbn94** [comment]
Is it possible to describe a normal vector as a ```Vector3``` using ```Pose```? I'm looking for how to get the normal vector of a place using ```getCenterPose()```
