### ISSUE TITLE
DllNotFoundException: instant_preview_unity_plugin when building on Linux beta

### ISSUE THREAD

**Issue by claywilkinson** [google-ar/arcore-unity-sdk#164]
I used to be able to build OK with pre 1.1 versions of the plugin.  Now I get this error.

I understand that instant preview probably is not supported on Linux yet, but it should not break the build.

DllNotFoundException: instant_preview_unity_plugin
GoogleARCoreInternal.LifecycleManager._Initialize () (at Assets/GoogleARCore/SDK/Scripts/Managers/LifecycleManager.cs:231)
GoogleARCoreInternal.LifecycleManager..cctor () (at Assets/GoogleARCore/SDK/Scripts/Managers/LifecycleManager.cs:58)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GoogleARCoreInternal.LifecycleManager
GoogleARCore.Frame.get_LightEstimate () (at Assets/GoogleARCore/SDK/Scripts/Frame.cs:70)
GoogleARCore.EnvironmentalLight.Update () (at Assets/GoogleARCore/SDK/Scripts/EnvironmentalLight.cs:47)

**Comment by pablisho** [comment]
Hi, Thanks for the report. I added it to our internal tracker so we look at this for next releases.

**Comment by thestr4ng3r** [comment]
I found a cheap workaround for this. Basically I create a tiny stub library and put it in `Assets/GoogleARCore/SDK/InstantPreview/Plugins/x86_64`. It does not do anything, but at least fixes building.
The code is here: https://github.com/thestr4ng3r/arcore-unity-instantpreview-stub
You can download a build here: https://github.com/thestr4ng3r/arcore-unity-instantpreview-stub/releases

**Comment by otaviojr** [comment]
There is a simple way to solve that.

On /Assets/GoogleVR/Scripts/InstantPreview/InstantPreviewHelper.cs (line 27)

Just change the line:

#if UNITY_HAS_GOOGLEVR && UNITY_EDITOR

to

#if UNITY_HAS_GOOGLEVR && UNITY_EDITOR && !UNITY_EDITOR_LINUX

This will disable instant preview on linux and the build will success.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.

**Comment by OptiHub** [comment]
I'm still experiencing this issue. 

I downloaded and imported the newest ARCore SDK for Unity 1.5.0 but when I press the Play Button I get these Errors:

![image](https://user-images.githubusercontent.com/32564947/46726273-4fb4e180-cc7e-11e8-990b-d1f2828c663d.png)

Strange is also, that the instant Preview is not available in the Project Settings in ARCore.

![image](https://user-images.githubusercontent.com/32564947/46726388-84c13400-cc7e-11e8-8c85-32a80def0d82.png)

**Comment by knightcube** [comment]
I am facing this same error in ARCore 1.12.0. I am on Ubuntu 18.0.4 and using Unity 2019.1.1.

**Comment by metinc** [comment]
I can confirm this error is back in 1.12.0, tested on Fedora 31.
