### ISSUE TITLE
Image Recognition Capabilities

### ISSUE THREAD

**Issue by LuisCRSousa** [google-ar/arcore-unity-sdk#165]
Hi,

There are a lot of Image recognition for AR out there. One of the missing features of ARCore is IR. Will you supporting this?

Thanks.

**Comment by chaosemer** [comment]
Thanks for the feature request.

**Comment by bilelmnasser** [comment]
Image recognition is a must, i vote for this !!

**Comment by UnNeill** [comment]
opencv is free and does several kinds of image recognition

**Comment by LuisCRSousa** [comment]
They just released Augmented Image with Arcore 1.2 :)

**Comment by pablisho** [comment]
Hi, [Augmented Images](https://developers.google.com/ar/develop/unity/augmented-images/) is one of the new features released in [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0)
