### ISSUE TITLE
instantpreview input and standard unity UI

### ISSUE THREAD

**Issue by DomDumont** [google-ar/arcore-unity-sdk#167]
Hi,

I created a standard unity button on top of the HelloAR demo.
in instantpreviewmode with 

using Input = GoogleARCore.InstantPreviewInput;

the button is not activated.
with the exact same code but by building the project (Build and run) it works perfectly.

**Comment by chaosemer** [comment]
This is expected. InstantPreview is not fully hooked into Unity's input system. That's why you need to use GoogleARCore.InstantPreviewInput.

**Comment by DomDumont** [comment]
oh ok, this is quite a bad news. I must use my UI and now  this is the only reason I need to deploy to the phone.
