### ISSUE TITLE
Duplicate zip entry [classes.jar:com/google/android/aidl/BaseProxy.class 

### ISSUE THREAD

**Issue by JudeOsborn** [google-ar/arcore-unity-sdk#168]
When building to Android with both ARCore and VR (Daydream or Cardboard at least) activated, I get the error "Duplicate zip entry [classes.jar:com/google/android/aidl/BaseProxy.class".

This is the same issue that has apparently been [fixed in the Android SDK](https://github.com/google-ar/arcore-android-sdk/issues/180#issuecomment-380878183) in version 1.1. However, I am using arcore-unity-sdk-v1.1.0.untitypackage, but receive the same error.

**Comment by JudeOsborn** [comment]
Note that this could be a duplicate (or related to) [this issue](https://github.com/google-ar/arcore-unity-sdk/issues/116).

**Comment by peachpieproductions** [comment]
Has this been patched yet?

**Comment by pablisho** [comment]
Hi, this will be fixed in our next release.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0). Feel free to reopen if you still experience the issue.
