### ISSUE TITLE
How to hide pointcloud and plane in unity ar-core?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-unity-sdk#176]
Hai iam using ARCore sdk for unity.i want to hidel horizontal grid plane and point cloud points in unity.how can i do that?

**Comment by ReiiYuki** [comment]
You can disable mesh renderer of TrackedPlaneVisualizer Prefabs and also disable PointCloud in the scene.

**Comment by ArigarasuthanRepo** [comment]
Any possibilities to hide feature points in code? because i want to hidel feature points based on button click.

**Comment by pablisho** [comment]
If you are using HelloAR's Point Cloud game object, disabling it should disable the point cloud visualization.

**Comment by ping-xiong** [comment]
I had solved this problem.
This video shows how TrackedPlaneVisualizer  works:  https://www.youtube.com/watch?v=Rl7entk9lio

**In controller script,** 

`private bool hide_show_plane = true;

private List<GameObject> m_NewPlanes_visible = new List<GameObject>();`

`
// add a click method
public void Hide_pointCloud()
        {
            if (hide_show_plane)
            {
                hide_show_plane = false;
            }
            else
            {
                hide_show_plane = true;
            }
        }`

// In the update method, add each new plane to a GameObject list
`            // Iterate over planes found in this frame and instantiate corresponding GameObjects to visualize them.
            Session.GetTrackables<TrackedPlane>(m_NewPlanes, TrackableQueryFilter.New);
            for (int i = 0; i < m_NewPlanes.Count; i++)
            {
                // Instantiate a plane visualization prefab and set it to track the new plane. The transform is set to
                // the origin with an identity rotation since the mesh for our prefab is updated in Unity World
                // coordinates.
                GameObject planeObject = Instantiate(TrackedPlanePrefab, Vector3.zero, Quaternion.identity,
                    transform);
              //  add to a Gameobject list 
                m_NewPlanes_visible.Add(planeObject);
                planeObject.GetComponent<TrackedPlaneVisualizer>().Initialize(m_NewPlanes[i], true);
            }

            for (int i = 0; i < m_NewPlanes_visible.Count; i++)
            {
               // call the method on  TrackedPlaneVisualizer.cs 
                m_NewPlanes_visible[i].SendMessage("Hide_pointCloud", hide_show_plane);
            }`

**In TrackedPlaneVisualizer.cs script**


`private bool isShow = true;`

`
// just change one line in Update method
public void Update()
        {
            if (m_TrackedPlane == null)
            {
                return;
            }
            else if (m_TrackedPlane.SubsumedBy != null)
            {
                Destroy(gameObject);
                return;
            }
            else if (m_TrackedPlane.TrackingState != TrackingState.Tracking)
            {
                 m_MeshRenderer.enabled = false;
                 return;
            }
           
           // hide or show the pointcloud 
            m_MeshRenderer.enabled = isShow;

            _UpdateMeshIfNeeded();
        }`

      // add a  new method for SendMessage in controller script
    `public void Hide_pointCloud(bool hide_show_plane)
        {
            isShow = hide_show_plane;
            m_MeshRenderer.enabled = hide_show_plane;
           // update the pointcloud
            Update();
        }`

It works

**Comment by ArigarasuthanRepo** [comment]
Thank you so much for your solution.Iam going to put on this to my code and check.

**Comment by claywilkinson** [comment]
Looks like this issue is resolved, please re-open if not.

**Comment by DomCoccorese** [comment]
sorry, doesn't work for me

**Comment by pyiqun** [comment]
ARPointCloudManager.SetTrackablesActive(false);
ARPlaneManager.SetTrackablesActive(false);
