### ISSUE TITLE
libtango_3d_reconstruction.so Included in apk

### ISSUE THREAD

**Issue by DmytroHreshchik** [google-ar/arcore-unity-sdk#18]
Building an apk with ARCore adds libtango_3d_reconstruction.so into apk, which increases apk size by something like 5MB. In Google Tango, 3D reconstuction was an experimental feature, I'm not sure if ARCore uses this lib. It would be great to have an option to exclude this lib from apk, if it's possible.

**Comment by chaosemer** [comment]
Thanks for the bug report! That .so is safe to manually remove from the .apk as it is not used. It will not be included in the 1.0 release of ARCore.

**Comment by chaosemer** [comment]
This should now be resolved in Developer Preview 2.
