### ISSUE TITLE
Not having game preview in editor full screen freezes instant preview

### ISSUE THREAD

**Issue by claywilkinson** [google-ar/arcore-unity-sdk#180]
I want to see the hierarchy of the scene when running instant preview, so i turn off maximize on play.

It freezes and I see this in the console log.
Assertion failed: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state

**Comment by gstanlo** [comment]
There were previously some bugs with resizing the game window which should have been fixed in version 1.2.
