### ISSUE TITLE
About deleting old trackables and start tracking without any previous data(start like a first try)

### ISSUE THREAD

**Issue by AnipenHkim** [google-ar/arcore-unity-sdk#181]
Hi, I'm using ARCore for my project and have some questions.

I want to reset all trackables when application is paused(especially run in background), and I've searched solution for this issue here.
The nearest issues about this was "**#128 Trackables can not be deleted"** and I've watched this issue and found the release note that this issue have been already solved. 

**release note : Fixed #128: Objects from old sessions are deleted when a new ARCoreSession is created.**

But, when I tried to destroy old "ARCoreSession" and create new "ARCoreSession" script, nothing happened. Old trackables were still remains and tracked when ARCore recognized same environment.
I also tried to call method "ArSession_destroy" on "SessionApi" script, but app crashed.

Can I know specific process to delete old trackables? or has it been fixed not yet? 
Please, answer

Thanks, regards

**Comment by pablisho** [comment]
Hi, to destroy an create a new ARCore Session you have to destroy your ARCoreSession object that is usually attached to ARCore Device and then create a new one. What version of Unity ARCore SDK are you using?
You shouldn't be calling internal methods, as we don't guarantee any behaviour on them.

**Comment by AnipenHkim** [comment]
I've tested exactly what you mentioned. I destroyed "ARCoreSession" and contained object. After that I re-created GameObject contains "ARCoreSession", but still remained trackables(checked it as displaying "Session.GetTrackables with trackable filters All" count)

I'm using Unityj ARCore SDK 1.1 and my unity version is 2017.3.1f1 and tested device is Galaxy S8 & Pixel XL with android 8.1.

**Comment by pablisho** [comment]
Hi I cannot repro this issue with [ARCore SDK for Unity v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0)

What I'm doing is something like:

```
var session = GameObject.Find("ARCore Device").GetComponent<ARCoreSession>(); 
Destroy(session);
var device = GameObject.Find("ARCore Device");
session = device.AddComponent<ARCoreSession>();
session.SessionConfig = // Set config
session.enabled = true
```

The if you do `Session.GetTrackables<DetectedPlane>(planeList);` gives me an empty list. Keep in mind that if you have old references to objects that belong to the previous session you have to destroy those objects too, but that's a visualization issue, ARCore is not returning them anymore.

**Comment by NicolasWipon** [comment]
Hi, I tried to destroy and create a new Session with these lines in a coroutine : 

 ```
ARCoreSession session = goARCoreDevice.GetComponent<ARCoreSession>();
        ARCoreSessionConfig myConfig = session.SessionConfig;
        Destroy(session);

        yield return null;

        session = goARCoreDevice.AddComponent<ARCoreSession>();
        session.SessionConfig = myConfig;
        session.enabled = true;
```

However, when I do this, the app is frozen for several seconds. Then, sometimes it works as expected, but sometimes the camera doesn't work anymore and is frozen on the last frame captured before the creation of a new session. 

Is there another way to reset the scan from the beginning (and not keep the previous scanning data) ?
Tested with ARCore SDK for Unity v1.2.0 on Galaxy S7 and S7 Edge.

**Comment by Pnailwal** [comment]
Hi, I tried the same above-mentioned code of pablisho and as soon as this code runs camera stops working.

**Comment by krychaszek** [comment]
Hi,
Is there any way for resetting previous session data? I want to reset data about found planes, and trackables, but I have the same problem and when I'try the solution above I have the same situation as @NicolasWipon - camera doesn't work anymore and it is frozen.

**Comment by leonmiura** [comment]
For me pablisho's code almost worked, but I had to replace  `Destroy(session);` with `DestroyImmediate(session);`.

What happens is that Destroy waits until the end of the frame to actually destroy the object. So when you try to create a new session, you get an error saying that there cannot be 2 ARCore sessions in one scene, and it destroys the new one... when you reach the end of the frame the old one is destroyed and I think that is why the camera is frozen afterwards.

When you call DestroyImmediate instead, the session is actually deleted immediately as you might have expected (I sure did) and the new session can be created fine.
