### ISSUE TITLE
ARCore orientation issue. Flickering on landscape mode

### ISSUE THREAD

**Issue by satheesh1000** [google-ar/arcore-unity-sdk#182]
Hi,

There is a rendering issue in ARCore. I need a landscape oriented scene in ARCore. I worked on an example scene in ARCore sdk. I changed the orientation to landscape left. I just put a game object 1m in front the camera. When I run the project everything works fine. But what my problem is, at first the game object renders in portrait mode, then it changes its orientation to landscape mode. Which means there is a flickering on game object in orientation when starting. I think this happens from ARCore itself. That is not good to go. Help me to fix this issue.

**Comment by pablisho** [comment]
Hi, thanks for the bug report. I added to our internal tracking.

**Comment by satheesh1000** [comment]
Thank you @pablisho .

**Comment by zarubin-alexey** [comment]
Hi, is there any updates on this bug?

**Comment by pablisho** [comment]
This will be fixed in out next release.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.3.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.3.0). Feel free to reopen if you still experience the issue.
