### ISSUE TITLE
How to place a single infinite plane? 

### ISSUE THREAD

**Issue by Dezec** [google-ar/arcore-unity-sdk#186]
Hello all, 

Thanks for the frequent updates. Love it. 

I am currently looking to find a way to limit plane tracking to a single infinite plane. That is to say, when I open the ARCore app, scan the environment and get the coordinates for a single plane, it should then automatically stretch to infinite x and z coordinates. 

Obviously, I tried increasing the x and z coordinates for the plane visualizer prefab, however this only increases the visuals and not the actual detected plane. 

Any help would be cool. 

Thank you

**Comment by ReiiYuki** [comment]
I am not sure do you mean merge all plane to single GameObject ?

**Comment by Dezec** [comment]
Hello, Thanks for the response. 

When the first plane is detected by ARCore, I simply want it to extend all the way to maybe 100 in the x and z coordinates. Then stop plane detection since that will be the only plane I need.

**Comment by Dezec** [comment]
Hi, just to make it clearer. This is the functionality I require. The application is IKEA Place for ARCore

https://www.youtube.com/watch?v=dpgoLNnkMr0

Notice how after the initial tracking, ARCore in the video places a single plane that extends out even though the farther distance wasn't tracked. 

Whereas by default ARCore only tracks areas that you personally show your camera to.

**Comment by pablisho** [comment]
Hi, to visualize it as an infinite plane, you can modify the TrackedPlaneVisualizer.cs, to render the way you want once it was detected, not using the ARCore returned Polygon but creating your own polygon.
If you want an infinite plane to then place objects on it, when performing a Raycast HitTest, then pass [PlaneWithinInfinity](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/TrackableHitFlags.cs#L53)

**Comment by Dezec** [comment]
Hello,

Thanks for the reply. I've now managed to get it the way I want now. Gonna close this

**Comment by Alok100** [comment]
> 
> 
> Hello,
> 
> Thanks for the reply. I've now managed to get it the way I want now. Gonna close this

@Dezec  Can you explain how you did it as I have a similar requirement

**Comment by NightFury13** [comment]
+1 for elaborate solution.

**Comment by hardik-intellify** [comment]
How to achieve this same using ARCore Java SDK?

**Comment by dashifuguye** [comment]
> How to achieve this same using ARCore Java SDK?

hi, hardik-intellify, have you solved this question?

**Comment by hardik-intellify** [comment]
> > How to achieve this same using ARCore Java SDK?
> 
> hi, hardik-intellify, have you solved this question?

Not actually, But I end-up doing like 
```
for (HitResult hitResult : frame.hitTest(mMotionEvent)) {
    try {
        anchor = hitResult.createAnchor();
    } catch (FatalException e) {
        e.printStackTrace();
    }
}
```
and setup Y as the First plane's position
