### ISSUE TITLE
ARCore materials show as black in Unity Editor

### ISSUE THREAD

**Issue by eisenbruch** [google-ar/arcore-unity-sdk#188]
When putting an object into a scene (or when viewing the object thumbnail or preview), if the object has the ARCoreDiffuse... or ARCoreSpecular... materials from the HelloAR example then the object just shows up as a black facade in the unity editor. 

Is this an ARCore issue or a Unity settings issue? I feel like it may be a Unity settings issue but I haven't seen anything to help with this elsewhere online so posting here before I go to stack exchange or elsewhere.

**Comment by pablisho** [comment]
Hi, those materials use light estimation values, which are populated by EnvironmentalLight script in Environmental Light prefab in HelloAR. Did you remove that prefab?

**Comment by pablisho** [comment]
Hi, I could repro it with latest release. Unity editor is now using Instant Preview light estimation values. If you disable InstantPreview you won't get this behaviour, although your lose InstantPreview capabilities, and so not recommended.
I added it to our internal tracking to fix it for next releases.

**Comment by eisenbruch** [comment]
Thanks! @pablisho is there a guide somewhere on adding the ARCore lighting shader feature to other shaders? It would be great to be given some info to help us write shaders that will be light/dark based on the ARCore scene, but that don't require a texture like the example shaders are setup.

**Comment by pablisho** [comment]
[Frame.LightEstimate](https://developers.google.com/ar/reference/unity/class/GoogleARCore/Frame#classGoogleARCore_1_1Frame_1afff8a4f5982320359a7cf92de256701a) returns a [LightEstimate](https://developers.google.com/ar/reference/unity/struct/GoogleARCore/LightEstimate) which has the LightEstimate values for this frame. EnvironmentalLight takes those values and properly uploads _GlobalColorCorrection global constant that you can use in any of your own shaders and apply it to the final color value.

**Comment by eisenbruch** [comment]
That sounds like information that should get me going in the right direction :) Thanks!

**Comment by eisenbruch** [comment]
@gstanlo this happens in single scene projects, so afai understand it cannot be that bug.

**Comment by gstanlo** [comment]
Is it appearing dark in the game window or the scene window? 
The shader constant that controls this lighting should be in EnvironmentalLight.cs as `_GlobalColorCorrection` and `_GlobalLightEstimation`. Can you tell if these are being set to values you would expect?

**Comment by eisenbruch** [comment]
Scene window. Game window is fine. As pablisho noted, I turned off instant preview and now I can see the materials just fine in the scene window.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.3.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.3.0). Feel free to reopen if you still experience the issue.
