### ISSUE TITLE
Unity loading time for ARScreen in Android native(Java) app 

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-unity-sdk#195]
I am exporting android code from Unity and embedding an UnityPlayerActivity as part of my native android app. So Whenever I launch ARScreen, it loads custom splashscreen and load ARCamera and 3DObject. This screen launch takes time because,it loads Unity game engine.

Is it any other way to preload this screen in Android? How Pokemon shows ARScreen as soon as it launches. I want to show screen like this without loading in between.

**Comment by small-potatoes** [comment]
Hey there,

By "ARScreen" are you referring to an ARCore Unity SDK application rendering an passthrough camera background?  For the splash screen, Unity allows you to remove this for [some licenses.](https://docs.unity3d.com/Manual/class-PlayerSettingsSplashScreen.html).  Unfortunately, there is no way to initialize ARCore in java and pass that initialization to Unity.  There may be a way to initialize Unity in an Android application without rendering to the viewport but that is beyond the scope of what we can help you here.  Does that help?

**Comment by rramprasad** [comment]
@small-potatoes Yes ARScreen means ARCore unity camera background. I already removed splashscreen with Unity plus license,but still it shows some black screen.You said,there may be a way to initialize unity in Android without rendering.But Unity gradle build gives exported project,not any loading parameters.Is it anything you know about loading Unity engine in background in Android app startup?

**Comment by pablisho** [comment]
Hi @rramprasad I think you'll find better support for non-ARCore specific issues in Unity forum and answers.

**Comment by rramprasad** [comment]
Hi @pablisho no problem,I discontinued using Unity and using Sceneform SDK.This is best way to avoid unity dependencies.
