### ISSUE TITLE
Supports Unity WebGL?

### ISSUE THREAD

**Issue by yosun** [google-ar/arcore-unity-sdk#20]
It looks like a web version of ARCore is avail. Can you update ARCore Unity to also allow for Unity WebGL builds to work with ARCore?

**Comment by nathanmartz** [comment]
Not really, no. Right now ARCore is only supported on the web via prototype browsers. Unity WebGL support for ARCore/Kit would require support for a WebAR standard in production browsers like Safari and Chrome, which in turn require a common standard for AR on the web, which doesn't happen quickly.

**Comment by saszer** [comment]
most of production browsers have started to route with webar google documention. would it be possible to support webgl export?! or babylon.js export
