### ISSUE TITLE
'Invalid Room Code' error when running ARCore 1.2 with Cloud Anchors

### ISSUE THREAD

**Issue by thePostFuturist** [google-ar/arcore-unity-sdk#202]
Reproduction is trivial, but I'll list it for the sake of protocol.

1. Got an API key with ARCore Cloud Anchor API enabled as a service.
2. Entered the key in the config.
3. Compiled and ran the "CloudAnchor" scene on Pixel 1.
4. Scanned my surroundings and created the Anchor, which, according to the log on the bottom was created successfully. I had also tested retrieval with another Pixel 1 by manually entering the IP and Room Code with success. 
5. Close the sample app on my Pixel.
6. Start the sample app on my Pixel.
7. Tapped 'retrieve anchor', input my Room code and got a 'Invalid Room Code' error.

**Comment by pablisho** [comment]
Hi, the mapping between room code and anchor id only lives in memory in the example (although in the cloud the anchors are still there). So if you want that behaviour you would need to store somewhere the anchor id once that is resolved.

**Comment by thePostFuturist** [comment]
Right, I saw the activity in my API Dashboard. If I understand correctly, the Room Number is Unity's Networking stack, and has nothing to do with Anchors?

Could you provide an example of how to retrieve anchors from the Anchor Cloud and place them locally on the device's surroundings?

**Comment by pablisho** [comment]
Hi, Cloud Anchor example does exactly that, it just uses the networking layer and the "room code" to map local room code to anchor id and share it to another device.
But the methods you have to use to Create and Resolve an anchor are very simple and are in [XPSession](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/XPSession.cs).
Let me know if this helped.

**Comment by thePostFuturist** [comment]
++

**Comment by pablisho** [comment]
Yes, but it's the example limitation and not Cloud Anchors limitation. If you share and store the AnchorId (with your own method), then resolving the Anchor would work for 24hs.

**Comment by pablisho** [comment]
Hi, I'm closing this because I believe your questions were solved. Please feel free to reopen if you still have questions regarding Cloud Anchors example.
