### ISSUE TITLE
How to take screenshot in a button click using ARCore in unity?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-unity-sdk#203]
Iam working a project with ARCore and unity.In this project i want to implement functionality take a screenshot with button click.Is there any way take screen shot with arcore?

**Comment by ufktvfk** [comment]
You can use this asset, it is free: https://github.com/yasirkula/UnityNativeGallery

Just read the example code. It includes the code that allows you to take ss.

**Comment by ArigarasuthanRepo** [comment]
Thank you.I will import this plugin and check it.Is ARCore provide screenshot functionality?

**Comment by ArigarasuthanRepo** [comment]
I was checked this plugin it was worked for me.Thank you for the solution.

**Comment by pablisho** [comment]
Hi, I'm closing this as I think your question is solved by now. Feel free to reopen if you still think you experience an ARCore issue.

**Comment by ArigarasuthanRepo** [comment]
Ok Thank you.
