### ISSUE TITLE
C# Style Guide Available? 

### ISSUE THREAD

**Issue by zkwencu** [google-ar/arcore-unity-sdk#205]
I really like the programming style you used in the ARCore Unity SDK and it's different from Microsoft's C# programming guide. I'd like to keep the code style consistent with yours while my team develops the ARCore app. I couldn't find it on Google Style Guides (https://google.github.io/styleguide/) though. I also Googled other websites but found no clue. Do you have a C# style guide that is publicly available? If so could you kindly give me a pointer to the webpage?

**Comment by pablisho** [comment]
Hi, the style we are using is not public, but we'll consider it as a feature request for the future. Thanks!

**Comment by zkwencu** [comment]
Thank you! You've done a great job. I'm looking forward to your style guide release.

**Comment by small-potatoes** [comment]
Hey Zikai, upon further review we are unable to release our style guide and have no plans to do so in the near future.  We appreciate your feedback and please feel free to make your own from reviewing our code.
