### ISSUE TITLE
Instant Preview initalizes but does not transmit or receive data

### ISSUE THREAD

**Issue by renaudbedard** [google-ar/arcore-unity-sdk#209]
I am able to use Instant Preview in the SDK sample provided with ARCore 1.2, but when attempting to use it in my own project, I can't get it to send the frame and pose data.

I see the following log after initializing AR :
`Instant Preview version 1.0.8
To disable Instant Preview, uncheck 'Instant Preview Enabled' under 'Edit > Project Settings > ARCore'.`

And my USB-attached Google Pixel 2 opens the ARCore Instant Preview app, but I get a white screen for the AR background render on the camera, and the phone shows the ARCore Instant Preview UI which says "Not connected to editor".

I tried to debug the problem and it does run in the main loop `InstantPreviewManager.UpdateLoop()` but in `UpdateBackgroundTextureIfNeeded`, `NativeApi.LockCameraTexture` always returns **false** so it never applies the background texture data in editor.

How can I further debug this problem?
Thanks!

**Comment by poi-oezd** [comment]
Also have the same problem. This occured when after the second start of the project. From there on it wasn't possible anymore to connect to the app....

**Comment by Shamos** [comment]
I am facing the same problem. I am using a Samsung S8

**Comment by gstanlo** [comment]
Does the Instant Preview app show as connected? Or does it have a red bar/disconnected?

Sometimes the ports Instant Preview uses don't get freed for some reason. Only one instance of Unity with Instant Preview will work at a time. If you close all instances of Unity and check your instant preview port, is it open? You can do that on windows with:
`netstat -ano | findstr 49838`
and on osx with:
`netstat -an | grep 49838`

If open, they should not show any output.

**Comment by poi-oezd** [comment]
In my case they ports still were open with a non existing process attached. I tried to close them with ProcessExlporer and TCPViewer on Windows but had no luck.

**An easy way to fix this problem is to log out and log back in.**

**Comment by gstanlo** [comment]
Instead of re-logging, `adb kill-server` can sometimes fix this.

**Comment by renaudbedard** [comment]
It does appear to work now! When I first tried I had 2 instances of Unity, one with the SDK sample and one with my own project.
Thanks for the `adb kill-server` tip, I'll try it if it fails again.

**Comment by Shamos** [comment]
still not working for me :(  (Samsung s8 & Unity 2017.4.3f1)
In the ARCore Instant Preview app I can see "Press PLAY in Unity editor to stream", but after hitting the play button the screens turns black -> after 1 or 2 seconds it switches back to die initial app screen. 
Anybody who is able to run in with Samsung S8?

**Comment by lothvorn** [comment]
The same for me.  With Samsung S8, after hitting play button in the ediotr, Instant preview goes to black for  second and then go back to the main screen with the 'press play in unity editor screen' message.

**Comment by Edgar-BlipparDev** [comment]
Same issue on Samsung Galaxy S9 and Note 8. After hitting play button in the editor, Instant preview goes to black for second and then go back to the main screen with the 'press play in unity editor screen' message. In Unity Screen is black and no camera feed is showing

**Comment by ikaro88** [comment]
i have the same problem with Galaxy A6 and Unity 2017.4.5f1 (64-bit)

No One can help us? :(

**Comment by pap3rinik** [comment]
same here: samsung s8, Unity 2017.4.8, ARcore 1.4, instant preview 1.0.9

**Comment by ikaro88** [comment]
is from april that we have this problem..
there is no work around?

**Comment by keyserjaya** [comment]
Same issue on my Samsung Galaxy S8+ After hitting play button in the editor, Instant preview goes to black for second and then go back to the main screen with the 'press play in unity editor screen' message. In Unity Screen is white.

**Comment by tntmeijs** [comment]
I, too, have the same issue on a Samsung Galaxy S9. 

The preview application appears to enter the game but quits immediately after half a second or so.

**Comment by FUBAR2077** [comment]
The same on S7, Unity 2018.2.2f1, ARCore 1.4.0, Instant Preview 1.0.9 :/ This is crucial for the development as I have to build the app everytime right now and this wastes 50% of the time..

**Comment by keyserjaya** [comment]
We should open the case again, it shouldn't be closed yet

**Comment by FUBAR2077** [comment]
@renaudbedard ? Can you please open this issue again so it can get resolved? Much development time relies on this, please please please.

**Comment by renaudbedard** [comment]
All the reports seem to be on Samsung Galaxy phones... may I suggest that you open a new issue that reflects your problem? It works fine on my end on a Pixel 2 XL.

**Comment by FUBAR2077** [comment]
Interesting point, maybe indeed it is connected with Samsung Galaxy phones.. I'll try to open new issue, thank you for an answer :)

**Comment by kolboch** [comment]
Have the same issue with LG G6, but I am stuck in press play in Unity editor. Seems to be connected well, but only game preview shows (being stuck) on Searching for surfaces...  in demo project and phone is still presenting Instant Preview screen with prompt to press play mentioned above.

**Comment by JamieShelley** [comment]
Same here. I've tried other options however and now get a white screen on direct apk install using opengl es2 instead if 3. And disabling multithreaded rendering. Tried in android versions 7,8, 8.1

**Comment by scottlaforge** [comment]
How is it possible that this issue is still not resolved?

**Comment by JeongeunJPark** [comment]
Same here, It still doesn't working. (galaxy s9+ / unity 2019.1.5f)

**Comment by DAigory** [comment]
still not work...s9 2019.2...

**Comment by aymusbond** [comment]
Still not working. Not Samsung, but Oppo phone.
