### ISSUE TITLE
Can I use custom camera preview? 

### ISSUE THREAD

**Issue by xiaowu4** [google-ar/arcore-unity-sdk#21]
I want to detect face when show the camera preview, and then create 3D model by Unity in the preview surface. So can I use custom camera preview?

**Comment by kai-dream** [comment]
Hi,

Current preview version of ARCore doesn't have face detection. If you want to detect face, you might considering adding own implementation.

Kai

**Comment by xiaowu4** [comment]
@kai-dream Thank you, Actually I alredy implemented the face detection. I wrote a Java class FaceGLSurfaceView which got the camera preview and then detected the face.  The problem is how can I use this Java custom view in ARCore!

**Comment by kai-dream** [comment]
@xiaowu4 I see. I don't have the answer to your question as I am not familiar with Android native development. The closest thing I've seen is in HelloAR example _ShowAndroidToastMessage function, which created a new AndroidJavaClass on existing unityActivity.

**Comment by nathanmartz** [comment]
This isn't possible with the preview version of ARCore as the camera cannot be controlled by two different systems at once, and ARCore has to control the camera. We're looking at providing access to the camera image data via ARCore for a future update.
