### ISSUE TITLE
Import New ARcore SDK 1.2.0 throw an error

### ISSUE THREAD

**Issue by lluma** [google-ar/arcore-unity-sdk#210]
<img width="996" alt="2018-05-15 2 23 05" src="https://user-images.githubusercontent.com/25431739/40040217-e6a24e40-584b-11e8-8d05-972bb0b90310.png">
Just import the new sdk 1.2.0 to my old project with old version sdk 1.0.0 and throw out an error.
Did any one encounter the same problem ?
The error message said that the ApiTrackableType is inconsisent accessilibity. Why?

Additionaly, when I import the sdk, I didn't import the HelloARController.cs and HelleAR scene. Is that make this problem happened?

**Comment by pablisho** [comment]
Hi, when updating the ARCore version I suggest you remove the GoogleARCore folder before importing the new version. I believe that file was removed in v1.2.0.
Let me know if that solves your issue.

**Comment by lluma** [comment]
While I just tried your suggestion and resolved it. Thanks for help a lot~~

**Comment by pablisho** [comment]
Cool. I'm closing this as your issues was solved. Feel free to reopen if you still experience the issue.
