### ISSUE TITLE
`GoogleARCoreInternal.ApiConstants' does not contain a definition for `AugmentedImageCliBinaryName'

### ISSUE THREAD

**Issue by tarakinsuide** [google-ar/arcore-unity-sdk#212]
Trying to import new ARCore SDk but getting an error:

`GoogleARCoreInternal.ApiConstants' does not contain a definition for `AugmentedImageCliBinaryName'

**Comment by Kitwradr** [comment]
Please give a solution for this , I am running unity on Linux . I hate Windows and don't want to use unity on Windows

**Comment by seyacat** [comment]
Put this lines at end of
./GoogleARCore/SDK/Scripts/Api/ApiConstants.cs

#elif UNITY_EDITOR_LINUX
        public const string AugmentedImageCliBinaryName = "augmented_image_cli_win";

Compile Successfull
But editor crash if try to run.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.
