### ISSUE TITLE
OSX: augmented_image_cli_osx exception attempting to open Example Database.asset in augmentedImage sample

### ISSUE THREAD

**Issue by pap3rinik** [google-ar/arcore-unity-sdk#215]
Hi, I have an ussue with
augmented_image_cli_osx attempting to open Example Database.asset in AugmentedImage sample scene targetting both Android or iOS

Unity version: 2017.3.1f1 on OSX HighSierra 10.13.4

Here the error stacktrace:
Win32Exception: ApplicationName='Assets/GoogleARCore/CLI/augmented_image_cli_osx', CommandLine='version', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
GoogleARCoreInternal.ShellHelper.RunCommand (System.String fileName, System.String arguments, System.String& output, System.String& error) (at Assets/GoogleARCore/SDK/Scripts/Utility/ShellHelper.cs:53)
GoogleARCore.AugmentedImageDatabase.GetDirtyQualityEntries () (at Assets/GoogleARCore/SDK/Scripts/AugmentedImageDatabase.cs:215)
GoogleARCoreInternal.AugmentedImageDatabaseInspector._RunDirtyQualityJobs (GoogleARCore.AugmentedImageDatabase database) (at Assets/GoogleARCore/SDK/Scripts/Editor/AugmentedImageDatabaseInspector.cs:122)
GoogleARCoreInternal.AugmentedImageDatabaseInspector.OnInspectorGUI () (at Assets/GoogleARCore/SDK/Scripts/Editor/AugmentedImageDatabaseInspector.cs:54)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1253)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by pablisho** [comment]
Hi, thanks for the report. I confirm I was able to repro it and I added it to our internal tracking to fix it for next releases. 
Though not related to this issue, Augmented Image example is Android only.

**Comment by pablisho** [comment]
@pap3rinik This seems to be just a file permission issue. To workaround this, give execute permission to augmented_image_cli_osx file. We'll fix it for next releases.

**Comment by pap3rinik** [comment]
Great! it works!

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.3.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.3.0). Feel free to reopen if you still experience the issue.

**Comment by simplewilliamz** [comment]
This still occurs in unity 2018.1.6f1
