### ISSUE TITLE
How to tell if detected plane is horizontal or vertical?

### ISSUE THREAD

**Issue by JackM36** [google-ar/arcore-unity-sdk#216]
Is there a way to tell if a certain detected plane is horizontal or vertical through ARCore? Or should that be implemented by the developer?

**Comment by dzak83** [comment]
I don't see it in the API but as it's all represented by just mesh vertices, you can use GetBoundaryPolygon, divide the count by two and compare [0] with [n/2]. If their "y" is similar or much different. For better results I would take even 3 points or more. For small planes you might get a wrong reading but because it's small, maybe it doesn't matter.

**Comment by JackM36** [comment]
Maybe it is not the best approach, but what I did I used the euler angles of the CenterPose.rotation to determine if it is vertical or horizontal. So far it works fine.

**Comment by dzak83** [comment]
I thought that even vertical planes are represented the same way as horizontal, it just happens that its vertices are in vertical order, not horizontal in the 3D space. I am glad that it works for you.

If that's the case, in DetectedPlaneVisualizer there is a code that calculates plane normal which might be another way to do it (I haven't tried it).

**Comment by JackM36** [comment]
They are represented in pretty much the same way as far as I can understand. However, the CenterPose contains their rotation values, which are different to represent their actual rotation in Unity world space. So by checking their euler angles it worked pretty well so far.

I am using my own custom wrapper around ARCore, which does not use the normal calculation like in DetectedPlaneVisualizer, so I could not use that. But now that you mentioned it, maybe I should include such a calculation. Thanks!

**Comment by deeivid** [comment]
Hello, I have suscribed to this thread and I'm wondering:  Can a plane be detected on an inclined surface? if so, @JackM36, would you consider a 45 degree inclined plane a horizontal or a vertical plane?

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and [DetectedPlane](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/DetectedPlane.cs#L118) exposes the plane type.
