### ISSUE TITLE
HitTest inaccessible due to its protection level when using unity-arkit-plugin spring2018_update branch

### ISSUE THREAD

**Issue by ghost** [google-ar/arcore-unity-sdk#217]
Following the instructions for "Quickstart for iOS" but happened to use the spring2018_update branch for Unity's ARKit plugin. Looks like ARCore doesn't like it:

> Assets/GoogleARCore/Examples/CloudAnchor/Scripts/ARKitHelper.cs(63,21): error CS0122: UnityEngine.XR.iOS.UnityARSessionNativeInterface.HitTest(System.IntPtr, UnityEngine.XR.iOS.ARPoint, UnityEngine.XR.iOS.ARHitTestResultType)' is inaccessible due to its protection level

I've tried the following versions just for fun:
2018.20b4 (obviously not supported)
2017.4.3f1
2017.3.1f1

When using the **default** branch I don't have issues.

**Comment by dblatner** [comment]
Same here with Unity 2018.1.1f1 official release.

Any update on this issue? It's quite urgent, since building or running in the play mode is not possible with this error.

What does the protection level mean? Is it possible to get a short workaround bugfix?

**Comment by dblatner** [comment]
If you change line 63 of file "ARKitHelper.cs" from
`session.HitTest(arPoint, ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent, m_HitResultList);`
to
`session.HitTest(arPoint, ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent/*, m_HitResultList*/);`
the compiler error vanishes, but I suggest fixing the missing overload method^^

**Comment by anuragTiwari92** [comment]
If you download the Unity ARKit from the bit bucket repository instead of the Asset store, the overload /protection access error go away
will need to look at UnityARSessionNativeInterface to see what changed. 
here is the bitbucket link https://bitbucket.org/Unity-Technologies/unity-arkit-plugin

**Comment by pablisho** [comment]
Hi, as some have already mentioned, we are currently only supporting the default branch of https://bitbucket.org/Unity-Technologies/unity-arkit-plugin. We'll a define a better process to support stable releases of ARKit in the future.
