### ISSUE TITLE
DllNotFoundException : arcore_camera_utility

### ISSUE THREAD

**Issue by FelixGirard** [google-ar/arcore-unity-sdk#219]
Hi, i wanted to use the TextureReaderApi from the ComputerVision example.
If i activate the textureReader, i get this error : DllNotFoundException : arcore_camera_utility

Also, on a different note, the instantPreview also isn't working, showing a blank screen on unity and stuck on the phone with 'press play in Unity editor'... In the adb logcat i can see that he couldn't find unitygar. I can build it and run on the phone though.

Here is my configuration : 
- Unity 2018.2.0b3 Personal (64 bit) and Unity 2017.4.3f1 Personal (64bit)
- Visual studio 2017
- arcore-unity-sdk 1.2.0
- Samsung S8 SDK 8.0.0

Thank you !

**Comment by pablisho** [comment]
Hi, to use Texture Reader Api you'll need to also include the Plugins from the ComputerVision example, not only the TextureReader.cs file. Let me know if it helps.

**Comment by FelixGirard** [comment]
Even if just try the ComputerVision example I get this error. I'm also a bit lost with plugins, how am I supposed to include them ? Is it only putting them in the Assets/Plugins folder ?

**Comment by pablisho** [comment]
Hi, I cannot repro your issue. I was able to run ComputerVision on an Android device, as it is when downloading it from this repo.
When running the Computer Vision example, please make sure that you didn't delete anything from its folder. If you still cannot run the ComputerVision example with no modifications, please provide a logcat of the error.

**Comment by FelixGirard** [comment]
I started with a fresh project and reimporting the package and the ComputerVision scene, to enable the texture reader my setting and only change in the project was this :
![image](https://user-images.githubusercontent.com/7445146/40380147-2e887bc4-5dc6-11e8-932d-796d64e33980.png) 
Also, here is the logcat file :
[log.txt](https://github.com/google-ar/arcore-unity-sdk/files/2027898/log.txt)

Thank you !

**Comment by FelixGirard** [comment]
I'm trying to put it with the HelloAR example. I just add add the TextureReader script not enabled like in ComputerVision and I enable it on the Start() of my controller. But no matter where I put the plugin, it seems unable to find it. But yes, it was working well with the ComputerVision example. I tried putting the plugin in :
- Assets/GoogleARCore/Examples/Plugins
- Assets/GoogleARCore/Examples/Plugins
- Assets/Plugins
- Assets/Plugins/Android

Is there a special registration for plugin that I don't know of ? This is clearly not a bug, but a question because I've not worked so much with native plugins.

**Comment by FelixGirard** [comment]
Ok I'll explain my problem for those after me : The dll wasn't found and I think it's because I moved the plugin files within unity and didn't care for the files located on the disk. Now i copied and pasted the plugins in the physical folder 'Assets/Plugins' of my project and it works. 

Thanks for helping ! 👍

**Comment by sonary01** [comment]
I am facing the same problem. When I tried to use TextureReaderApi to access the CPU images, I am getting the error given below. I didn't change anything in the ComputerVision example. Just added a new script and image(for rendering) to the ComputerVision  example. I also referred discussions in #72, #221, still I am not able to get the color image frames. Any help is much appreciated.

Error message:
> DllNotFoundException: arcore_camera_utility
GoogleARCore.Examples.ComputerVision.TextureReaderApi.Create (ImageFormatType format, Int32 width, Int32 height, Boolean keepAspectRatio) (at Assets/GoogleARCore/Examples/ComputerVision/Scripts/TextureReaderApi.cs:65)
GoogleARCore.Examples.ComputerVision.TextureReader.Update () (at Assets/GoogleARCore/Examples/ComputerVision/Scripts/TextureReader.cs:137)

Code:
```
using System;
using System.IO;
using System.Collections.Generic;
using GoogleARCore;
using UnityEngine;
using UnityEngine.UI;
using GoogleARCore.Examples.ComputerVision;
using GoogleARCore.Examples.Common;

public class ColorFrames : MonoBehaviour {

	private TextureReader TextureReaderComponent;
	private Texture2D m_TextureToRender =null;
	private byte[] m_EdgeImage =null;
	int buffersize=0;
	//public TextureReaderApi.ImageFormatType imageFormat = 
   TextureReaderApi.ImageFormatType.ImageFormatColor;
    public Image EdgeDetectionBackgroundImage;


	// Use this for initialization

	public void Start()
	{
		TextureReaderComponent = gameObject.GetComponent<TextureReader> ();
		TextureReaderComponent.OnImageAvailableCallback += OnImageAvailable;

	}
	
	// Update is called once per frame
	void Update () {

		if (!Session.Status.IsValid())
		{
			return;
		}

		using (var image = Frame.CameraImage.AcquireCameraImageBytes())
		{
			if (!image.IsAvailable)
			{
				return;
			}
				buffersize = image.Width * image.Height;
				TextureReaderComponent.enabled = true;
			    OnImageAvailable(TextureReaderApi.ImageFormatType.ImageFormatColor,image.Height, image.Height, image.Y, buffersize);
		}

	}

	private void OnImageAvailable(TextureReaderApi.ImageFormatType format,int width, int height, IntPtr pixelBuffer, int bufferSize)
	{
		if (m_TextureToRender == null || m_EdgeImage == null || m_TextureToRender.width != width || m_TextureToRender.height != height)
		{
			
				if (format == TextureReaderApi.ImageFormatType.ImageFormatColor) {
				Debug.Log("Color Image is requested"); 
					

					m_TextureToRender = new Texture2D (width, height, TextureFormat.RGBA32, false, false);
					m_EdgeImage = new byte[width * height * 4];

				} 
                              else 
			       {
				  Debug.Log("Gray Image is requested");
					m_TextureToRender = new Texture2D (width, height, TextureFormat.R8, false, false);
					m_EdgeImage = new byte[width * height];
				}
		}

		Debug.Log("Buffer size:"+ bufferSize);
		System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, m_EdgeImage, 0, bufferSize*4);

		// Update the rendering texture with the sampled image.
		m_TextureToRender.LoadRawTextureData(m_EdgeImage);
		m_TextureToRender.Apply();
		EdgeDetectionBackgroundImage.material.SetTexture("_ImageTex", m_TextureToRender);

		var encodedJpg = m_TextureToRender.EncodeToJPG();
		var path = Application.persistentDataPath;
		File.WriteAllBytes(path + "/testImage.jpg", encodedJpg);

	}

	void OnDisable()
	{
		TextureReaderComponent.enabled = false;
		TextureReaderComponent.OnImageAvailableCallback -= OnImageAvailable;

	}
}

```
