### ISSUE TITLE
Assets/GoogleARCore/SDKScripts/Managers/AnchorManager.cs(27,36):error CS0234:The type namespace name 'XR' does not exist in the namespace 'UnityEngine'.Are you msssing an assembly reference?

### ISSUE THREAD

**Issue by hanhailong** [google-ar/arcore-unity-sdk#22]
Assets/GoogleARCore/SDKScripts/Managers/AnchorManager.cs(27,36):error CS0234:The type namespace name 'XR' does not exist in the namespace 'UnityEngine'.Are you msssing an assembly reference?

How to solve it?

**Comment by StephenHodgson** [comment]
Sounds like you're using the wrong version of the editor.

**Comment by hanhailong** [comment]
@StephenHodgson  Yes，I'm using the **_Unity 2017.1.0f3_** version now,then I checked the official website,does unity must have to be above  **_Unity 2017.2 Beta 11_** or higher?

**Comment by StephenHodgson** [comment]
That is correct. Might be best to use the 2017.2 release candidate.

**Comment by hanhailong** [comment]
@StephenHodgson 
![image](https://user-images.githubusercontent.com/4241807/30850883-8f54b424-a26c-11e7-8306-a33643970bd6.png)
The official website has stated the minimum version！！！3Q！！
