### ISSUE TITLE
Can't compile for iOS

### ISSUE THREAD

**Issue by SetoKaiba** [google-ar/arcore-unity-sdk#222]
I can't compile for iOS.

> Undefined symbols for architecture arm64:
>   "_ArSession_resolveAndAcquireNewCloudAnchor", referenced from:
>       _SessionApi_ResolveCloudAnchor_m3309448601 in Bulk_GoogleARCore_1.o
>       _ExternApi_ArSession_resolveAndAcquireNewCloudAnchor_m4029966198 in Bulk_GoogleARCore_1.o
>      (maybe you meant: _ExternApi_ArSession_resolveAndAcquireNewCloudAnchor_m4029966198)
>   "_ArSession_hostAndAcquireNewCloudAnchor", referenced from:
>       _SessionApi_CreateCloudAnchor_m3876984356 in Bulk_GoogleARCore_1.o
>       _ExternApi_ArSession_hostAndAcquireNewCloudAnchor_m1469541766 in Bulk_GoogleARCore_1.o
>      (maybe you meant: _ExternApi_ArSession_hostAndAcquireNewCloudAnchor_m1469541766)
>   "_ArFrame_getTimestamp", referenced from:
>       _FrameApi_GetTimestamp_m1492695928 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArFrame_getTimestamp_m3923927618 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArFrame_getTimestamp_m3923927618)
>   "_ArSession_updateAndAcquireArFrame", referenced from:
>       _ARCoreIOSLifecycleManager__OnARKitFrameUpdated_m722746442 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArSession_updateAndAcquireArFrame_m2956215672 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArSession_updateAndAcquireArFrame_m2956215672)
>   "_ArAnchorList_acquireItem", referenced from:
>       _AnchorApi_AcquireListItem_m4256508686 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchorList_acquireItem_m1817788421 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchorList_acquireItem_m1817788421)
>   "_ArPose_create", referenced from:
>       _PoseApi_Create_m2426744117 in Bulk_GoogleARCore_1.o
>       _ExternApi_ArPose_create_m455975273 in Bulk_GoogleARCore_1.o
>      (maybe you meant: _ExternApi_ArPose_create_m455975273)
>   "_ArAnchor_getPose", referenced from:
>       _AnchorApi_GetPose_m3904778067 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_getPose_m612023754 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchor_getPose_m612023754)
>   "_ArAnchorList_getSize", referenced from:
>       _AnchorApi_GetListSize_m2749379767 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchorList_getSize_m2193174137 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchorList_getSize_m2193174137)
>   "_ArSession_destroy", referenced from:
>       _ARCoreIOSLifecycleManager_ResetSession_m2501165725 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArSession_destroy_m326121169 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArSession_destroy_m326121169)
>   "_ArSession_create", referenced from:
>       _ExternApi_ArSession_create_m3460313138 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArSession_create_m3460313138)
>   "_ArAnchorList_destroy", referenced from:
>       _AnchorApi_DestroyList_m507084046 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchorList_destroy_m3928424137 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchorList_destroy_m3928424137)
>   "_ArAnchorList_create", referenced from:
>       _AnchorApi_CreateList_m213097415 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchorList_create_m375693803 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchorList_create_m375693803)
>   "_ArAnchor_getCloudAnchorState", referenced from:
>       _AnchorApi_GetCloudAnchorState_m3801379099 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_getCloudAnchorState_m2728214828 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchor_getCloudAnchorState_m2728214828)
>   "_ArPose_destroy", referenced from:
>       _PoseApi_Destroy_m2977467867 in Bulk_GoogleARCore_1.o
>       _ExternApi_ArPose_destroy_m202848633 in Bulk_GoogleARCore_1.o
>      (maybe you meant: _ExternApi_ArPose_destroy_m202848633)
>   "_ARKitAnchor_create", referenced from:
>       _CloudServiceManager_CreateCloudAnchor_m3948842918 in Bulk_GoogleARCore_0.o
>       _ExternApi_ARKitAnchor_create_m3526505584 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ARKitAnchor_create_m3526505584)
>   "_ArAnchor_acquireCloudAnchorId", referenced from:
>       _AnchorApi_GetCloudAnchorId_m1673892043 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_acquireCloudAnchorId_m3525646899 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchor_acquireCloudAnchorId_m3525646899)
>   "_ArPose_getPoseRaw", referenced from:
>       _PoseApi_ExtractPoseValue_m4237254583 in Bulk_GoogleARCore_1.o
>       _ExternApi_ArPose_getPoseRaw_m1187545805 in Bulk_GoogleARCore_1.o
>      (maybe you meant: _ExternApi_ArPose_getPoseRaw_m1187545805)
>   "_ARKitAnchor_release", referenced from:
>       _CloudServiceManager_CreateCloudAnchor_m3948842918 in Bulk_GoogleARCore_0.o
>       _ExternApi_ARKitAnchor_release_m162113648 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ARKitAnchor_release_m162113648)
>   "_ArAnchor_detach", referenced from:
>       _AnchorApi_Detach_m3499419975 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_detach_m2705649792 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchor_detach_m2705649792)
>   "_ArFrame_release", referenced from:
>       _ARCoreIOSLifecycleManager__OnARKitFrameUpdated_m722746442 in Bulk_GoogleARCore_0.o
>       _FrameApi_Release_m1049149260 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArFrame_release_m810911495 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArFrame_release_m810911495)
>   "_ArString_release", referenced from:
>       _AnchorApi_GetCloudAnchorId_m1673892043 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArString_release_m2753487005 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArString_release_m2753487005, _ExternApi_ArString_release_m2359065355 )
>   "_ArAnchor_getTrackingState", referenced from:
>       _AnchorApi_GetTrackingState_m1475763831 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_getTrackingState_m2314327404 in Bulk_GoogleARCore_0.o
>      (maybe you meant: _ExternApi_ArAnchor_getTrackingState_m2314327404)
>   "_ArAnchor_release", referenced from:
>       _Anchor_Factory_m2784952542 in Bulk_GoogleARCore_0.o
>       _AnchorApi_Release_m2264091913 in Bulk_GoogleARCore_0.o
>       _Anchor_OnDestroy_m4178574533 in Bulk_GoogleARCore_0.o
>       _XPAnchor_Factory_m906341095 in Bulk_GoogleARCore_0.o
>       _XPAnchor_OnDestroy_m3393370680 in Bulk_GoogleARCore_0.o
>       _ExternApi_ArAnchor_release_m1040360027 in Bulk_GoogleARCore_0.o
>       _CloudServiceManager__UpdateCloudAnchorRequest_m3199307262 in Bulk_GoogleARCore_0.o
>       ...
>      (maybe you meant: _ExternApi_ArAnchor_release_m1040360027)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SetoKaiba** [comment]
OK. I see. It's the problem of POD.

**Comment by jvetulani** [comment]
How did you manage to resolve this? I'm having the same exact issue.

**Comment by SetoKaiba** [comment]
@jvetulani Just run pod update yourself in mac.

**Comment by andresmqa** [comment]
@SetoKaiba are you working on any YGO AR project?
