### ISSUE TITLE
ARFaceAnchor selector inside GARSession hostCloudAnchor:error? - True Depth api

### ISSUE THREAD

**Issue by dzak83** [google-ar/arcore-unity-sdk#223]
Hi,
My app submission to iOS failed due to reference to True Depth api and from the logs I got, I feel like new AR Core 1.2 might be responsible for it. I couldn't find anything myself in the code but can you check in your code if you are referencing ARFaceAnchor selector? 

The logs indicate "GARSession **hostCloudAnchor**:error" which looks like AR Core anchor cloud sharing.

Thanks!

Thanks,
Smart AR Home team
http://smartarhome.com/

**Comment by dzak83** [comment]
The comment in the ApiArStatus.cs says:
> // HostCloudAnchor() failed because the anchor is not a type of anchor that is currently supported for hosting.
ErrorAnchorNotSupportedForHosting = -16,

which might indicate that there is a check for ARFaceAnchor type, which could trigger True Depth api and cause failure for all app submissions to Apple Store.

Please check and advise. If that's the case, any workaround suggestions are more than welcome!

**Comment by sammcd** [comment]
Thanks for alerting about this issue!

You are correct, that our host anchors specifically disallows ARFaceAnchors, this does mean we reference that symbol. We are working on removing our reference to this symbol asap.

In the mean time, can you give more information on the rejection? Any chance it was a request for additional information? If so feel free to communicate that we simply reference it to purposefully disallow it. I assume you aren't even running in ARFaceTrackingConfiguration, and it might be worth mentioning this to Apple.

**Comment by josselinco** [comment]
Sure ! My rejection said : 

Guideline 2.5.1 - Performance - Software Requirements


During review, we found that your app includes TrueDepth APIs. However, we were not able to locate any features in your app that use TrueDepth APIs.

Next Steps

If your app does not include any features that use TrueDepth APIs, please remove them from your app. 

As your app uses the Unity ARKit plugin, it would be appropriate to update to the latest version, which includes a setting that allows you to exclude TrueDepth APIs.

If your app does include features that use TrueDepth APIs, please reply to this message in Resolution Center to provide information on how to locate them.

**Comment by dzak83** [comment]
I also got the logs after I failed certification few times which helped me debug the issue.

> Hello,

Thank you for your response. 

This app contains direct references to the ARFaceAnchor selector. To pass through review it would be appropriate to remove this selector reference (found in [GARSession hostCloudAnchor:error:]) or to implement TrueDepth features into the app. Any obfuscation of this selector use instead of removal will cause further delay and possible removal from the Apple Developer Program.


Best regards,

App Store Review

**Comment by sammcd** [comment]
Thanks for the additional information, this is very helpful.

We are still working on a fix, and will update this thread as soon as we have a resolution.

**Comment by dzak83** [comment]
Thanks! I hope you guys get it fixed soon. Would be great if we could use the same face tracking flag we set for AR Kit plugin. It should be accessible from settings file. 

Also today our app failed the Apple review on different issue which confirms that removing AR Core from the build solved the problem temporary. 

Thanks,
Smart AR Home team
http://smartarhome.com/

**Comment by sammcd** [comment]
We have a fix, but it will still take some time to release it publicly. If you are interested in getting a release candidate build earlier, feel free to reach out to me at sammcd@google.com with a little information on what you are doing (ex. Unity vs Unreal vs iOS Native).

Thanks again for your time and patience.

**Comment by dzak83** [comment]
Great! I sent you an email with the details and I will be happy to validate the fix.

**Comment by dzak83** [comment]
Good news, the RC candidate passed the review and fix looks good.

**Comment by sammcd** [comment]
Today we released version 1.2.1 of ARCore which includes the fix mentioned in this thread.

Please update to the 1.2.1 release, and this issue should be resolved.
