### ISSUE TITLE
Editor crash attempting to play an example scene targetting iOS

### ISSUE THREAD

**Issue by pap3rinik** [google-ar/arcore-unity-sdk#224]
Hi guys,
I was attempting to play on editor, targetting iOS, an example scene from new ARCORE 1.2 and I experienced a sudden crash. If you target Android all runs fine.
This happens all the time with all the example scenes.

Unity 2017.3.1f1, OSX 10.13.4

**Comment by pablisho** [comment]
Hi, [InstantPreview](https://developers.google.com/ar/develop/unity/instant-preview) (Play in editor) is Android only. Also, the only supported scene in iOS is [CloudAnchors](https://developers.google.com/ar/develop/unity/cloud-anchors/cloud-anchors-quickstart-unity-ios), the rest are Android only.
