### ISSUE TITLE
Unity 2017.3.0b1 support?

### ISSUE THREAD

**Issue by oscarbg** [google-ar/arcore-unity-sdk#23]
Maybe I'm doing something but I can't find "ARCore Supported" on XR Settings on Unity using 2017.3.0b1 on Windows..
any help..
thanks..

**Comment by nathanmartz** [comment]
Did you install the Android development package for Unity? Are you setup to
build for Android generally (e.g. can build and run a non-ARCore APK)?

-Nathan

**Comment by hanhailong** [comment]
support

**Comment by chaosemer** [comment]
This is a known issue with the 2017.3.0b1 release. For now please use 2017.2.0b11 or more recent for ARCore development.

**Comment by chaosemer** [comment]
The recent versions of the 2017.3 beta work with ARCore. I just verified now with 2017.3.0b5.
