### ISSUE TITLE
SR300 with Windows 10 depth is not working

### ISSUE THREAD

**Issue by BahramSoheili** [google-ar/arcore-unity-sdk#232]
Hi

I have involved with a new C# project related to background segmentation with sr300 and with SDK R3 2016 with windows 10 as I could not use to SDK2.0 in terms of shortages.
The segmentation sometimes works but most of the time it could not initialize(init) the SenseManager and stuck and getting hang at the starting point.
I would appreciated if you share your experiences about sr300 segmentation upon SDK R3 2016.
Best regards,
Bahram

**Comment by pablisho** [comment]
Hi, this is ARCore SDK for Unity. I believe your issue is not related to it. Feel free to reopen if you are experiencing issues with ARCore in particular.
