### ISSUE TITLE
Can't build for iOS

### ISSUE THREAD

**Issue by pcriadoperez** [google-ar/arcore-unity-sdk#239]
I have tried both 2018.1 and 2017.4 and get this error:

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/ARKitHelper.cs(27,26): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

Assets/GoogleARCore/SDK/Scripts/Managers/ARCoreIOSLifecycleManager.cs(31,26): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

\Assets/GoogleARCore/SDK/Scripts/XPSession.cs(26,26): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/ARKitHelper.cs(28,55): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/ARKitHelper.cs(39,22): error CS0246: The type or namespace name `ARHitTestResult' could not be found. Are you missing an assembly reference?

Assets/GoogleARCore/SDK/Scripts/Managers/ARCoreIOSLifecycleManager.cs(128,58): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

Assets/GoogleARCore/SDK/Scripts/XPSession.cs(52,70): error CS0246: The type or namespace name `UnityARUserAnchorComponent' could not be found. Are you missing an assembly reference?

**Comment by pcriadoperez** [comment]
That did it thanks! The version from the Asset store gave me an error. But it worked when I used the latest version from bitbucket:
https://bitbucket.org/Unity-Technologies/unity-arkit-plugin/downloads/

**Comment by BijayanBhattarai** [comment]
i am currently having same issue unable to solve
Any advices
