### ISSUE TITLE
Use "SetTriangles" instead of "SetIndices"

### ISSUE THREAD

**Issue by zarubin-alexey** [google-ar/arcore-unity-sdk#240]
I believe in [DetectedPlaneVisualizer.cs](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/Common/Scripts/DetectedPlaneVisualizer.cs  ) line 208
`m_Mesh.SetIndices(m_MeshIndices.ToArray(), MeshTopology.Triangles, 0);`

should be replaced with 
`m_Mesh.SetTriangles(m_MeshIndices, 0);`

It does not require applying "ToArray" method.

**Comment by pablisho** [comment]
Hi, thanks for the enhancement proposal. We'll consider it for future releases.

**Comment by fredsa** [comment]
Fixed in ARCore for Unity SDK 1.6.0
