### ISSUE TITLE
Unity ARCore cloud points are duplicated and drift

### ISSUE THREAD

**Issue by peetonn** [google-ar/arcore-unity-sdk#245]
It's hard to explain the issue I'm seeing, but I've captured a [video](https://www.youtube.com/watch?v=EdtjjSyMu0Y&feature=youtu.be) of what's going on. Basically, cloud points are duplicated (thus, rendered twice) and drift as the screen moves, without being stuck into physical space. 
Not sure why it's happening -  app used to work normally before, but then there was a project repo cleanup where Temp and Library folders were removed from the repo, so Unity had to recompile them. And then this problem started to manifest.

**Comment by bopangzz** [comment]
This looks like a tracking issue. Can you try add a static cube and see if the cube could stay at the same spot while you move your camera?

**Comment by peetonn** [comment]
@bopangzz I've updated Unity to the latest 2018.1.4f1 and ARCore to 1.2.1, still having this issue
here's the video with bounding boxes placed in 3d https://youtu.be/41BFY2Uym7o

**Comment by peetonn** [comment]
@bopangzz I think I've fixed the problem by re-importing `ARCore Device` prefab from `GoogleARCore/Prefabs` folder.

**Comment by pablisho** [comment]
@peetonn I'm closing this because I believe your issue was solved, feel free to reopen if you still experience issues with this.
