### ISSUE TITLE
Can I use Cloud Anchors with Unity Network Manager?

### ISSUE THREAD

**Issue by leshchenko** [google-ar/arcore-unity-sdk#246]
Hi. Can I use Cloud Anchors alongside Unity Network Manager? Or could you please give example how to sync objects by Cloud Anchors, if it is possible? Also, it would be useful for me to know how to send position in the real world and restore this position on another device.

**Comment by ls29322** [comment]
@leshchenko technically it works with Unity Network Manager (specifically with Unity's Network Server), maybe what you are asking for is more a u-net standard code example? With [Commands], [ClientRpcs] and that kind of stuff?

**Comment by leshchenko** [comment]
@ls29322 My main problem it is "How to synchronize system of coordinate between 2 devices?".

**Comment by bopangzz** [comment]
Cloud anchor should work with any network solution. All you need to do is to synchronize the cloud id from one device to the other device.

**Comment by leshchenko** [comment]
@bopangzz sorry for confusion, I would like to sync it by p2p connection with help NetworkManager. Without Cloud.

**Comment by bopangzz** [comment]
Yeah, you can sync the cloud id though p2p connection, but you will need
internet connection to access Google Cloud Anchor API to host and resolve
anchor.

**Comment by leshchenko** [comment]
@bopangzz Got it, thanks for the tip.

**Comment by pablisho** [comment]
Hi, I'm closing this because I believe your question was solved. Feel free to reopen if you still have questions about it.

**Comment by bgdevpj** [comment]
Hi,

I just want to clarify that there isn't a way to resolve and pass anchors between iOS and Android without the Cloud Services? I am doing a cross platform setup using Photon and I was trying to find out if I could do it without accessing the services.

Thanks
