### ISSUE TITLE
Support for older iOS versions

### ISSUE THREAD

**Issue by Klipi** [google-ar/arcore-unity-sdk#247]
I'm currently building an application that needs to support older iOS versions than iOS 11. Having the Android version of the app run ARCore shouldn't force me to also upgrade the iOS version. I'm not using the cloud anchors. Is this currently possible somehow?

**Comment by Klipi** [comment]
I've managed to temporarily work around the issue by wrapping all the source files with `#ifdef UNITY_ANDROID` and disabling everything in the Play Services Resolver's iOS settings. It would be nice if the SDK supported this with e.g. a simple compilation flag by default so I don't need to manually update the source files whenever there's a new release

**Comment by kkc0923** [comment]
Same issue here. I need old iOS support for Non-AR mode.

**Comment by bopangzz** [comment]
Thanks for the bug report, we will provide a way to exclude ARCore SDK when targeting iOS in the next release.

For now, you can disable the Play Services Resolver's iOS setting and modify the "__Internal" to "NOT_AVAILABLE" in these two [files](https://github.com/google-ar/arcore-unity-sdk/search?q=__Internal&unscoped_q=__Internal) to fix the linking problem.

**Comment by bopangzz** [comment]
@Klipi Can you describe what error prevent you building app against iOS 10 when Play Services Resolver's iOS is enabled? Are you using the iOS 11 SDK? 

I tried on my machine and it build fine when setting the minimal SDK version to iOS 10 and using iOS 11 SDK.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and now you can disable the iOS support through Edit->ProjectSettings->ARCore-> iOS support enabled.
