### ISSUE TITLE
No turn on camera flash apis

### ISSUE THREAD

**Issue by arghyasur1991** [google-ar/arcore-unity-sdk#25]
I need to turn on flash from ARCore app but there are no ways to do so. Even if I turn the flash on using android apis before arcore startup, it gets disabled on arcore session initialization. Vuforia sdk provides option to turn the flash on, so ARCore should also provide one to do so.

**Comment by nathanmartz** [comment]
Thanks for the feature request. We're discussing this API internally now. Can you provide a bit more information about the use case you have in mind for the flash?

**Comment by arghyasur1991** [comment]
for something like a horror game inside your room where players will want to play in low light condition using torch.

**Comment by nathanmartz** [comment]
Thanks for the context. We're looking into this now and it'll be in the release notes if/when we add support for it.

**Comment by cgfarmer4** [comment]
I would like to +1 this feature. Its very useful since AR works poorly in the dark.

**Comment by cgfarmer4** [comment]
It should also be noted that you can do this with ARKit. Having similar access would be awesome!

**Comment by mr0ng** [comment]
@nathanmartz Any updates? Looks like we still can't use flashlight / torch with ARCore

**Comment by synthercat** [comment]
+1 it will be a GREAT feature

**Comment by clebertavares** [comment]
+1, still waiting...
