### ISSUE TITLE
Editor warnings in Android build

### ISSUE THREAD

**Issue by zarubin-alexey** [google-ar/arcore-unity-sdk#251]
In my Android build, I get "ARCore light estimation cannot be disabled in editor." and "ARCore plane finding cannot be disabled in editor." warnings. I believe there is a simple mistype in "InstantPreviewManager" class line 192:
`            if (Application.isEditor || session == null)
`
Should be replaced with:
`            if (!Application.isEditor || session == null)
`

**Comment by pablisho** [comment]
Hi, Thanks for the report. This was a known issue internally and will be fixed in the next release.

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore Unity SDK v1.3.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.3.0). Feel free to reopen if you still experience the issue.
