### ISSUE TITLE
World Coordinate origin

### ISSUE THREAD

**Issue by sonary01** [google-ar/arcore-unity-sdk#254]
Where is the world coordinate origin of the ARCore tracking? Is it the initial position of the device camera when an AR session starts? When the phone moves, the world coordinate is still the same? (not based on the current phone position!). How to reset the world coordinate system based on a new reference point? I couldn't find any reference on this.

**Comment by bopangzz** [comment]
Yeah, the ARCore tracking origin (0,0,0) is the real world position where the AR session starts with. The tracking space pose is mapped to the Camera's relative transform in Unity world space.  Note that the Camera is usually hooked up as a child game object under the 'ARCore Device' game object.

I am not quite understand what are you trying to achieve. Are you trying to map the ARCore tracking origin in Unity world space to the pose of an anchor you placed? If so, you can first get the Anchor's Unity world space transform and then calculate the revert transform and set the transform of 'ARCore Device' to that revert transform. And if you want to keep maintain the origin in that physical spot, you should recalculate the revert transform every time the anchor pose is changed.

**Comment by sonary01** [comment]
Thank you very much. I have done some coordinate transformation to get the new reference origin.

**Comment by mantach86** [comment]
Hi guys,
am working on creating a new model and put on the ground when clicking a new button, I created a new model but the problem is it follow me and the camera when I move I need it to be fixed any suggestions?
here is the code:

    public void DuplicateObject()
    { 
		GameObject Cloud = GameObject.Find("Point Cloud");  
		//Vector3 CameraPosition = new Vector3(MainCamera.transform.position.x , 0 , MainCamera.transform.position.z + distance);
		Vector3 CameraPosition = new Vector3(MainCamera.transform.position.x, Cloud.transform.position.y , MainCamera.transform.position.z + distance );
 
		NewObject = GameObject.Instantiate(Gobject , transform.position , Quaternion.identity);
		NewObject.transform.position = MainCamera.transform.position + MainCamera.transform.forward * distance;
		positionx = NewObject.transform.position.x;
		positiony = NewObject.transform.position.y;
		positionz = NewObject.transform.position.z;

		LocalPosition = new Vector3(positionx ,positiony , positionz );

		Vector3 AnchorPos =  NewObject.transform.position;
		Pose pose = new Pose(AnchorPos, NewObject.transform.rotation);
		_anchor = Session.CreateAnchor(pose , null);
		//NewObject.transform.Rotate(0, 180, 0, Space.Self);
		NewObject.transform.Rotate(0, k_ModelRotation,0 , Space.Self);
		_anchor.transform.parent = Cloud.transform;
		NewObject.transform.parent = _anchor.transform;
	}
