### ISSUE TITLE
ARCoreProjectSettings: Version string value is wrong

### ISSUE THREAD

**Issue by zarubin-alexey** [google-ar/arcore-unity-sdk#257]
[ARCoreProjectSettings](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Utility/ARCoreProjectSettings.cs) still uses v1.1.0, while library is 1.2.1.  
This lead to some misunderstanding.

Are there any reasons to have ARCoreProjectSettings class to be used only in the editor? I wish to know its value real-time on Android.

**Comment by bopangzz** [comment]
That is a bug in 1.2.1 release. We will make sure to update that value in the next release.
