### ISSUE TITLE
Why are we required to add iOS ARCore SDK when using ARKit exclusively on iOS?

### ISSUE THREAD

**Issue by sebrk** [google-ar/arcore-unity-sdk#261]
We have an app that was originally made for iOS. Now the client wants to port it to Android. All well, we download this package and unselect everything regarding to iOS. We use our own ARKit hooks for that. However linking fails because the ARCore for iOS framework is not added. Why are we forced to use this?

It seems that Unity ARCore plugin has hard dependencies to the iOS ARCore SDK?

**Comment by pablisho** [comment]
Hi, thanks for the report. Could you explain a little more of what's your project set up, your build target, what is the error and what would have been the expected behaviour?

**Comment by Klipi** [comment]
I had a similar question in #247. For iOS 11 it's possible to include the ARCore library as a dependency, but for earlier versions ARCore will prevent us from compiling the app at all.

I worked around it by adding #if UNITY_ANDROID to all ARCore files. Make sure to keep the serialized properties and fields in place so you don't lose references and data whenever switching platforms. It would be great if this was supported out of the box :)

**Comment by sebrk** [comment]
Thing is there are options to not include and generate podfile for iOS but even with everything unchecked I get the linker errors. Would love an official response on this.

**Comment by bopangzz** [comment]
Can you guys try change the "__Internal" to "NOT_AVAILABLE" in these [two files](https://github.com/google-ar/arcore-unity-sdk/search?q=__Internal&unscoped_q=__Internal) and see if that resolves your issue?

**Comment by sebrk** [comment]
I should add that we also have a fallback solution for non-ar devices and therefore target iOS 10.

**Comment by bopangzz** [comment]
The issue with iOS is that everything is static linked on iOS and since ARCore provide cloud anchor support on iOS, it will need to static link the ARCore iOS library.

We will prioritize this issue and resolve it in future releases. Stay tuned.

**Comment by sebrk** [comment]
@bopangzz a framework can be dynamic. Why don’t you package it like that instead?

**Comment by bopangzz** [comment]
Unfortunately, Unity doesn't support dynamic framework on iOS yet. But we have prioritized this issue and will make the ARCore iOS support an opt-in option in ARCore settings in the next release. 

For now, you can delete AppDependencies.xml under Assets/GoogleARCore/Editor folder and change the "__Internal" to "NOT_AVAILABLE" in these [two files](https://github.com/google-ar/arcore-unity-sdk/search?q=__Internal&unscoped_q=__Internal) to workaround this issue.

Let me know if there is other issues regards this problem.

**Comment by sebrk** [comment]
@bopangzz You are right, although isn't the framework added by a podfile later anyway? In any way, nevermind - you seem to have this under control. Thank you for swift communication and feedback!

**Comment by pablisho** [comment]
Thanks @sebrk , we'll keep it open until we release a fix for it.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and now you can disable the iOS support through Edit->ProjectSettings->ARCore-> iOS support enabled.
