### ISSUE TITLE
Disable Augmented Images at runtime

### ISSUE THREAD

**Issue by LCernei** [google-ar/arcore-unity-sdk#264]
I need Augmented Images only for initialisation. After finding the position of the image I want to disable this feature. How to stop tracking the image? Or how to disable a particular image?

I tried:
* modifying the database content
* setting another database
* setting another Session Config
* getting the position coordinates only once
But after re-positioning of the image in the real world, it creates a new augmented object at the new position.

ARCore 1.2, Unity3D 2017.4.3f1

**Comment by bopangzz** [comment]
There is not way to disable a particular image right now. You will have to switch to another database to do that.

If you want to disable the augmented image entirely, you can set the database to null in session config.

**Comment by LCernei** [comment]
This did not work.

Let me explain the scenario:
* I point the camera to a marker.
* It gives a Pose, at which I create an anchor and instantiate a prefab as a child.
* I want the prefab to stay in place, then as you pointed, I assign `null` to the database (it becomes null, checked with Instant Preview).
* Then I move the marker to another place, let's say 2m away. 
* I point the camera at it again, and and the prefab "teleports" at the new position (why?).

How it recognizes the image, when the DB is null? And how to stop it?

**Comment by LCernei** [comment]
I somehow got around this problem.  
In the editor, in Session Config I disabled Augmented Images Database (set to `None`).  
In code (in `Start()` method) I assigned to it MyDatabase, and after I found the marker I set it again to `null`.

About the previous solution, idk, maybe when Unity builds, it compiles the database , then the images sort of remain in memory.

**Comment by lichenyigit** [comment]
@LCernei I want to know how you modifying the database content.
