### ISSUE TITLE
Rotate and position the camera

### ISSUE THREAD

**Issue by minnes09** [google-ar/arcore-unity-sdk#266]
Hi, 
I´m trying to orientate the camera respecting to the north pole, so that I have my phone aligned with it. 
I take the north rotation correctly from the Input.compass, but then the camera doesn´t rotate. I´ve tried to move it in the scene at runtime, but also that doesn´t work. 
I thought I could rotate the ARCore Device (and so all the childs) but also this approach was a failure: ARCore Device moves correctly, but the camera stays still.
Thank you for the support.

**Comment by minnes09** [comment]
Yes, I want the scene to be aligned with the north pole. 
I already know where the north is in the scene, so if I start with the camera in the right orientation I can align them.

**Comment by juanmajr93** [comment]
Yes I want do the same. ArCore camera must be moved around my scene in Unity and it is always still

**Comment by pablisho** [comment]
Hi @minnes09, sorry for the late reply. The issue is that ARCore tracking is relative to the starting point of the device. To align or anchor it to a real world object (in this case it would be the north pole), I think the best way to do it is with [Augmented Images](https://developers.google.com/ar/develop/unity/augmented-images/), then you can position your virtual objects relative to it. Let me know if this helps.

**Comment by minnes09** [comment]
Hi @pablisho, thank you for the answer. 
I had thought about using the AugmentedImage, but due to my use case I can´t use it. 
Since also the smartphone compass is not reliable I have decided not to align the camera with the north pole.
About the orientation: the problem occurs only when I use the Instant Preview, because the camera is fixed to the origin position. Using the app on the smartphone permits to correctly rotate the Camera Device object and all the children. It´s a bit hard to test, but the app works :)

**Comment by pablisho** [comment]
@minnes09 Would you mind creating a new issue and elaborating a bit more about the InstantPreview problem/difference in behaviour compared to running on device?

**Comment by minnes09** [comment]
@pablisho I have created a new issue #327

**Comment by pablisho** [comment]
Thanks @minnes09 we'll keep track of the InstantPreview issue there.
