### ISSUE TITLE
Still getting il2cpp failure in ARCore 1.3, in Unity 2018.1.5f1

### ISSUE THREAD

**Issue by patrickoshaughnessey** [google-ar/arcore-unity-sdk#269]
Here are the relevant Unity Editor log entries:

`Failed running /Applications/Unity/Hub/Editor/2018.1.5f1/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="/<Redacted>/Temp/StagingArea/assets/bin/Data/Native/armeabi-v7a/libil2cpp.so" --cachedirectory="/<Redacted>/Assets/../Library/il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="/Applications/Unity/Hub/Editor/2018.1.5f1/PlaybackEngines/AndroidPlayer/Tools/bdwgc/include" --additional-include-directories="/Applications/Unity/Hub/Editor/2018.1.5f1/PlaybackEngines/AndroidPlayer/Tools/libil2cpp/include" --tool-chain-path="/Users/<Redacted>/dev/android-ndk-r13b" --map-file-parser="/Applications/Unity/Hub/Editor/2018.1.5f1/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Assembly-CSharp.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/3rdParty.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Utility.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/DataLayer.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Root.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/UnityEngine.UI.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/UnityEngine.SpatialTracking.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/TextMeshPro-2017.3-1.0.56-Runtime.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Atesh.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Atesh.WindowsAndWidgets.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Atesh.MagicAutoLinker.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Atesh.WeNeedCreatedMessage.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/Atesh.ComponentModel.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/UnityEngine.Analytics.dll" --assembly="/<Redacted>/Temp/StagingArea/assets/bin/Data/Managed/UnityEngine.dll" --generatedcppdir="/<Redacted>/Temp/StagingArea/Il2Cpp/il2cppOutput" 

stdout:
Building libil2cpp.so with AndroidToolChain.
	Output directory: /<Redacted>/Temp/StagingArea/assets/bin/Data/Native/armeabi-v7a
	Cache directory: /<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache
ObjectFiles: 621 of which compiled: 0
Total compilation time: 601 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: /Users/<Redacted>/dev/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/fy/hbzmpwc17zl0d24hr6yn8btc0000gn/T/tmpwpofYy.tmp" -o "/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_6036F5023F18AA85654E582F60BA6942/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "/Users/<Redacted>/dev/android-ndk-r13b/platforms/android-16/arch-arm" -gcc-toolchain "/Users/<Redacted>/dev/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "/Users/<Redacted>/dev/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" -lgnustl_static -llog -Xlinker -Map="/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_6036F5023F18AA85654E582F60BA6942/libil2cpp.map" -rdynamic -fPIE -pie -fuse-ld=bfd

clang++: warning: argument unused during compilation: '-pie'
/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/3C1B42412967C3A5401B73C7049E36F0.o: In function `UnityARVideoFormat_EnumerateVideoFormats_m2145873851':
/<Redacted>/Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Assembly-CSharp_2.cpp:27191: undefined reference to `EnumerateVideoFormats'
/<Redacted>/Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Assembly-CSharp_2.cpp:27191: undefined reference to `EnumerateVideoFormats'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(IEnumerable`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: /Users/<Redacted>/dev/android-ndk-r13b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/fy/hbzmpwc17zl0d24hr6yn8btc0000gn/T/tmpwpofYy.tmp" -o "/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_6036F5023F18AA85654E582F60BA6942/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "/Users/<Redacted>/dev/android-ndk-r13b/platforms/android-16/arch-arm" -gcc-toolchain "/Users/<Redacted>/dev/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "/Users/<Redacted>/dev/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a" -lgnustl_static -llog -Xlinker -Map="/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/linkresult_6036F5023F18AA85654E582F60BA6942/libil2cpp.map" -rdynamic -fPIE -pie -fuse-ld=bfd

clang++: warning: argument unused during compilation: '-pie'
/<Redacted>/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/3C1B42412967C3A5401B73C7049E36F0.o: In function `UnityARVideoFormat_EnumerateVideoFormats_m2145873851':
/<Redacted>/Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Assembly-CSharp_2.cpp:27191: undefined reference to `EnumerateVideoFormats'
/<Redacted>/Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Assembly-CSharp_2.cpp:27191: undefined reference to `EnumerateVideoFormats'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(IEnumerable`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
   at Program.Main(String[] args)

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunNetCoreProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:79)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:360)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(ICollection`1, String, String, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:343)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:162)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

Exception: /Applications/Unity/Hub/Editor/2018.1.5f1/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:79)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:360)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (System.Collections.Generic.ICollection`1[T] userAssemblies, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:343)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:162)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a798aa15a3b64b78b7b748372c1177e2>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a798aa15a3b64b78b7b748372c1177e2>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <a798aa15a3b64b78b7b748372c1177e2>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <a798aa15a3b64b78b7b748372c1177e2>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:285)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

Error building Player: 3 errors

Build completed with a result of 'Failed'
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x0021f] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:182 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00065] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:89 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
`

**Comment by pablisho** [comment]
Hi, Thanks for the report. I reopened this internally to fix it.

**Comment by pablisho** [comment]
Hi @patrickoshaughnessey, I think this issue may be in ARkit plugin and not ARCore. Did you try in a project with out it?

**Comment by patrickoshaughnessey** [comment]
Hi @pablisho - I have not. Although, ARKit is required for ARCore on iOS, is it not?

**Comment by patrickoshaughnessey** [comment]
Hi @pablisho - it looks like you are correct: https://bitbucket.org/Unity-Technologies/unity-arkit-plugin/issues/25/android-il2cpp-build-fail

**Comment by pablisho** [comment]
@patrickoshaughnessey closing this as this needs to be fixed in their plugin and not in ARCore plugin.
