### ISSUE TITLE
DiffuseWithLightEstimation shader too dark in low lighting

### ISSUE THREAD

**Issue by odbol** [google-ar/arcore-unity-sdk#27]
First I wanted to say I love this library and it's super easy and fun to get started. Thanks!

I've exported voxel models from MagicaVoxel into the Unity sample project. I then applied the `ARCore/DiffuseWithLightEstimateion` [sic] shader to the models. 

On my Pixel, it seems to perform pretty well in daylight and bright indoor lighting, but with lower light situations like a bar or street night lighting, all the models are pitch black (even though there's enough light in the scene to see the sidewalk and detect surfaces). 

Am I doing something wrong? Should I be adding light sources to my Unity scene, or using a normal map with the specular shader or something? Or is there a way to tweak the shader so it never dips below a certain lighting intensity?

**Comment by nathanmartz** [comment]
Can you post some screenshots of the behavior you are seeing? Also, do you have any regular unity lights in the scene or are you depending entirely on the light estimation to light your objects?

**Comment by odbol** [comment]
I'm depending completely on the light estimation shader. Does that shader also take regular unity lights into account? Should I be adding other lights to my scene? I just used the sample project.

![screenshot_20171002-172049](https://user-images.githubusercontent.com/550985/31848099-5f238b46-b5df-11e7-9b28-dc9ed0bcd820.png)
![screenshot_20171002-213504](https://user-images.githubusercontent.com/550985/31848100-5f7a0304-b5df-11e7-8cd2-2e7ee0494c95.png)

**Comment by nathanmartz** [comment]
We discussed this internally and the behavior is about what we expect, but there are a few things you can change to get better results.
 1) Try moving the directional light in the scene so that it's more at an angle, and not straight down.
 2) Consider adding a sky light so that you have a more natural "ambient" term.
