### ISSUE TITLE
ARCore camera bug

### ISSUE THREAD

**Issue by robrtoprz** [google-ar/arcore-unity-sdk#270]
Hi, I have this problem, how can I solve it?
I'm using Unity 2018.1.0f2, ARCore SDK v1.2.1, Samsung Galaxy S8.

Thanks.

![screenshot_20180622-175149_furniture arcore test](https://user-images.githubusercontent.com/31904585/41802514-e078474a-7646-11e8-84be-ee3abdab2f71.jpg)

**Comment by pablisho** [comment]
Hi, thanks for the report. With the information that you provide it's hard to help. Could you give more info about what you are trying to do? Are you basing your project from one of our examples? What modifications did you do to it? Thanks.

**Comment by robrtoprz** [comment]
Hi Pablisho, was my mistake I change the script and that happen. Thanks.

**Comment by pablisho** [comment]
@robrtoprz Thanks for the heads up.
