### ISSUE TITLE
Sometimes objects were placed vertically in plane arcore unity.

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-unity-sdk#272]
Iam using google arcore unity sdk.Iam using horizontal plane mode for placing 3d objects and also disabled vertical plane detection,some times objects were placed vertically but the plane only detected in horizontal mode.How can i fix this issue?

3d objects placed like this

![img-20180626-wa0000](https://user-images.githubusercontent.com/13533279/41894467-9a1f1e2e-793c-11e8-8892-1a4b79973477.jpg)
![img-20180626-wa0001](https://user-images.githubusercontent.com/13533279/41894468-9a5ccd3c-793c-11e8-95b7-93341126d84d.jpg)

**Comment by ArigarasuthanRepo** [comment]
I checked Andy model provided by google arcore examples it was also placed like this

![img_20180627_133001](https://user-images.githubusercontent.com/13533279/41960906-975a2aee-7a0e-11e8-982d-8d7c092361d2.jpg)

**Comment by pablisho** [comment]
Hi, can you show me the code you are using to perform the hit test? In particular, which TrackableHitTestFlags are you using? If you are using FeaturePointWithSurfaceNormal, it may not being placed on a plane, but on a FeaturePoint.

**Comment by ArigarasuthanRepo** [comment]
Ok please wait i will share you the code.

**Comment by ArigarasuthanRepo** [comment]
`if (Input.touchCount > 0 && (touch = Input.GetTouch(0)).phase == TouchPhase.Began)
            {
                TrackableHit hit;
                TrackableHitFlags raycastFilter = TrackableHitFlags.PlaneWithinPolygon |
                    TrackableHitFlags.FeaturePointWithSurfaceNormal;

                if (Frame.Raycast(touch.position.x, touch.position.y, raycastFilter, out hit))
                {
                    if ((hit.Trackable is DetectedPlane) &&
                        Vector3.Dot(FirstPersonCamera.transform.position - hit.Pose.position,
                            hit.Pose.rotation * Vector3.up) < 0)
                    {
                        Debug.Log("Hit at back of the current DetectedPlane");
                    }
                    else
                    {
                       arObject = (GameObject)Instantiate(AndroidPrefab, hit.Pose.position, hit.Pose.rotation;
                        arObject.transform.Rotate(0, k_ModelRotation, 0, Space.Self);
                        var anchor = hit.Trackable.CreateAnchor(hit.Pose);
                        arObject.transform.parent = anchor.transform;
                    }
                }
                }`

**Comment by pablisho** [comment]
@ArigarasuthanRepo try removing `TrackableHitFlags.FeaturePointWithSurfaceNormal` from your raycastFilter. Having that would mean that you not only want to place your objects on planes, but also on feature points, which could have a weird orientation like you are experiencing. Let me know if this helps.

**Comment by ArigarasuthanRepo** [comment]
Thanks @pablisho it was worked for me.

**Comment by pablisho** [comment]
Cool @ArigarasuthanRepo, closing this as your question was solved.
