### ISSUE TITLE
The ability to disable the ARCore SDK completely

### ISSUE THREAD

**Issue by patrickscheper** [google-ar/arcore-unity-sdk#274]
Currently it is impossible to build a simple scene, without any ARCore components, to PC Standalone if the ARCore SDK in inside of the asset folder. 

This means creating a multi-platform application with ARCore is theoretically impossible, which is quite sad. Am I wrong, or am I just overlooking something?

Thanks a lot, this is my first time writing an issue. 👍

**Comment by pablisho** [comment]
Hi, Thanks for the feature request.

**Comment by patrickscheper** [comment]
Thank you!

**Comment by patrickscheper** [comment]
Is there any possibility you could point me towards a temporarily solution? Because this kind of prohibits me to use ARCore...

**Comment by pablisho** [comment]
As a workaround, add an else [here](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Api/ApiConstants.cs#L52) and set all those strings to "NOT_AVAILABLE". Let me know if helps.

**Comment by patrickscheper** [comment]
Thank you so much, that worked perfectly! 👍

**Comment by sebrk** [comment]
#261

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and this issue has been fixed. Feel free to comment if you still experience the issue.
