### ISSUE TITLE
ARCore is causing Unity Cloud Build to fail.

### ISSUE THREAD

**Issue by patrickoshaughnessey** [google-ar/arcore-unity-sdk#275]
It appears that the 1.3 cocoapod downloaded during a unity cloud build is causing the compile to fail. I'm not sure why local builds to not similarly fail, but here is the log I am getting:

19321: ▸ Compiling AppDelegate.m
19322: ▸ ❌;  /BUILD_PATH/<redacted>/temp.XXXXXX20180626-7238-try0h3/Pods/ARCore/Examples/CloudAnchorExample/CloudAnchorExample/AppDelegate.m:19:9: 'FirebaseCore/FirebaseCore.h' file not found
19323: ▸ #import <FirebaseCore/FirebaseCore.h>
19324: ▸ Compiling ExampleViewController.m
19325: ▸ ❌;  /BUILD_PATH/<redacted>/temp.XXXXXX20180626-7238-try0h3/Pods/ARCore/Examples/CloudAnchorExample/CloudAnchorExample/ExampleViewController.m:22:9: 'FirebaseDatabase/FirebaseDatabase.h' file not found
19326: ▸ #import <FirebaseDatabase/FirebaseDatabase.h>

**Comment by patrickoshaughnessey** [comment]
It appears the problem is that ARCore SDK requires building using the generated xcworkspace instead of the standard Unity-iPhone.xcodeproj workflow. Hopefully, there is a workaround that can be found to this, as we rely on cloud build to get builds out to our clients and project stakeholders.

**Comment by bopangzz** [comment]
You should be able to config the iOS resolver to use Xcode project instead of workspace. Go to Assets->Play Service Resolver->iOS Resolver->Settings, and change Cocoapods integration to Xcode Project

**Comment by patrickoshaughnessey** [comment]
@bopangzz Thank you! Getting closer, but unfortunately, this results in a build error:

`<project dir>/Pods/ARCore/Examples/CloudAnchorExample/CloudAnchorExample/AppDelegate.m:19:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found`

Not sure why Cocoapods would resolve properly when using the workspace method, but not the Xcode project method?

**Comment by bopangzz** [comment]
Yeah, I can reproduce the issue here. We will create a internal bug to track this issue.

**Comment by patrickoshaughnessey** [comment]
@bopangzz thanks. Adding in @pablisho's suggested workaround fixed the build. We aren't actually using the CloudAnchors. This obviously won't work for anyone that is using CloudAnchors. Thanks, @pablisho.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.
