### ISSUE TITLE
Background video is noizy on Galaxy S9+ (SCV39)

### ISSUE THREAD

**Issue by kkc0923** [google-ar/arcore-unity-sdk#279]
Hi. I tested ARCore SDK (1.3.0) with Unity 2017.4.4. It works on Galaxy S8+, but same app doesn't work on Galaxy S9+. The background video is odd (no color video. it seems to be edge-detection image and very noising).

Here is device information from Unity:

OS : Android OS 8.0.0 / API-26
Device Model : samsung SCV39
GPU Name : Ardreno (TM) 630
GPU Vendor : Qualcomm

**Comment by kkc0923** [comment]
This only happens when using Multiple camera which has depth-only and no objects for rendering. I resolved this by disable non-rendering camera.

**Comment by fredsa** [comment]
Thanks for the update.

Also, if you are seeing edge detection, you be running the **ComputerVision** scene instead of the **HelloAR** scene.
