### ISSUE TITLE
Cloud anchor API logs are output when build while AR is not used

### ISSUE THREAD

**Issue by JeongSuhong** [google-ar/arcore-unity-sdk#280]
I am using Unity 2017.4.6f1 , ARCore 1.2

When Scene is built without ARCore, the corresponding logs are output.
This is the only thing " Scenes in Build " has.
Are there any internal requests for Cloud Anchor API when building?

--> Debug.Log
A cloud anchor API key has not been set.  Cloud anchors are disabled in this build.
UnityEngine.Debug:Log(Object)
GoogleARCoreInternal.CloudAnchorPreprocessBuild:_PreprocessAndroidBuild() (at Assets/ARPlatforms/GoogleARCore/SDK/Scripts/Editor/CloudAnchorPreprocessBuild.cs:142)
GoogleARCoreInternal.CloudAnchorPreprocessBuild:OnPreprocessBuild(BuildTarget, String) (at Assets/ARPlatforms/GoogleARCore/SDK/Scripts/Editor/CloudAnchorPreprocessBuild.cs:50)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by JeongSuhong** [comment]
How can I keep the message away?
There is no need to use Cloud Anchors in my project.

**Comment by pablisho** [comment]
Hi, by design we want to keep that message there. You can remove that log from CloudAnchorPreprocessBuild.cs:142 if you wish.
