### ISSUE TITLE
Support for Unity's AR Foundation

### ISSUE THREAD

**Issue by kennethlng** [google-ar/arcore-unity-sdk#285]
Hi Google ARCore team,

I was curious if you would be leveraging Unity's AR Foundation in the future.

Thanks!

**Comment by pablisho** [comment]
Hi, thanks for the feature request. We'll work to make our plugin compatible with Unity AR Foundation but I cannot share any timelines.

**Comment by sergiosolorzano** [comment]
+1 on this request please

**Comment by mimming** [comment]
We do indeed support Unity AR Foundation now.  We recommend you use it for new projects.  Here's a [comparison of features supported by the two different SDKs](https://developers.google.com/ar/develop/unity).
