### ISSUE TITLE
Script components stripped on ARKit Root in Cloud Anchors example w/ 1.3.0

### ISSUE THREAD

**Issue by augmenteer** [google-ar/arcore-unity-sdk#289]
Most of the script components in the ARKit Root hierarchy are _Missing ( mono script )_. The sample still builds for Android, but throws lots of warnings. I've confirmed this across multiple projects on two different Win computers running Unity 2018.1.5f1 and 2018.1.0f2 to verify that it's not an issue w/ my Unity installation.

**Comment by pablisho** [comment]
Hi, thanks for the report. I added an issue to our internal tracker.

**Comment by pablisho** [comment]
Hi, after investigating this we got to the conclusion that this is expected behaviour if you use CloudAnchors example only for Android and so not include ARKit plugin.
