### ISSUE TITLE
Unsupported devices do not work gracefully

### ISSUE THREAD

**Issue by patrickoshaughnessey** [google-ar/arcore-unity-sdk#29]
We are testing an ARCore app on unsupported devices, and we are finding that even without loading a scene with ARCore in it, the app causes the screen to be scrambled.

This is on a Samsung Galaxy S7, running Android 7.0, with a test screen with 2 buttons, and no ARCore classes in it, but with the ARCore SDK in the project:

![pasted image at 2017_10_05 11_13 am](https://user-images.githubusercontent.com/115180/31248247-b62bd302-a9d8-11e7-9a22-77ad77b53b4b.png)

**Comment by nathanmartz** [comment]
I'm sorry, but we can't provide support for unsupported devices. If you can reproduce this on an S8 or a Pixel, please reopen.

**Comment by jguomoto** [comment]
@patrickoshaughnessey Does this only happen in unsupported device? What's the OS you are using to run Unity?
