### ISSUE TITLE
Cast XPAnchor to Anchor

### ISSUE THREAD

**Issue by patrickscheper** [google-ar/arcore-unity-sdk#291]
I cannot use the XPAnchor (Which I get back from XPSession.ResolveCloudAnchor) as a normal Anchor. Is this by design, if so, why? 

I think it makes sense to cast a cross-platform anchor to a standard one.

**Comment by pablisho** [comment]
Hi, we expect XPAnchors to be used both in iOS and Android without needing to write platform specific code, while Anchors are Android only.
But I think it could be a valid use case if you want to use them in Android, so I take the feature request.

**Comment by small-potatoes** [comment]
Hi patrick, as Pablo mentioned, this is by design since XPAnchors can be used on both Android and iOS.  We have no plans allow casting XPAnchors to Anchors since that would conceal that the underlying mechanisms  of the casted anchor that may not be compatible with methods that accept Anchor.
