### ISSUE TITLE
Unable to get image marker orientation in Unreal with multiple markers

### ISSUE THREAD

**Issue by bss-sudhar** [google-ar/arcore-unity-sdk#292]
I am using ARCore's image recognition feature to scan multiple markers and spawn actors based on the marker scanned. It is mostly based on the AugmentedImages example project.

However, I found out that when I scan the 2nd marker and use the "Get Local to World Transform" from the  Google ARCoreAugmentedImage object, it gives the transforms of the 1st marker every time. "Get Center" function too seems to return the transforms oriented in the direction of the 1st marker.

For example,
The markers are defined to be like in the image-1. 
When scanning these markers I expect the objects spawned to face the direction of the marker, i.e., in -ve axis of x-axis (in red).

[image-1](https://drive.google.com/open?id=1dLm4CHBNdy5H6dZxJYpzoo95ypS27-tP)

However, when I scan the 2nd marker from another position, I expect the character to still face the direction of the marker as shown in image-2 (Since the get transform function should return the transform of the marker scanned?). However, every marker after the 1st marker spawns the character with the orientation of the 1st marker only. "Get Center" and "Get Local to World transform" too returns only the 1st marker's transforms. However, I am able to get the correct index of the image using the "Get  Image Index" function.

[image-2](https://drive.google.com/open?id=14CnWPi6HmsQvnaN3FYqa0kdVQKFmg1vn)

**Comment by bopangzz** [comment]
Can you file the issue on the arcore-unreal-sdk issue tracker?
