### ISSUE TITLE
Where to start??

### ISSUE THREAD

**Issue by GuptaTanay** [google-ar/arcore-unity-sdk#294]
Hey there, I am new to ARCore and I want to develop an indoor navigation using ARCore in Unity.
So please let me know where to start from??
I have downloaded the SDK and I don't know how to begin with the Indoor navigation stuff.
Thanks in advance!

**Comment by GuptaTanay** [comment]
Thanks! Will see that definitely.

**Comment by pablisho** [comment]
Hi, the best way to start is our [documentation](https://developers.google.com/ar/) and play with our [examples](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples). Feel free to reopen if you still have questions!
