### ISSUE TITLE
Android MAJOR issue with ARCore and Wikitude 7.2 integration. Unity 2018.1.1f1

### ISSUE THREAD

**Issue by leakymutant** [google-ar/arcore-unity-sdk#298]
So I'm trying to get AR Core working with Wikitude but AR Core requires that you check the AR Core Supported in XR setting which overrides the Wikitude settings and displays a white screen when built.

Is there anyway to not check that box so I can use Wikitude and AR Core together?

I just want to have two scenes one for AR Core and one for Wikitude. AR Kit works with Wikitude because there is nothing that is natively built inside of Unity to override the settings like AR Core does.

Adding a bounty to solve this problem because time is in short supply! 

Also I have seen this post [https://github.com/google-ar/arcore-unity-sdk/issues/274](url)
and wondering if the solution provide could disable AR Core within Unity completely so I can load both scenes.

Please help! Thank you AR Core team :)

**Comment by pablisho** [comment]
Hi @leakymutant, unfortunately we concluded that there's nothing in enabling ARCore that would prevent it working with other SDKs and so we won't be fixing this. I would suggest that you report this to Wikitude.
