### ISSUE TITLE
Camera not working for HelloAR

### ISSUE THREAD

**Issue by eugenepeh** [google-ar/arcore-unity-sdk#300]
Hello everyone,

I have followed the instructions on https://developers.google.com/ar/develop/unity/quickstart-android, however the camera doesn't seems to be active as shown in the picture below

![image](https://user-images.githubusercontent.com/19277206/42420904-921e33fa-82ff-11e8-9c7f-6fdc5988ee08.png)

The app did not prompt me to enable camera and I have tried giving it the permission too but doesn't work as well.

I am using Pixel 2, Android version 8.1.0.

Hope to receive some help on this. Thank you.

**Comment by markusfehr** [comment]
Maybe there is another scene selected in your **Build Settings** then you have open in the **hierarchy**. Then deselect the scene in the Build Settings (e.g. SampleScene) and build your app again.
![grafik](https://user-images.githubusercontent.com/22787040/42438229-bb60af3a-835f-11e8-906f-8e5ed401a361.png)

**Comment by eugenepeh** [comment]
Thank you, I've forgotten about that. It has solved my problem!
