### ISSUE TITLE
Support for Moto G5 Plus

### ISSUE THREAD

**Issue by Freshchris01** [google-ar/arcore-unity-sdk#303]
Hy, when I build and run the sample scene (HelloVR) I just get a black screen.
And when I try instant preview I get the message `Your device does not support AR` on my phone.
But generally AR kit supports Moto G as discussed [here](https://github.com/google-ar/arcore-android-sdk/issues/381). Any hints on how I could get this running?

I installed the ARCore app from the Github releases page.

**Comment by pablisho** [comment]
Hi, as stated in [Supported Devices](https://developers.google.com/ar/discover/supported-devices) the Moto G5 plus is not supported. Only G5S plus is supported.
