### ISSUE TITLE
Frame.CameraImage.Texture empty?

### ISSUE THREAD

**Issue by abrageor** [google-ar/arcore-unity-sdk#306]
Hey, I was trying to get the texture (the input of ARCore ), as I see in the documentation I should be able to access it through Texture backgroundTexture = Frame.CameraImage.Texture; however I am always getting the width and height of it to be 0 (I assume its empty?). The default prefab of ARCoreBackgroundRender works great as the material is being filled in by the texture. However when I try to get the info of the texture I am getting nothing. 

Any help on this one?

**Comment by FelixGirard** [comment]
You should take a look at the  [Computer vision](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples/ComputerVision ) example.
It shows the API provided to access the texture.
I encountered some issues with the API but I resolved them. You can look at that issue for more info :  https://github.com/google-ar/arcore-unity-sdk/issues/221
