### ISSUE TITLE
Has someone tried Arcore in Huawei Honor 8 with HiSilicon Kirin 950?

### ISSUE THREAD

**Issue by elblogbruno** [google-ar/arcore-unity-sdk#309]
Has someone tried Arcore in Huawei Honor 8 with HiSilicon Kirin 950?

**Comment by pablisho** [comment]
Hi, you can find the list of ARCore supported devices [here](https://developers.google.com/ar/discover/supported-devices). If it's not there, you won't be able to install ARCore.
