### ISSUE TITLE
Cloud Anchors iOS: Getting ErrorInternal message when testing on iPhoneX

### ISSUE THREAD

**Issue by bgdevpj** [google-ar/arcore-unity-sdk#311]
Good day,

I have been trying to find the cause of this issue. I made sure to follow the steps in https://developers.google.com/ar/develop/unity/quickstart-ios. I added the google cloud keys for iOS and Android etc. We tested and confirmed on android that Cloud Anchors work. Now we are trying to link iPhones and soon between iPhones and Android.

According to the documentation:

AR_CLOUD_ANCHOR_STATE_ERROR_INTERNAL | A hosting/resolving task for this anchor finished with an internal error. The app should not attempt to recover from this error.
-- | --

There is no trace to figure out why it behaves as is. I just want to know if I missed anything, or I was using incorrect keys. The description is too general to try and figure out the source of the issue.

using ARCore 1.3, ARKit 1.5, XCode Version 10.0 beta (10L176w).

edit: using Unity 2018.1.6f1 personal

**Comment by pablisho** [comment]
Hi, thanks for the report. What's the operation you are trying to do? Does this happen every time you try to host or resolve an Anchor? Or is it random?

**Comment by bgdevpj** [comment]
Hi, thanks for the reply. I am trying to host a cloud anchor. I know I followed every step in the guide, except firebase, which is not in the iOS Unity guide page. I do not know how to pinpoint the issue at all.

**Comment by sammcd** [comment]
Hello,

Thanks for your patience! You mention you are using the Xcode 10 beta. I assume you are using it because you are building to an iOS 12 device. We currently have a bug on iOS 12 that should be fixed in the next release. Until then it might be helpful to test on an iOS 11 device.

Thanks!

**Comment by sammcd** [comment]
We recently released 1.4.0 which includes this fix. Update your Podfile to 1.4.0 and run `pod install --repo-update`. This should solve your issue. If it doesn't, or if you run into anything else please let me know!
