### ISSUE TITLE
Cannot download Unity package v1.3.0 due to malware/ virus

### ISSUE THREAD

**Issue by Berenice2018** [google-ar/arcore-unity-sdk#313]
Hi,
I cannot download the Unity package v1.3.0 from this link: https://github.com/google-ar/arcore-unity-sdk/releases/download/v1.3.0/arcore-unity-sdk-v1.3.0.unitypackage

because McAffee tells me it is the virus Artemis. See the screenshot. 
Has anyone experienced the same? 

<img width="564" alt="virus" src="https://user-images.githubusercontent.com/35174799/42769143-ae956ecc-8921-11e8-9160-09b7fbf686d6.png">

**Comment by pablisho** [comment]
Hi, thanks for the report. This will be fixed in the next release.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and this issue has been fixed. Feel free to comment if you still experience this issue.
