### ISSUE TITLE
CloudAnchors -> how to Spawn?

### ISSUE THREAD

**Issue by ls29322** [google-ar/arcore-unity-sdk#314]
Hi, I'm trying to modificate the CloudAnchor example to let the players spawn more than one andy model.

After trying to create multiple cloud anchors, I think that I found the conceptual problem: I only need one cloud anchor for room, cause that "cloud anchor" is acting like a link to stablish a room.
**Is this concept true, or I'm missing something?**

So if I'm right, when bouth players are on the same room stablished by a single cloud anchor, if the host makes something like:
```
public void SpawnPrefab()
{
    // Raycast against the location the player touched to search for planes.
    if (Application.platform != RuntimePlatform.IPhonePlayer)
    {
        TrackableHit hit;
        if (Frame.Raycast(touch.position.x, touch.position.y,
                TrackableHitFlags.PlaneWithinPolygon, out hit))
        {
            m_LastPlacedAnchor = hit.Trackable.CreateAnchor(hit.Pose);
        }
    }

    if (m_LastPlacedAnchor != null)
    {
        // Instantiate Andy model at the hit pose.
        var andyObject = Instantiate(ARCoreAndyAndroidPrefab_Net, m_LastPlacedAnchor.transform.position,
            m_LastPlacedAnchor.transform.rotation);

        // Compensate for the hitPose rotation facing away from the raycast (i.e. camera).
        andyObject.transform.Rotate(0, k_ModelRotation, 0, Space.Self);

        // Make Andy model a child of the anchor.
        andyObject.transform.parent = m_LastPlacedAnchor.transform;

        NetworkServer.Spawn(andyObject); ---->>> HERE IS THE CHANGE! Instead of hosting anchor, spawn object!
    }    
}
```
You can notice that the only change is that now  **_HostLastPlacedAnchor();** is replaced by **NetworkServer.Spawn(andyObject);**

This approach makes no warnings or errors, but the new spawned object is only visible on the host. 
Why the client can't saw the new object?

Note: andyObject prefab has networkIdentity attached to him.

**Comment by pablisho** [comment]
Hi, I think you're approach is right in general, but in order to position the Andy in the right place in the other devices, you would need to share the cloudAnchorId. Then in the other devices, you'll need to use that CloudAnchorId to call `_ResolveAnchorFromId` and use that information to anchor your andy locally. Let me know if this helps.

**Comment by ls29322** [comment]
The actual problem is not the object position (at least, not at the moment).

The problem is that NetworkServer.Spawn() is only spawning on the Host side, not the host and the client sides.

Also I don't know why I have to get the Id anchor to position, if I the NetworkServer spawns, it spawns on the same position for bouth players, isn't it?

**Comment by ls29322** [comment]
That's what I'm asking, how can I adapt it? Which approach is that?

**Comment by pablisho** [comment]
I think what you are asking is not related to ARCore, I would suggest that you take a look at Unity Networking examples and tutorials https://unity3d.com/learn/tutorials/s/multiplayer-networking.
Once you have that set up you'll have to use CloudAnchors to position the Andy in the right place.

**Comment by ls29322** [comment]
I think that it's related with ARCore, more precisely, with CloudAnchors, what I'm asking is HOW the system of CloudAnchors works with Unet, how can I send commands and clientrpcs by your implementation. I know how to do it in other projects (I know how Unet works), but I don't get how your example works/set up your network stuff.

**Comment by peiyumo** [comment]
So, it is true that I can't create more than one cloud anchor in my app, right? The cloud anchor is only for the room. @pablisho

**Comment by raj244u** [comment]
I also trying to  touch the  andy prefab after instantiate.So it not be respond any touch through ray cast. 

Ray raycast = Camera.main.ScreenPointToRay(touch.position);
            RaycastHit raycastHit;
            if (Physics.Raycast(raycast, out raycastHit))
            {
                Debug.Log("Inside ray");
                if (raycastHit.collider.name == "f1")
                {
                    Debug.Log("f1. collider");

                }
                if (raycastHit.collider.tag == "f1")
                {
                    Debug.Log("tag. hit");

                }

**Comment by fredsa** [comment]
Conceptually it is expected that you use a single Cloud Anchor to establish a common frame of references across multiple users and devices. Then, use your preferred networking solution to synchronize the state of any virtual objects relative to then common frame of reference.

**Comment by fredsa** [comment]
The Cloud Anchors sample in the SDK has been updated to use Unity Networking. Feel free to use that sample scene as a reference when building your own projects.
