### ISSUE TITLE
AugmentedImages Rotation

### ISSUE THREAD

**Issue by MustaphaGH** [google-ar/arcore-unity-sdk#318]
Hello,

I'm making an AugmentedImage as a trigger to my AR Application. After detecting the image/trigger, I create an Anchor and attach to it different 3D objects as parent. These Objects will move according to it  in different Axis : X,Y,Z.

The problem is that ARCore often misses the correct rotation of the Image , this will make a catastrophic impact to the experience because the X & Z Axis could be inverted. So my 3DObjects will move up/down instead of right/left

**Comment by claywilkinson** [comment]
Do you mean the image is recognized, but it is pose of the image is rotated from what you expect?  Is it possible to share the image which causes the problem?

**Comment by MustaphaGH** [comment]
@claywilkinson  Exactly ! 
Here's some of the images : 
![image](https://user-images.githubusercontent.com/32525652/43015395-58059c00-8c58-11e8-9e0d-8b634ffa095b.jpg)
![image_zx1](https://user-images.githubusercontent.com/32525652/43015396-58227eba-8c58-11e8-95ac-36e27c213b9c.png)

The solution I found is to test the eulerangles of the recognized image and create an anchor only when the rotation fits my needs.

**Comment by small-potatoes** [comment]
Hi @MustaphaGH , please see [our documentation](https://developers.google.com/ar/reference/unity/class/GoogleARCore/AugmentedImage#centerpose) for the ceneter pose of the image.  TLDR; the y-axis points "out" of the image, the x-axis points toward the right edge of the image, and the z-axis points toward the top of the image.

I am closing for now, please reopen if you still observe behavior that does not match the documentation.
