### ISSUE TITLE
The raycast go through the Canvas.

### ISSUE THREAD

**Issue by robrtoprz** [google-ar/arcore-unity-sdk#322]
Hi everyone, I have a Canvas in my scene and If I touch any button, the raycast go through the button and instantiate an object, how can I prevent that? I'm using the HelloARController.
Thanks.

**Comment by robrtoprz** [comment]
I found a solution:
add this line: ` if (!EventSystem.current.IsPointerOverGameObject(touch.fingerId))` 
before the line: `if (Frame.Raycast(touch.position.x, touch.position.y, raycastFilter, out hit))` 
It worked for me.

**Comment by MustaphaGH** [comment]
Hello , the Frame.Raycast method is used only to detect the Trackables objects of ARCore , it's not used for normal 3D Objects and Canvas. 
Take a look at the classical method of unity : [Physics.Raycast](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html)

**Comment by pablisho** [comment]
Hi, thanks for the report and the workaround.

**Comment by chaosemer** [comment]
Glad you figured this out.

I'm closing this report as the issues you are describing are general Unity issues and not ARCore specific.
