### ISSUE TITLE
About supported devices

### ISSUE THREAD

**Issue by dvlee1024** [google-ar/arcore-unity-sdk#325]
We run our ARCore demo with Mi8 which is MIUI9 system, it could not support ARCore.

We run with Samsung S7 (G9300). It works, but why offical website says it is not support?

"Samsung devices with a model number ending in 0 or 8 are not supported, e.g. SM-G9600."

**Comment by pablisho** [comment]
Hi, Samsung devices ending with 0 or 8 might experience unexpected crashes, mainly if you are in China with no Play Store access, that's why we cannot fully support them. Does that answer your question?

**Comment by inio** [comment]
In general (see note below), ARCore is only fully supported only devices that shipped from the factory with the Google Play Store.  As a convenience to developers, version 1.3 has a workaround that allows ARCore to work some additional devices, such as the 0 and 8 model number Samsung phones.  **These devices are not fully supported**.

Note: For devices sold in China (without Google Play Store obviously), ARCore is only supported those for which we or the manufacturer have officially announced support for the Chinese variant of those devices.  At this time I believe this is limited to one model each from Xiaomi and Huawei.
