### ISSUE TITLE
Feature Request: Add extra debug features

### ISSUE THREAD

**Issue by SaikCaskey** [google-ar/arcore-unity-sdk#329]
I'm about to make something like a debug panel for walking around and testing my project. I know ARCore has everything that I need, but I don't know how to put it all together yet or what's the most useful thing to use.

## Usecase: 
* testing in lots of new places, the first thing to do is to walk the whole way around the place and try to gauge how ARCore took it in - it is difficult to know you got/ to get a consistent test (as you can imagine).

I don't expect you guys to just make AR easy, but it would be handy if you could add a few convenient debugging functions to decrease the time it takes me to understand what I'm looking at. 

Perhaps some debugging guidance or tips as well? You guys must have created lots of tools to bring this out.  It's possible that these resources exist, but I just don't know about them.

**Comment by pablisho** [comment]
Hi, thanks for the feature request. What are your looking for exactly? Example apps? Better documentation? What do you want us to showcase?

**Comment by SaikCaskey** [comment]
Yep sorry I was a bit vague - basically all of the above

A curated list of resources aimed at android developers who were not Games or open GL developers prior to working with ARCore. I kind of feel like "what now" after reading the developer resources pages. 

Basically I'm uncomfortable as I'm an Android developer who never did games development, so transforming objects on screen in an OpenGL style does just not come naturally to me, if you get me - I imagine a lot of other people will be in similar positions. 

Demoing Sceneform and some of the really really easy ARCore stuff added a lot of weight to this project, and now we want to do more complex things - but I have no idea where to start, even with simple-looking things like placing and rotating an object to an arbitrary position at some given distance from the device etc. 

Do I need to go do an Open GL or Unity course if I want to do this properly? If that's the case, it would be awesome if this was recommended somewhere, then I could point to it and say - look guys give me the time to do this properly.
