### ISSUE TITLE
Why i can not get texture by API "Frame.CameraImage.Texture"?

### ISSUE THREAD

**Issue by dvlee1024** [google-ar/arcore-unity-sdk#330]
I want to save texture from rear camera into sdcard. But when i get texture by the API "Frame.CameraImage.Texture" on my phone , i can only get a 0:0 size texture?

        Texture2D texture = (UnityEngine.Texture2D)Frame.CameraImage.Texture;
        if(texture == null) {
            SFLog.d("no texture");
            return;
        }
        SFLog.d("bg texture: "+texture.width + ":" + texture.height); // output 0:0
       
        string savePath = "/sdcard/DCIM/a.jpg";
        saveTextureToPath(texture,savePath);

**Comment by pablisho** [comment]
Hi, this is expected behaviour, that's an external texture and cannot be used for that. To do CPU image access you have to use [Frame.CameraImage. AcquireCameraImageBytes](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Frame.cs#L353) or use the TextureReaderApi. I would suggest that you take a look a the [ComputerVision](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples/ComputerVision) example. Let me know if this solves your question.

**Comment by dvlee1024** [comment]
@pablisho 

We can only get the separated data like just Y data or U data like the code below, which is not convenient for me.

```
using (CameraImageBytes image = Frame.CameraImage.AcquireCameraImageBytes())
        {
            if (!image.IsAvailable)
            {
                return;
            }

            int size = image.Width * image.Height;
            byte[] yBuff = new byte[size];
            System.Runtime.InteropServices.Marshal.Copy(image.Y, yBuff, 0, size);

            if(texture == null) {
                texture = new Texture2D(image.Width, image.Height, TextureFormat.R8, false,false);
            }
            texture.LoadRawTextureData(yBuff);
            texture.Apply();

            rawImage.texture = texture;
        }
```

I use screenshot insteaded.

```
Texture2D screenShot = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24,false);  
 screenShot.ReadPixels(new Rect(0,0,Screen.width,Screen.height), 0, 0);  
screenShot.Apply();
```

**Comment by dvlee1024** [comment]
@pablisho  hi, why I cannot get CameraImageBytes on Mi8 device? 
When I try to get CameraImageBytes on Mi8 device, console show the following log and failed to get the data.
But I can get it on other device. Something wrong with my code or my Mi8 device?

```
08-04 13:45:37.943  9876  9965 E native  : filter_update_base.cc:83 Mapped visual feature update failed when computing its residual and Jacobian.
08-04 13:45:37.979  9876  9895 E native  : status.cc:158 ArStatusErrorSpace::AR_ERROR_NOT_YET_AVAILABLE: 
08-04 13:45:37.979  9876  9895 W Unity   : Failed to acquire camera image with status ErrorNotYetAvailable
```

```
using (var image = Frame.CameraImage.AcquireCameraImageBytes())
                {
                    if (!image.IsAvailable)
                    {
                        print("IsAvailable");
                        return;
                    }
                    print("get it");
                }
```

**Comment by pablisho** [comment]
Hi, @dvlee1024 CameraImageBytes comes in YUV format and we don't provide conversions because there are many libraries already doing that.
Thanks for reporting the Mi8 issue. We'll be looking further into it and I'll let you know if we were able to reproduce it.

**Comment by dvlee1024** [comment]
@pablisho Any update of the Mi8 issue？

**Comment by chaosemer** [comment]
Sorry for the delayed reply. Most Xiaomi devices have a known issue where the CPU image access does not reliably work. If you want to support these devices, you will need to copy the GPU image to CPU using the [TextureReader](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/ComputerVision/Scripts/TextureReader.cs) code in the ComputerVision sample.
