### ISSUE TITLE
ARcore scene Unloading Issue

### ISSUE THREAD

**Issue by AbdullahBurhan** [google-ar/arcore-unity-sdk#331]
I have noticed that when I unload an ARcore scene (a scene that contains AR core camera) the unloading process takes too much time.
the Unloading and loading the next scene takes about 10sec even though the next scene is empty.
Any ideas...

**Comment by pablisho** [comment]
Hi, thanks for the report. What device and version of Unity and ARCore are you using? Are you doing SceneManager.LoadScene() to unload and load next scene? Thanks.

**Comment by AbdullahBurhan** [comment]
Hi, I am using Samsung s7 as an android device and using Unity 2018.1.0f2 and ARcore1.3,
I am doing a SceneManager.LoadScene()  to load and Unload.

**Comment by spaceapplesoft** [comment]
Hey,

I get the same issue with 1.4 and 1.3 version, and it went away when I rolled back to v1.0.

SceneManager.LoadScene() takes about 10-12 seconds.

To replicate: 
1. Start a new Project
2. Import ARCore Unity 1.4
3. Open HelloAr scene
4. Add a script which doesn't SceneManager.LoadScene() on some button click

Device: Samsung S8

I use scene reloading to restart the whole ARCore state (in case user wants to rescan the surfaces)

**Comment by chaosemer** [comment]
A fix for this rolled out in ARCore 1.5.
