### ISSUE TITLE
Select specific Plane 

### ISSUE THREAD

**Issue by AbdullahBurhan** [google-ar/arcore-unity-sdk#338]
how can I get the plane that I am hitting from the m_NewPlanes list

**Comment by pablisho** [comment]
Hi, if you perform a Raycast, the result [TrackableHit.Trackable](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/TrackableHit.cs#L64) will give you the trackable that you hit. Let me know if this answers your question.

**Comment by AbdullahBurhan** [comment]
Hi, thank you for responding, actually I have tried this but the m_newplanes list is from type DetectedPlane and the TrackableHit.Trackable is from type Trackable, so How can I reach DetectedPlane type from the Trackable one.

**Comment by pablisho** [comment]
Hi, DetectedPlane inherits from Trackable. If you used a filter with only planes when you did your hit, you can cast it safely. Let me know if that helps.

**Comment by AbdullahBurhan** [comment]
yes, that helped me thank you so much,
I am using Plane With Infinity as raycastFilter but that does not give me an infinite plane, it is extended  approximately two times as its being visualized, knowing that I am using ARCore 1.3 
is there a solution for this issue?

**Comment by small-potatoes** [comment]
Hi Abdullah, you are absolutely correct that the infinite plane raycast extends approximately two times the planes actual bounding box.  We are working to correct this and will update documentation to reflect the actual behavior in the meantime.  The only current workaround is to perform your own raycast mathematically.

**Comment by AbdullahBurhan** [comment]
yes, I made a custom solution to overcome this issue.
I generate a unity plane (big sized plane) in the position of the detected plane and start using the unity raycast instead of the ARcore one to perform my work

**Comment by chaosemer** [comment]
This is being tracked in #334

**Comment by NightFury13** [comment]
@pablisho @AbdullahBurhan I'm trying to do the same thing. Stuck at the type-cast issue mentioned by @AbdullahBurhan . My code looks like the one below,

```
protected override void OnEndManipulation(TapGesture gesture)
{
            if (gesture.WasCancelled)
            {
                return;
            }

            // If gesture is targeting an existing object we are done.
            if (gesture.TargetObject != null)
            {
                return;
            }

            // Raycast against the location the player touched to search for planes.
            TrackableHit hit;
            TrackableHitFlags raycastFilter = TrackableHitFlags.PlaneWithinInfinity | TrackableHitFlags.PlaneWithinPolygon;

            if (Frame.Raycast(gesture.StartPosition.x, gesture.StartPosition.y, raycastFilter, out hit))
            {
                Debug.Log("Entered into hit if condition");
                // Use hit pose and camera pose to check if hittest is from the
                // back of the plane, if it is, no need to create the anchor.
                if ((hit.Trackable is DetectedPlane) &&
                    Vector3.Dot(FirstPersonCamera.transform.position - hit.Pose.position,
                        hit.Pose.rotation * Vector3.up) < 0)
                {
                    //var andyObject = Instantiate(AndyPrefab, hit.Pose.position, hit.Pose.rotation);
                    Debug.Log("Hit at back of the current DetectedPlane");
                }
                else
                {
                    if (PlaneFixed is false)
                    {
                        foreach (GameObject plane in DetectedPlaneGenerator.instance.PLANES) //RK
                        {
                            if (hit.Trackable is plane)
                            {
                                Debug.Log("Plane Selected");
                                PlaneFixed = true;
                                FixPositionButton.gameObject.SetActive(true);
                            }
                            else
                            {
                                plane.SetActive(false);
                            }
                        }
                    }
                }
            }
}```

I think I am using the correct filters (PlaneWithinInfinity | PlaneWithinPolygon) but the compiler throws an error saying 'Assets/GoogleARCore/Examples/ObjectManipulation/Scripts/AndyPlacementManipulator.cs(225,50): error CS0029: Cannot implicitly convert type 'UnityEngine.GameObject' to 'GoogleARCore.Trackable'

Can you please help me find what am I doing incorrectly? TIA! 😄

**Comment by Nishanth14** [comment]
> yes, I made a custom solution to overcome this issue.
> I generate a unity plane (big sized plane) in the position of the detected plane and start using the unity raycast instead of the ARcore one to perform my work


@AbdullahBurhan Could you please provide your solution of creating a unity plane at a detected plane and using unity raycast. I am facing the same issue. Infinite plane raycast extends approximately two times the planes actual bounding box.
Thanks!
