### ISSUE TITLE
Commercial app with ARCore for Unity (license question)

### ISSUE THREAD

**Issue by KichangKim** [google-ar/arcore-unity-sdk#339]
Hi. I want to use ARCore for Unity with my commercial android application but its license is concern. It seems that ARCore itself is APACHE 2.0 license ( https://github.com/google-ar/arcore-unity-sdk/blob/master/LICENSE ) so it may be okay for this plugin. 

The problem is that ARCore for Unity requires ARCore by Google ( https://play.google.com/store/apps/details?id=com.google.ar.core ) and its license allows personal use only ( see "About Software in our Services" section in http://www.google.com/accounts/TOS )

So I'm very confusing and want to know whether ARCore for Unity can be used with commercial unity app.

**Comment by pablisho** [comment]
Hi, thanks for your question. I'll be escalating this within our team and be back with an answer.
