### ISSUE TITLE
Jitter when objects are moving rapidly or attached to the camera

### ISSUE THREAD

**Issue by shliama** [google-ar/arcore-unity-sdk#34]
Performance & feel of moving objects driven by either `RigidBody + force` or just updating `transform` are okay **until** you start moving the camera at the same time.

So, maybe I'm a total noob and can't configure Unity properly (might happen), or there is some issue with camera/world frame sync.

I've created [a fork](https://github.com/shliama/arcore-unity-sdk) and modified it a little to showcase the issue.
Changes are:
- modified `Andy` prefab (added  Plane to be camera RayCast target & added nested Andy to follow the pointer).
- added `ExampleScript` that applies force on RigidBody so it follows a pointer.

[Google Photos link to video with poor jitter Andy](https://photos.app.goo.gl/6GFT0f1ucWBL0IJy1)

P.S. While I was searching for an answer on forums I stumbled upon this [bug-report](https://forum.unity.com/threads/jitter-when-objects-are-moving-rapidly-or-attached-to-the-camera.435048/) that is so alike but with Daydream and a year ago.

Any help would be appreciated.

**Comment by chaosemer** [comment]
What you are seeing is that the object is updating at physics framerate (likely 50 fps) and the camera is updating at 30 fps. So roughly every other frame the object moves but the camera does not, causing visual stutters. This is a limitation of moving objects.

We'll be adding an option in v1 to lock Unity's update rate to the camera rate which should address this issue.

**Comment by shliama** [comment]
@chaosemer thank you for the explanation. So is there any chance we can get 60 fps camera on Pixel/S8?

P.S. Looking forward to v1 :octocat:

**Comment by chaosemer** [comment]
Closing this as the Match Camera Framerate option is in DP2. Please reopen if you are still having issues.

**Comment by shliama** [comment]
@chaosemer oh man, works like a charm! Keep on rollin' 🤘

**Comment by ChristophGeske** [comment]
I would like to set the camera frame rate to 60fps instead of setting the overall framerate down. Am I right in assuming that this is not possible because the ARCore team needs a fixed camera frame rate (30fps) for making the tracking possible. 
I would like to use that for improving the quality of my inside out tracking app which requires 60fps.

**Comment by chaosemer** [comment]
Changing the passthrough camera framerate to 60 is not currently supported with ARCore.

For some background, not all phone hardware supports 60 fps cameras at the full sensor coverage. Even if/when such an option does become available you will need to have fallback support in case the phone you are running on does not support 60 fps camera.
