### ISSUE TITLE
Warning: Enum member Unknown has been deprecated

### ISSUE THREAD

**Issue by SabreRunner** [google-ar/arcore-unity-sdk#343]
Using Unity 2018.2, we get this warning:

`Assets/GoogleARCore/Examples/ComputerVision/Scripts/ComputerVisionController.cs(87,75): warning CS0618: UnityEngine.ScreenOrientation.Unknown' is obsolete: Enum member Unknown has been deprecated.`

I think it should be set to AutoRotation.

**Comment by pablisho** [comment]
Hi, thanks for the report. I added to our internal tracker to fix it for next releases.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.
