### ISSUE TITLE
Warning: UnityEditor.Build.IPreprocessBuild is obsolete.

### ISSUE THREAD

**Issue by SabreRunner** [google-ar/arcore-unity-sdk#344]
Using Unity 2018.2, I get the following warning:

`Assets/GoogleARCore/SDK/Scripts/Editor/RequiredOptionalPreprocessBuild.cs(29,20): warning CS0618: 'UnityEditor.Build.IPreprocessBuild' is obsolete: 'Use IPreprocessBuildWithReport instead'`

And this repeats five times in five files.

**Comment by pablisho** [comment]
Hi, thanks for the report. I added it to our internal tracker to fix it for next releases.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.

**Comment by VishalParab902920** [comment]
Iam using Admob plugin version 3.18 and play services plugin version 0.9.64 which are latest at the time I post this comment. If I use them individually in my project they work but i use both of them i get this issue
