### ISSUE TITLE
Can I control the maximum distance of markers recognized by AugmentedImage?

### ISSUE THREAD

**Issue by SatoSeiichi** [google-ar/arcore-unity-sdk#346]
I am looking at the sample scene AugmentedImage,
Can you control the maximum distance of recognizable markers?
The maximum recognizable distance to the sample marker printed on A4 was about 1 m. What should I do if I want to recognize it over 1 meter?
UnityVer: 2017.4.8 f 1
ArCore: v1.4.0
Android terminal: Galaxy S8

**Comment by pablisho** [comment]
Hi, currently tracking distance for AugmentedImages is not configurable.

**Comment by SatoSeiichi** [comment]
Thank you for reply
Will it be possible to set it in future updates?

**Comment by pablisho** [comment]
Hi, I added it to the feature request list, but unfortunately I cannot share any timelines about when this is going to be added.

**Comment by chaosemer** [comment]
Combing with #283.
