### ISSUE TITLE
Cloud anchor cannot be resolved on a different iOS device

### ISSUE THREAD

**Issue by GothParrot** [google-ar/arcore-unity-sdk#349]
I built the sample CloudAnchor scene in my two iOS 11.4.1 devices, an iPhone and an iPad, on the same wifi. I can successfully create the anchors, and resolve on the same device. But when I try to create the anchor on one device and resolve on the other, I receive "Anchor resolve failed due to invalid room code, ip address or network error."

**Comment by pablisho** [comment]
Hi, thanks for the report. Are both devices in the same local network? Does it happen consistently or randomly?

**Comment by GothParrot** [comment]
They're in the same local network. It happens consistently - I haven't been able to resolve from one device to the other yet.

**Comment by GothParrot** [comment]
Turns out there was a problem with my local network. I finally set up a hot spot from another phone to network the two phones and solved the issue.

**Comment by KepAmun** [comment]
I have the same issue, found this thread and was able to get cloud anchors working with a hotspot like GothParrot, however, I would much prefer them to work while connected to my office Wifi. Is there something we can change, perhaps in our network configuration, that would allow cloud anchors to successfully resolve?
