### ISSUE TITLE
camera preview data can't update

### ISSUE THREAD

**Issue by feixiaku** [google-ar/arcore-unity-sdk#35]
@chaosemer your log shows didn't find the video. I think maybe you didn't put "urls_arcore.txt" or "model-2.nut" files into /sdcard/ directory. you can use these commands( "adb push urls_arcore.txt /sdcard/", "adb push model-2.nut /sdcard/" ), then open the app. and I catch the full logcat:
[arcore_logcat.txt](https://github.com/google-ar/arcore-unity-sdk/files/1389912/arcore_logcat.txt)

please ensure this thing, thanks.

**Comment by chaosemer** [comment]
Could you please continue to comment on #24? I'm going to close this and move your comment there.

**Comment by feixiaku** [comment]
ok, thx
