### ISSUE TITLE
Change Plane Style

### ISSUE THREAD

**Issue by ragavendranbala** [google-ar/arcore-unity-sdk#359]
Hi I need to change the detected plane visualizer style on ARcore with like the one in ARKit or any other on my own style. Is there is any possible way to do that? If yes please tell the way or code to change its style.
Thanks in advance

**Comment by dvlee1024** [comment]
You can get detectedPlane's center pose, extendX and extendY data to draw a plane you want.

**Comment by pablisho** [comment]
Hi, HellAR example uses  DetectedPlaneVisualizer [prefab](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/Common/Prefabs/DetectedPlaneVisualizer.prefab) and [script](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/Common/Scripts/DetectedPlaneVisualizer.cs) to render ARCore planes. You'll have to change/adapt those if you want you custom rendering. Let me know if this helps.
