### ISSUE TITLE
How to access the video feed texture?

### ISSUE THREAD

**Issue by yaustar** [google-ar/arcore-unity-sdk#36]
Edit: Oops, didn't actually add a description!

We are trying to access the video feed that arcore renders to the background. I've managed to find the material via UnityTango.Device.backgroundRenderer and when I assign it to a UI.RawImage, it shows the live feed. 

However, I would like to make a copy of the texture and accessing UnityTango.Device.backgroundRenderer.backgroundMaterial.GetTexture("_MainTex") returns null.

Thanks in advance.

**Comment by chaosemer** [comment]
The underlying texture is a YUV OES external texture and can not be referenced normally in the developer preview.

To get the texture as a normal texture, you should set your camera to render to a texture, and then use that texture as normal.

**Comment by andonegr** [comment]
Hey yaustar,

I know it's been sometime but did you manage to solve this?
 
I am having a similar problem
I am using the ARCore Camera to move my virtual camera (i need the positional tracking but i don't want the background render)
I want to have something sort of a webcamtexture though somewhere inside my virtual scene.
I cannot get it to render on another texture! 

Regards,

**Comment by yaustar** [comment]
@andonegr ARCore now provides access to the video feed via the API. (See computer vision example in the SDK).

Up to that point, we used a second camera with the AR Core Background Renderer script and a target texture to a render texture.

This allowed us to use the feed how we liked (computer vision, render it in a scene, part of a debug UI, etc)
