### ISSUE TITLE
Set AugmentedImages DB at Runtime

### ISSUE THREAD

**Issue by georgegmpixels** [google-ar/arcore-unity-sdk#360]
Hello,

I know that adding/removing markers at runtime is not available at the moment (and I want to see it implemented also). As a workaround I am trying to download the files from the server and load them like 

`LifecycleManager.Instance.NativeSession.AugmentedImageDatabaseApi.CreateFromBytes(m_RawData);`

It says success and no errors are thrown, but it seems like this is not enough to register the DB with the SessionConfig. Can you point me to the right direction?

Thank you,
Georgi

**Comment by pablisho** [comment]
Hi, currently there's no way to neither add new images to a existing database nor to create a new database at runtime, as the scripts that creates it runs in the editor. For Augmented Images at runtime support, ser #256
