### ISSUE TITLE
Converting IntPtr (CPU buffer representing Y channel) to AndroidJavaObject without copy

### ISSUE THREAD

**Issue by bilsou** [google-ar/arcore-unity-sdk#364]
When calling `AcquireCameraImageBytes` to retrieve an `CameraImageBytes` instance and the underlying `Y` IntPtr buffer, I need to pass that IntPtr to my own AAR library which takes a `ByteBuffer` as argument. I could not find a way of converting the `IntPtr` to an `AndroidJavaObject` reference which would allow me to pass it to my method.

```csharp
using (GoogleARCore.CameraImageBytes image = GoogleARCore.Frame.CameraImage.AcquireCameraImageBytes())
{
    if (!image.IsAvailable)
    {
        return;
    }

    int width = image.Width;
    int height = image.Height;
    IntPtr yPixelBuffer = image.Y;

    using (AndroidJavaClass utilsClass = new AndroidJavaClass("com.mypackage.MyClassUtils"))
    {
        utilsClass.CallStatic("setCurrentBuffer", yPixelBuffer, width, height); // <-- Need to pass a AndroidJavaObject here but no way to just pass the ByteBuffer
    }
}
```
the Java method implementation:
```java
public class MyClassUtils {
    public static final void setCurrentBuffer(
                                              ByteBuffer buffer,
                                              int width,
                                              int height) {
}
```

Is there any way to convert the `IntPtr` to its underlying `ByteBuffer` reference ?

**Comment by pablisho** [comment]
Hi, the IntPtr is not a ByteBuffer object, but you can see it as a raw memory pointer (unmanaged). I cannot help with how to convert a raw ptr to a ByteBuffer in Java.

**Comment by dvlee1024** [comment]
you can get byte array in c# and pass to java 

``` Marshal.Copy(yPixelBuffer, byteArray, 0, bufferSize); ```

**Comment by bilsou** [comment]
`the IntPtr is not a ByteBuffer object` @pablisho thanks a lot for this, I really thought it was pointing to the address of a `ByteBuffer` object, my bad. I reckon I have no choice but to directly pass the `IntPtr` to my `.so` C++ library and use the pointer to `unsigned char*` there. Thanks again.
