### ISSUE TITLE
example for replacing models

### ISSUE THREAD

**Issue by gdbassett** [google-ar/arcore-unity-sdk#366]
I have very little unity experience so am having trouble understanding how to replace, position, size, and orient the models (frame corners) in the augmented image example.  In addition to the tutorial on adding an image, could you point me to or add a tutorial on how to add a model?

Thank you,
Gabe

**Comment by pablisho** [comment]
Hi @gdbassett, AugmentedImages example [uses AugmentedImageVisualizer](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/AugmentedImage/Scripts/AugmentedImageVisualizer.cs) to visualize the aumented image. You can use your own visualizer/model to visualize it in the way you want. [HelloAR example](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/HelloAR/Scripts/HelloARController.cs#L136) also places a model on top of planes and feature points.
Let me know if this helps. I also would suggest you do some of the initial Unity tutorials as this is a general Unity question and not specific to ARCore. They are really helpful.

**Comment by gdangalov** [comment]
Hi @gdbassett, there is a ready to use example that demonstrates how to load 3D models from internet and load them dynamically in the mobile app. You can find more information here - http://arcapt.com/demos
