### ISSUE TITLE
Editor crash when press PLAY

### ISSUE THREAD

**Issue by marad747** [google-ar/arcore-unity-sdk#367]
I connect galaxy s7. Install Instant Preview and press play and editor are crushed
![image](https://user-images.githubusercontent.com/20600166/44652535-c9f21500-a9f4-11e8-8918-609b6c1ceb79.png)

**Comment by pablisho** [comment]
Hi @marad747, thanks for the report. What version of Unity and ARCore are you using?

**Comment by small-potatoes** [comment]
This may be related to a problem fixed in the next release due to spaces and non-ascii characters in the path causing issues.  Please reopen if you still have problems or additional information.
