### ISSUE TITLE
Camera not rendering when using Unity as a library in android app

### ISSUE THREAD

**Issue by tarakinsuide** [google-ar/arcore-unity-sdk#369]
Hi,

I'm using Unity app Mapbox AR which uses Google Arcore for my unity app. The app works fine, but I need to integrate it with my existing android app.
But I keep getting error and the logcat reads like this in the android studio:
```
(Filename: C Line: 0)
08-23 14:42:48.575 15689-15721/? E/Unity: DllNotFoundException: arcore_unity_api
        at (wrapper managed-to-native) GoogleARCoreInternal.LifecycleManager/ExternApi:ArCoreUnity_setArPrestoInitialized (GoogleARCoreInternal.LifecycleManager/EarlyUpdateCallback)
      at GoogleARCoreInternal.LifecycleManager._Initialize () [0x00019] in C:\Users\Tarak\Documents\MapboxtoAndroid\Assets\GoogleARCore\SDK\Scripts\Managers\LifecycleManager.cs:223 
      at GoogleARCoreInternal.LifecycleManager..cctor () [0x00010] in C:\Users\Tarak\Documents\MapboxtoAndroid\Assets\GoogleARCore\SDK\Scripts\Managers\LifecycleManager.cs:58 
    Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GoogleARCoreInternal.LifecycleManager
      at GoogleARCore.ARCoreSession.Awake () [0x00001] in C:\Users\Tarak\Documents\MapboxtoAndroid\Assets\GoogleARCore\SDK\Scripts\ARCoreSession.cs:42 

    (Filename: C Line: 0)
08-23 14:42:48.586 15689-15721/? I/Unity: has extra
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    FromAndroid:Update() (at C:\Users\Tarak\Documents\MapboxtoAndroid\Assets\FromAndroid.cs:27)

```

This is the detail of my issue I had raised with Mapbox AR:

https://github.com/mapbox/mapbox-unity-sdk/issues/977

**Comment by tarakinsuide** [comment]
Same thing happened when I tried Google ARCore example HelloAR Unity in the native android app as android.
The screen doesn't start camera even after giving camera permissions manually.

**Comment by SafwanCheng** [comment]
What mobile phone?

**Comment by tarakinsuide** [comment]
Google pixel XL

**Comment by pablisho** [comment]
Hi @tarakinsuide, which version of Unity and ARCore are you using? Does your app work when you build it in Unity but fails when integrating it in your Android app?

**Comment by small-potatoes** [comment]
Hi, it looks like you are missing some native libraries.  Please check that all the aar and .so files from an APK build (most located [here](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/SDK/Plugins)) are making it into your android project.   Closing for now, please reopen if you need additional assistance.

**Comment by MuhammadAasharib** [comment]
@small-potatoes @tarakinsuide  @pablisho @SafwanCheng 

Hi, I am facing the same issue i have checked all .aar files but the same results. Can you please guide me?

**Comment by stubuchbinder79** [comment]
I'm having the same issue

**Comment by SafwanCheng** [comment]
Have you solved it?

stubuchbinder79 <notifications@github.com> 于 2019年1月3日周四 02:19写道：

**Comment by stubuchbinder79** [comment]
Yes. It's a permission slip issue. If you go to the app settings and enable camera permissions it will work.

**Comment by syamsol** [comment]
im facing the same problem but thats on my own project
