### ISSUE TITLE
how to handle Anchors that are lost when tracking lost

### ISSUE THREAD

**Issue by EliTayrien** [google-ar/arcore-unity-sdk#37]
Hello,

What is the intended way to handle Anchors being lost when tracking is lost? 

I'm seeing a bug where my game objects can disappear when the device has tracking issues. Each of the game objects is attached to an anchor. From doing a bit of digging through the ARCore SDK source, it seems like the following is happening:

1. ARCore establishes non-localized Tracking
2. I create an anchor and attach game objects to it
3. anchors are left in the non-localized collection
4. tracking is lost. All non localized anchors are deactivated and then forgotten.

I did a bit of printf-debugging, and I've confirmed that when I observe this problem, in Anchor._UpdateTrackingState, the anchor has been Deactivated and my game objects are still attached to the anchor.

I'm planning on working around this issue by modifying _UpdateTrackingState to detect when this has happened, and notifying my game objects that they need to remove themselves from their anchor, wait for tracking to be re-established, then recreate Anchors. However, I can't do this without modifying code that's "internal" to the ARCore SDK. Is there a better way to handle this scenario?

Thanks!

**Comment by chaosemer** [comment]
Your observation is correct. This is a limitation of the developer preview. If you lose tracking while anchors aren't tied to a map ("localized"), then there's no way to know where they are when you regain tracking.

The best you can do is surface this state up to the user. We surface it as the "StoppedTracking" state. In that case, you'll need to tell the user to re-place their anchors.

I hope this makes sense. I'm going to close this issue as it is a limitation of the system.

**Comment by areavisuale** [comment]
Hei cahosemer could you tell me how an anchor can be "localized"? I cannot find any reference to localized and non-localized anchors.
I would like to create an anchor on my detected plane only if the tracking is stable so I can see the objects I instantiated also after I lose tracking.
