### ISSUE TITLE
The camera does not detect the plane, using OnePlus6

### ISSUE THREAD

**Issue by Rorschach1219** [google-ar/arcore-unity-sdk#371]
The arcore has been updated at the Google store. When I run the "HelloAR" in the official sample scenario, there will be no feature points on the ground. It looks like a normal camera.This phenomenon has just emerged recently. It is normal for me to use ARCore and ARFoundation a few weeks ago. Please help me!

**Comment by pablisho** [comment]
Hi @SafwanCheng, thanks for the report. I reported this internally and will be back with a response.
