### ISSUE TITLE
Vertical plane object always is rotated in y-axis

### ISSUE THREAD

**Issue by dawidthedust** [google-ar/arcore-unity-sdk#378]
Is this possible to set object on vertical plane with rotation pararell to horizontal plane? For example image frame or tv screen - I would like to place it wall-sticky but I get random rotation in y-axis.

**Comment by pablisho** [comment]
Hi, the plane orientation itself will depend of the shape of the detected plane, but if you want to place an object on it, you can adjust its orientation to always be aligned with Y axis. 
For example in HelloAR, when we place an Andy model, it's always looking at the camera:
https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/HelloAR/Scripts/HelloARController.cs#L136. It's not the same transformation, but I think you can do something similar to have your object aligned with Y. Let me know if this helps.

**Comment by dawidthedust** [comment]
I have used that trick before, but it made it depending on phone position and rotation. It would be great if user had been using stationary tripod, but it is not a solution.

**Comment by fredsa** [comment]
You can use `Transform.LookAt()`:
  https://docs.unity3d.com/ScriptReference/Transform.LookAt.html

Make sure to use the two argument version of this method.
