### ISSUE TITLE
Unity ARCore cloud anchor gets misplaced on the second phone

### ISSUE THREAD

**Issue by aefox** [google-ar/arcore-unity-sdk#379]
Hello everyone,

I am hoping to get some guidance on a problem I am encountering and that I am trying to figure out.

Current setup: 2 x Google Pixel 2 XL phones

Scenario: I have both phone in my hands, one next to the other. I'm starting the cloud anchors example on both phones. On one phone I am doing the hosting of a cloud anchor (I also have a small red dot assigned as a child of the anchor for visualization). Once the anchor is saved to the cloud I am resolving the same anchor on the second phone.

Outcome: the outcome of this exercise is that on the second phone where I do the resolving the anchor is rendered in a different position than the position where the anchor was registered

Extra note: I have picked a place on the floor which has extra details (like various boxes) so the surrounding space has extra details.

**Comment by aefox** [comment]
It seems that the positioning of the second cloud anchor on the second phone is a lot more precise in the android example. Anyone any idea why could this be or how could I fix this in unity-arcore?

**Comment by small-potatoes** [comment]
Hi @aefox , how long and how well ARCore tracking runs prior to host/resolve effects the accuracy of the operation.  Generally, having 5+ seconds of moderate translational movement of the device around the area before making a call will yield more accurate results.  I am closing the issue, please reopen if you encounter additional problems.
