### ISSUE TITLE
Pixel 2 XL: last app/homescreen showing on some surfaces in ARCore 

### ISSUE THREAD

**Issue by eisenbruch** [google-ar/arcore-unity-sdk#38]
See app icons where a shadow would be. Shadow would be provided by ARCoreUtils. I am not sure but it is possible this started after updating to Unity 2017.3.0b5 Personal.

![screenshot_20171019-191547](https://user-images.githubusercontent.com/6180294/31799574-d2f180fa-b508-11e7-98a9-e7f63e6168b8.png)

**Comment by eisenbruch** [comment]
I noticed this on my Pixel XL as well. It only happens sometimes.

**Comment by chaosemer** [comment]
Is this still happening on recent versions of 2017.3? I do not recall seeing this issue recently, though I'm spending most of my time on the next release. :)

**Comment by eisenbruch** [comment]
I don't believe this has ben an issue recently.
