### ISSUE TITLE
CPU image access: DllNotFoundException: arcore_camera_utility

### ISSUE THREAD

**Issue by sonary01** [google-ar/arcore-unity-sdk#381]
I am trying to access color image frames using TextureReaderApi . When I try to use TextureReaderApi to access the CPU images, I am getting "DllNotFoundException: arcore_camera_utility'  error given below. I added a new script in the Computervision example to do it.  I didn't change any plugins . Someone reported this issue before (#219), but that didn't help me to solve this error.  I tried all the methods mentioned in #72, #221, still I am not able to get the color image frames. Any help is much appreciated.

Error message:

> DllNotFoundException: arcore_camera_utility
> GoogleARCore.Examples.ComputerVision.TextureReaderApi.Create (ImageFormatType format, Int32 width, Int32 height, Boolean keepAspectRatio) (at Assets/GoogleARCore/Examples/ComputerVision/Scripts/TextureReaderApi.cs:65)
> GoogleARCore.Examples.ComputerVision.TextureReader.Update () (at Assets/GoogleARCore/Examples/ComputerVision/Scripts/TextureReader.cs:137)

Script:

```
using System;
using System.IO;
using System.Collections.Generic;
using GoogleARCore;
using UnityEngine;
using UnityEngine.UI;
using GoogleARCore.Examples.ComputerVision;
using GoogleARCore.Examples.Common;

public class ColorFrames : MonoBehaviour {

	private TextureReader TextureReaderComponent;
	private Texture2D m_TextureToRender =null;
	private byte[] m_EdgeImage =null;
	int buffersize=0;
	public Image EdgeDetectionBackgroundImage;

	public void Start()
	{
		TextureReaderComponent = gameObject.GetComponent<TextureReader> ();
		TextureReaderComponent.OnImageAvailableCallback += OnImageAvailable;
	}
	
	// Update is called once per frame
	void Update () {

		if (!Session.Status.IsValid())
		{
			return;
		}

		using (var image = Frame.CameraImage.AcquireCameraImageBytes())
		{
			if (!image.IsAvailable)
			{
				return;
			}
				buffersize = image.Width * image.Height;
				TextureReaderComponent.enabled = true;
			    OnImageAvailable(TextureReaderApi.ImageFormatType.ImageFormatColor,image.Height, image.Height, image.Y, buffersize);
		}

	}

	private void OnImageAvailable(TextureReaderApi.ImageFormatType format,int width, int height, IntPtr pixelBuffer, int bufferSize)
	{
		if (m_TextureToRender == null || m_EdgeImage == null || m_TextureToRender.width != width || m_TextureToRender.height != height)
		{
			
			m_TextureToRender = new Texture2D (width, height, TextureFormat.RGBA32, false, false);
			m_EdgeImage = new byte[width * height * 4];
  		 }

		System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, m_EdgeImage, 0, bufferSize*4);

		// Update the rendering texture with the sampled image.
		m_TextureToRender.LoadRawTextureData(m_EdgeImage);
		m_TextureToRender.Apply();
		EdgeDetectionBackgroundImage.material.SetTexture("_ImageTex", m_TextureToRender);
		var encodedJpg = m_TextureToRender.EncodeToJPG();
		var path = Application.persistentDataPath;
		File.WriteAllBytes(path + "/testImage.jpg", encodedJpg);

	}
void OnDisable()
	{
		TextureReaderComponent.enabled = false;
		TextureReaderComponent.OnImageAvailableCallback -= OnImageAvailable;
	}
}

```

**Comment by iBicha** [comment]
With the `Frame.CameraImage.AcquireCameraImageBytes` you no longer need to use the `TextureReaderApi` which is used as an example (and should probably be deprecated)

`Frame.CameraImage.AcquireCameraImageBytes` returns a data structure holding the pixel buffer in a YUV format (pointers to Y, U and V), and it's up to you to convert it to RGB, put it in a texture, etc

**Comment by sonary01** [comment]
Thanks for the response. I even tried with Arcore older versions (1.2 and 1.3) and getting the same error.  I'm not sure TextureReaderApi is a depreciated method. It is recommended to use in some recent post (#330) as well. 
I tried to convert YUV to RGB conversion , but not getting proper color images.

**Comment by sonary01** [comment]
I already tried this conversion. The converted RGBA image is like. 
![yuv_rgba](https://user-images.githubusercontent.com/25668351/45269576-8a004880-b45e-11e8-8903-f7c3b5b51d63.jpg)

**Comment by iBicha** [comment]
Can you share the code to produce this?

**Comment by sonary01** [comment]
There was a mistake in my YUVto RGB a conversion. Now getting good results.

![image](https://user-images.githubusercontent.com/25668351/45319669-714f6b80-b50e-11e8-951d-ad5ade947a00.png)

Modified _OnImageAvailable () method:
```

private void _OnImageAvailable(int width, int height, IntPtr pixelBuffer, int bufferSize)
		{

			m_TextureRender = new Texture2D (width, height, TextureFormat.RGBA32, false, false);
			byte[] bufferYUV = new byte[width * height*3/2];
			bufferSize = width * height*3/2;
			System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, bufferYUV, 0, bufferSize);
			Color color = new Color ();
			for (int y = 0; y < height; y++) {
				for (int x = 0; x < width; x++) {

					float Yvalue = bufferYUV[y * width + x];
					float Uvalue = bufferYUV[(y / 2) * (width/2) + x/2 + (width * height)];
					float Vvalue = bufferYUV[(y / 2) * (width/ 2) + x / 2 + (width* height)+ (width * height)/4];
					color.r= Yvalue + (float)(1.37705 * (Vvalue-128.0f));
					color.g= Yvalue - (float)(0.698001 * (Vvalue-128.0f)) - (float)(0.337633 * (Uvalue-128.0f));
					color.b= Yvalue + (float)(1.732446 * (Uvalue-128.0f));

					color.r /= 255.0f;
					color.g /= 255.0f;
					color.b /= 255.0f;

					if (color.r < 0.0f)
						color.r = 0.0f;
					if (color.g < 0.0f)
						color.g = 0.0f;
					if (color.b < 0.0f)
						color.b = 0.0f;

					if (color.r > 1.0f)
						color.r = 1.0f;
					if (color.g > 1.0f)
						color.g = 1.0f;
					if (color.b > 1.0f)
						color.b = 1.0f;

					color.a = 1.0f;
					m_TextureRender.SetPixel (width - 1 - x, y, color);      
				}
			}

					
			m_TextureRender.Apply();
			var encodedpng = m_TextureRender.EncodeToPNG ();
			var path = Application.persistentDataPath;
			File.WriteAllBytes (path + "/YUV2RGB.png", encodedpng);
          }

```

**Comment by jarileon** [comment]
In case someone needs only the grayscale values (like I did for QR code detection using Zxing), you only need to read the first n values (where n = width*height) from the pixelBuffer: 

`int bufferSize = width * height;
byte[] pixels = new byte[bufferSize];            
System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, pixels, 0, bufferSize);
`
Then you can pass the pixels byte array to the barcodeReader.Decode (you must also pass RGBLuminanceSource.BitmapFormat.Gray8)

**Comment by dragonkhoi** [comment]
@sonary01  can you link full code? I am using ARCORE 1.9 for Unity and I'm getting color in the Instant Preview but not when I build to device. Also, Image is flipped and rotated.

**Comment by dragonkhoi** [comment]
@sonary01  I am trying to render the color image onto a UI Image in the scene.`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleARCore;
using GoogleARCore.Examples.ComputerVision;
using System;
using UnityEngine.UI;

public class SUVSTARAcquireBytes : MonoBehaviour
{
    public RenderTexture rt;
    public Image imageCanvas;
    private byte[] m_EdgeDetectionResultImage = null;
    private Texture2D m_EdgeDetectionBackgroundTexture = null;
    private DisplayUvCoords m_CameraImageToDisplayUvTransformation;


    // Start is called before the first frame update
    void Start()
    {
      //  textureReader.OnImageAvailableCallback += _OnImageAvailable;

    }

    // Update is called once per frame
    void Update()
    {
        using (var image = Frame.CameraImage.AcquireCameraImageBytes())
        {
            if (!image.IsAvailable)
            {
                return;
            }

            _OnImageAvailable(image.Width, image.Height, image.Y, 0);
        }
    }

    private void _OnImageAvailable(int width, int height, IntPtr pixelBuffer, int bufferSize)
    {
        if (m_EdgeDetectionBackgroundTexture == null ||
                this.m_EdgeDetectionResultImage == null ||
                m_EdgeDetectionBackgroundTexture.width != width ||
                m_EdgeDetectionBackgroundTexture.height != height)
        {
            m_EdgeDetectionBackgroundTexture =
                new Texture2D(width, height, TextureFormat.RGBA32, false, false);
            m_EdgeDetectionResultImage = new byte[width * height * 3 / 2];

            // m_EdgeDetectionResultImage = new byte[width * height];
            m_CameraImageToDisplayUvTransformation = Frame.CameraImage.ImageDisplayUvs;
        }
        // m_CameraImageToDisplayUvTransformation = Frame.CameraImage.ImageDisplayUvs;
        
        // m_EdgeDetectionBackgroundTexture = new Texture2D(width, height, TextureFormat.RGBA32, false, false);
        bufferSize = width * height * 3 / 2;
        System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, m_EdgeDetectionResultImage, 0, bufferSize);
        Color color = new Color();
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {

                float Yvalue = m_EdgeDetectionResultImage[y * width + x];
                float Uvalue = m_EdgeDetectionResultImage[(y / 2) * (width / 2) + x / 2 + (width * height)];
                float Vvalue = m_EdgeDetectionResultImage[(y / 2) * (width / 2) + x / 2 + (width * height) + (width * height) / 4];
                color.r = Yvalue + (float)(1.37705 * (Vvalue - 128.0f));
                color.g = Yvalue - (float)(0.698001 * (Vvalue - 128.0f)) - (float)(0.337633 * (Uvalue - 128.0f));
                color.b = Yvalue + (float)(1.732446 * (Uvalue - 128.0f));

                color.r /= 255.0f;
                color.g /= 255.0f;
                color.b /= 255.0f;

                if (color.r < 0.0f)
                    color.r = 0.0f;
                if (color.g < 0.0f)
                    color.g = 0.0f;
                if (color.b < 0.0f)
                    color.b = 0.0f;

                if (color.r > 1.0f)
                    color.r = 1.0f;
                if (color.g > 1.0f)
                    color.g = 1.0f;
                if (color.b > 1.0f)
                    color.b = 1.0f;

                color.a = 1.0f;
                m_EdgeDetectionBackgroundTexture.SetPixel(width - 1 - x, y, color);
            }
        }


        m_EdgeDetectionBackgroundTexture.Apply();

        imageCanvas.material.SetTexture("_ImageTex", m_EdgeDetectionBackgroundTexture);
        const string TOP_LEFT_RIGHT = "_UvTopLeftRight";
        const string BOTTOM_LEFT_RIGHT = "_UvBottomLeftRight";
        imageCanvas.material.SetVector(TOP_LEFT_RIGHT, new Vector4(
            m_CameraImageToDisplayUvTransformation.TopLeft.x,
            m_CameraImageToDisplayUvTransformation.TopLeft.y,
            m_CameraImageToDisplayUvTransformation.TopRight.x,
            m_CameraImageToDisplayUvTransformation.TopRight.y));
        imageCanvas.material.SetVector(BOTTOM_LEFT_RIGHT, new Vector4(
            m_CameraImageToDisplayUvTransformation.BottomLeft.x,
            m_CameraImageToDisplayUvTransformation.BottomLeft.y,
            m_CameraImageToDisplayUvTransformation.BottomRight.x,
            m_CameraImageToDisplayUvTransformation.BottomRight.y));
        //var encodedpng = m_TextureRender.EncodeToPNG();
        //var path = Application.persistentDataPath;
        //File.WriteAllBytes(path + "/YUV2RGB.png", encodedpng);
    }
}
`

**Comment by sonary01** [comment]
Sorry! It's been a while, I couldn't trace back that work. I remember I was also getting flipped image ( See letters B and C in the figure).

**Comment by gogittossjx** [comment]
Dont know if this is still an issue, but the talk about flipped images in this issue
https://github.com/google-ar/arcore-unity-sdk/issues/221

**Comment by AlabamaBen** [comment]
> There was a mistake in my YUVto RGB a conversion. Now getting good results.
> 
> ![image](https://user-images.githubusercontent.com/25668351/45319669-714f6b80-b50e-11e8-951d-ad5ade947a00.png)
> 
> Modified _OnImageAvailable () method:
> 
> ```
> 
> private void _OnImageAvailable(int width, int height, IntPtr pixelBuffer, int bufferSize)
> 		{
> 
> 			m_TextureRender = new Texture2D (width, height, TextureFormat.RGBA32, false, false);
> 			byte[] bufferYUV = new byte[width * height*3/2];
> 			bufferSize = width * height*3/2;
> 			System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, bufferYUV, 0, bufferSize);
> 			Color color = new Color ();
> 			for (int y = 0; y < height; y++) {
> 				for (int x = 0; x < width; x++) {
> 
> 					float Yvalue = bufferYUV[y * width + x];
> 					float Uvalue = bufferYUV[(y / 2) * (width/2) + x/2 + (width * height)];
> 					float Vvalue = bufferYUV[(y / 2) * (width/ 2) + x / 2 + (width* height)+ (width * height)/4];
> 					color.r= Yvalue + (float)(1.37705 * (Vvalue-128.0f));
> 					color.g= Yvalue - (float)(0.698001 * (Vvalue-128.0f)) - (float)(0.337633 * (Uvalue-128.0f));
> 					color.b= Yvalue + (float)(1.732446 * (Uvalue-128.0f));
> 
> 					color.r /= 255.0f;
> 					color.g /= 255.0f;
> 					color.b /= 255.0f;
> 
> 					if (color.r < 0.0f)
> 						color.r = 0.0f;
> 					if (color.g < 0.0f)
> 						color.g = 0.0f;
> 					if (color.b < 0.0f)
> 						color.b = 0.0f;
> 
> 					if (color.r > 1.0f)
> 						color.r = 1.0f;
> 					if (color.g > 1.0f)
> 						color.g = 1.0f;
> 					if (color.b > 1.0f)
> 						color.b = 1.0f;
> 
> 					color.a = 1.0f;
> 					m_TextureRender.SetPixel (width - 1 - x, y, color);      
> 				}
> 			}
> 
> 					
> 			m_TextureRender.Apply();
> 			var encodedpng = m_TextureRender.EncodeToPNG ();
> 			var path = Application.persistentDataPath;
> 			File.WriteAllBytes (path + "/YUV2RGB.png", encodedpng);
>           }
> ```

Hi @sonary01 , thank's a lot for your help and code,  I also have issues using the TextureReaderAPI. 
I tried your code on the image buffer of the Frame.CameraImage.AcquireCameraImageBytes() as follow  :

`    private void _OnImageAvailable(int width, int height, IntPtr pixelBuffer, int bufferSize)
    {


        m_TextureRender = new Texture2D(width, height, TextureFormat.RGBA32, false, false);
        byte[] bufferYUV = new byte[bufferSize];
        System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, bufferYUV, 0, bufferSize);
        Color color = new Color();
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {

                float Yvalue = bufferYUV[y * width + x];
                float Uvalue = bufferYUV[(y / 2) * (width / 2) + x / 2 + (width * height)];
                float Vvalue = bufferYUV[(y / 2) * (width / 2) + x / 2 + (width * height) + (width * height) / 4];
                color.r = Yvalue + (float)(1.37705 * (Vvalue - 128.0f));
                color.g = Yvalue - (float)(0.698001 * (Vvalue - 128.0f)) - (float)(0.337633 * (Uvalue - 128.0f));
                color.b = Yvalue + (float)(1.732446 * (Uvalue - 128.0f));

                color.r /= 255.0f;
                color.g /= 255.0f;
                color.b /= 255.0f;

                if (color.r < 0.0f)
                    color.r = 0.0f;
                if (color.g < 0.0f)
                    color.g = 0.0f;
                if (color.b < 0.0f)
                    color.b = 0.0f;

                if (color.r > 1.0f)
                    color.r = 1.0f;
                if (color.g > 1.0f)
                    color.g = 1.0f;
                if (color.b > 1.0f)
                    color.b = 1.0f;

                color.a = 1.0f;
                m_TextureRender.SetPixel(width - 1 - x, y, color);
            }
        }


        m_TextureRender.Apply();
        Texture_Set = true;
    }
`

I apply the texture on default_material with a standard shader. And I still got result that looks like your first one : https://i.stack.imgur.com/jZDIC.jpg

Any idea of what I'm doing wrong ?

**Comment by moheydy** [comment]
the color changed to RGB because converted to JPG  otherwise is always black/white and 90 degrees rotate in raw texture format on devices
