### ISSUE TITLE
TextureReader never fires the OnImageAvailableCallback

### ISSUE THREAD

**Issue by jarileon** [google-ar/arcore-unity-sdk#383]
I need to get an access to the pixels of the device camera when using ARCore SDK (1.4.1) in Unity (2018.2.5f1).  

I found examples that show how this should be possible by using TextureReader and its OnImageAvailableCallback event. But it never gets fired. I debugged it and it seems that the following line in TextureReader.cs causes pixelBuffer to always be zero and therefore the 
OnImageAvailableCallback never gets called:

IntPtr pixelBuffer = m_TextureReaderApi.AcquireFrame(m_ImageBufferIndex, ref bufferSize);

I have added the TextureReader to my scene (to the First Person Camera gameobject) and subscribed to the OnImageAvailableCallback event in my custom script.

Is the TextureReader somehow broken? I would need the grayscale camera frame because I want to do some computer vision stuff on it.

**Comment by small-potatoes** [comment]
Hi @jarileon , the example you have modified is performing an edge detection mutation to the pixels.  To access the YUV image bytes, you simple need to call [Frame.CameraImage.AcquireCameraImageBytes](https://developers.google.com/ar/reference/unity/class/GoogleARCore/Frame/CameraImage#acquirecameraimagebytes).  Please re-open the issue if this does not solve you problem.

**Comment by kushG** [comment]
I'm also having the same issue of pixelBuffer always set to zero preventing OnImageAvailableCallback from getting called. Is there any fix/workaround available for this issue ?

**Comment by SimonAmpleman** [comment]
Make sure to disable Android Multithread rendering in the project settings. It will be fired after removing it.

**Comment by AlabamaBen** [comment]
Hi, I have the same issue about pixelBuffer always  being null, so OnImageAvailableCallBack is never fired. Is this solution still working ? If not how can I get a color rgb frame from the camera ? 
Thanks in advance
