### ISSUE TITLE
Disable tracking

### ISSUE THREAD

**Issue by OguzFARSAK** [google-ar/arcore-unity-sdk#387]
Is there any way to disable image tracking? I want to stop image recognition when I want to. (ex : in menu)

**Comment by OguzFARSAK** [comment]
I think I solved it by adding a controller at start of  foreach block that in Update() method of AugmentedImageExampleController.class

AugmentedImageExampleController.class >>
void Update() >>
 foreach (var image in m_TempAugmentedImages) block { 
// add if statement here 
....
}

**Comment by fredsa** [comment]
You can set `AugmentedImageDatabase` to `null` in your `ARCoreSessionConfig` to (temporarily) disable augment image detection and tracking.
