### ISSUE TITLE
ARCoreBackgroundRenderer not restoring camera projection matrix

### ISSUE THREAD

**Issue by DmytroHreshchik** [google-ar/arcore-unity-sdk#389]
Here is a case:
1. Disable ARCoreBackgroundRenderer component.
2. Change device orientation from Portrait to Landscape.
3. Camera image is stretched and distorted.

Here is what I found. ARCoreBackgroundRenderer alters camera projection matrix in the Update method. If you turn off the component it doesn't return projection matrix to standard values. I believe this is the reason of visual bugs we're experiencing in our app.

I'm using ARCore v 1.4.1.

**Comment by small-potatoes** [comment]
Hi @DmytroHreshchik , thanks for the report.  I have added this to our internal bug tracker.

**Comment by fredsa** [comment]
If you want to continue using ARCore, but don't want the camera preview image to render, you can make a copy of the SDK's `ARCoreBackgroundRenderer` and change this line:

            m_BackgroundRenderer.mode = ARRenderMode.MaterialAsBackground;
to:

            m_BackgroundRenderer.mode = ARRenderMode.StandardBackground;

If you in fact want to stop using the background renderer at runtime, you can reset the projection matrix using [Camera.ResetProjectionMatrix()](https://docs.unity3d.com/ScriptReference/Camera.ResetProjectionMatrix.html) after disabling the `ARCoreBackgroundRenderer ` component.

**Comment by small-potatoes** [comment]
This has been fixed in the [ARCore SDK for Unity version 1.7](https://github.com/google-ar/arcore-unity-sdk/releases) release.

**Comment by Zumbalamambo** [comment]
@fredsa  if I disable the ARCoreBackgroundRenderer, the 3D object is being tracked however while visualizing, the 3D  object appears to be moving with the camera. Is there any possible fix for the same?

**Comment by fredsa** [comment]
@Zumbalamambo  Please compare your code with the HelloAR sample for how to use Anchors to place objects.
