### ISSUE TITLE
Ar core feature points suddenly disappeared and not able to search plane

### ISSUE THREAD

**Issue by abhinav22rana** [google-ar/arcore-unity-sdk#394]
Hi,
I have not changed anything in the project but suddenly AR core App is not able to detect or search the plane surface and even camera is not able to detect the feature points on any provided surface. This problem occurs every now and then. 

Kindly help if anyone knows the solution of this problem.

**Comment by small-potatoes** [comment]
Hi abhinav22rana@, can you import the SDK into an empty project and confirm this is still happening on the HelloAR example?  If so, then could you please report your Unity editor version, your device fingerprint, and if this is happening on-device or in instant preview?

**Comment by abhinav22rana** [comment]
I have tried every possible solution I can think of. But instant preview is not working at any cost.


In the end I found that AR Core  (version 1.3)  instant preview only works on the Unity 2017.3

________________________________

**Comment by pablisho** [comment]
Hi @abhinav22rana are you still experiencing this issue with ARCore 1.5.0? If so, please provide more information about your environment: InstantPreview vs Device, Unity version, platform, device fingerprint.

**Comment by chaosemer** [comment]
Closing this due to lack of a reply.

If you are still having the issue, please reopen and report the specific device fingerprint, ARCore version on your phone, and ARCore SDK version.
