### ISSUE TITLE
Galaxy Tab S4 inconsistent crash immediately after splashscreen

### ISSUE THREAD

**Issue by jcoschi** [google-ar/arcore-unity-sdk#395]
I'm getting inconsistent/random crashes when my app starts up on my Galaxy Tab S4 (but never on my Google Pixel, I only have the 2 devices to test on). I've tested this on several apps with the exact same error on all apps (except timestamp, package name, pid/tid, etc), and cannot reproduce on a Google Pixel. The crash sometimes happens several times in a row, sometimes only after 10-30 times opening the app. A device restart reduces the consistency of the crashes, but they eventually happen again.

This is the logcat Fatal error that occurs:
>F native  : statusor.cc:21 Attempting to fetch value instead of handling error generic::invalid_argument: CLOCK_MONOTONIC is ahead of CLOCK_BOOTTIME by 5.573us. Max is 5us
>F native  : terminating.
>F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 25683 (ImageReader-640), pid 25601 (███████████████)
>F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
>F DEBUG   : Build fingerprint: 'samsung/gts4lwifixx/gts4lwifi:8.1.0/M1AJQ/T830XXU1ARGH:user/release-keys'
>F DEBUG   : Revision: '7'
>F DEBUG   : ABI: 'arm'
>F DEBUG   : pid: 25601, tid: 25683, name: ImageReader-640  >>> ████████████████████████ <<<
>F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
>F DEBUG   : Abort message: 'statusor.cc:21 Attempting to fetch value instead of handling error generic::invalid_argument: CLOCK_MONOTONIC is ahead of CLOCK_BOOTTIME by 5.573us. Max is 5us
>F DEBUG   : '
>F DEBUG   :     r0 00000000  r1 00006453  r2 00000006  r3 00000008
>F DEBUG   :     r4 00006401  r5 00006453  r6 c34824a4  r7 0000010c
>F DEBUG   :     r8 00000000  r9 c47f8120  sl c34828fc  fp 00000000
>F DEBUG   :     ip 00000341  sp c3482490  lr f3fb2417  pc f3fababc  cpsr 20070030
>F DEBUG   :
>F DEBUG   : backtrace:
>F DEBUG   :     #00 pc 0001aabc  /system/lib/libc.so (abort+63)
>F DEBUG   :     #01 pc 0058bd41  /data/app/com.google.ar.core-E5akKUPSgDgCekReKVKXEg==/lib/arm/libarcore_c.so
>F DEBUG   :     #02 pc 0057874f  /data/app/com.google.ar.core-E5akKUPSgDgCekReKVKXEg==/lib/arm/libarcore_c.so
>F DEBUG   :     #03 pc 0008bd37  /data/app/com.google.ar.core-E5akKUPSgDgCekReKVKXEg==/lib/arm/libarcore_c.so
>F DEBUG   :     #04 pc 0008cb79  /data/app/com.google.ar.core-E5akKUPSgDgCekReKVKXEg==/lib/arm/libarcore_c.so
>F DEBUG   :     #05 pc 0009037b  /data/app/com.google.ar.core-E5akKUPSgDgCekReKVKXEg==/lib/arm/libarcore_c.so
>F DEBUG   :     #06 pc 0000dd91  /system/lib/libmediandk.so (AImageReader::CallbackHandler::onMessageReceived(android::sp<android::AMessage> const&)+156)
>F DEBUG   :     #07 pc 00010649  /system/lib/libstagefright_foundation.so (android::AHandler::deliverMessage(android::sp<android::AMessage> const&)+24)
>F DEBUG   :     #08 pc 00012b3d  /system/lib/libstagefright_foundation.so (android::AMessage::deliver()+60)
>F DEBUG   :     #09 pc 000112af  /system/lib/libstagefright_foundation.so (android::ALooper::loop()+470)
>F DEBUG   :     #10 pc 0000d343  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+270)
>F DEBUG   :     #11 pc 000751e5  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+80)
>F DEBUG   :     #12 pc 00048d33  /system/lib/libc.so (__pthread_start(void*)+22)
>F DEBUG   :     #13 pc 0001b8df  /system/lib/libc.so (__start_thread+32)

**Galaxy Tab S4 info:**
Android version: 8.1.0
Android security patch level: June 1, 2018
Samsung Experience version: 9.5
Kernel version: 4.4.78-13881803
Knox version: 3.2, API 26, TIM 4.1.0

**Comment by small-potatoes** [comment]
Thanks for the report, I have created an internal bug to track this issue.

**Comment by DoomerDGR8** [comment]
I have a similar experience with a Sony Xperia XZ Premium: Build & Run deploy the app to phone and I see the Unity logo and then a crash. But debugging within Unity is possible but the quality of the ARCore Instant preview is impossible to work with.

Model: G8142
Android version: 8.0.0
Android security patch level: Sep 1, 2018
Kernel version: 4.4.78-pref+
Build #47.1.A.16.20

**Comment by Tritaru** [comment]
Our sales team just bought several of these devices, only to experience hard crashes that reboot the device after random durations, as described.

Anyone have any leads on this? I'm going to continue looking into tonight.

**Comment by helios02** [comment]
We are experienced the same issues with the Galaxy Tab S4. On scenes with ARCore, the application randomly crashes on load. Like the original poster describes, sometimes it happens on the first attempt, sometimes after 10-30 tries. This does not happen ever on our Pixel device.

**Comment by kolboch** [comment]
I experience same issues on LG G6 phone, once the app gets camera stream it will not crash. It only happens before getting stream from camera -> splash with Unity logo or black screen before ( I guess) session and everything arround starts.

**Comment by chaosemer** [comment]
Hi, I am unable to reproduce the issue on my Galaxy Tab S4. Could you please share a minimal repro project with me and @small-potatoes?

Thank you for your help here.

**Comment by jcoschi** [comment]
Sorry about the late response. I'll work on getting a stripped-down version of the project for the two of you.

**Comment by jcoschi** [comment]
@chaosemer @small-potatoes sorry again about the late reply, but the 'good' news is that we are unable to reproduce the issue anymore. I'm presuming that a Samsung or Android update has resolved the issue.

**Updated/Current Galaxy Tab S4 info:**
Android version: 8.1.0
Android security patch level: December 1, 2018
Samsung Experience version: 9.5
Kernel version: 4.4.78-14803871
Knox version: 3.2, API 26, TIM 4.1.0

The only differences on the tablet that I'm sure of (via the stats initially reported) are the Android security patch level and the Kernel version.

Thanks for your patience and time!

**Comment by fredsa** [comment]
Glad to here that your issue no longer reproduces.
