### ISSUE TITLE
Next version release and release ecosystem

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-unity-sdk#396]
Hello, 

When will be next release? I assume that something matching ARKit 2.0 possibillities is coming as there is no update in such a long time? ;)

How are the updates managed? Is the Google itself developing libraries for ARCore and we are waiting for them? Is there any way to contact this team?

Regards,
Greg

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released. I cannot share the timeline for our next releases. The official channel for bug reports and feature requests is this board.
