### ISSUE TITLE
ARCore HelloAR example (+others) crashing immediately

### ISSUE THREAD

**Issue by DoomerDGR8** [google-ar/arcore-unity-sdk#397]
Hello world!

I’m trying to run the HelloAR example for AR core on my Sony Xperia XZ Premium but every time I open the app on my phone, I see the **_Made with Unity_** logo and then an immediate crash. Appreciate any help with this.

I followed these guides:
 - https://developers.google.com/ar/develop/unity/quickstart-android

I'm trying to replicate this cool dude:
 - https://www.youtube.com/watch?v=GkzMFNmvums&t=187s

**Specs:**
Model: G8142
Android version: 8.0.0
Android security patch level: Sep 1, 2018
Kernel version: 4.4.78-pref+
Build #47.1.A.16.20

**Comment by FUBAR2077** [comment]
Hello, have you:
- accepted camera permission, 
- marked ARCore as required
- installed ARCore on your device?
- restarted phone
- tried other ARCore apps if they work
please try and let me know if any of those helped?

**Comment by DoomerDGR8** [comment]
Q: accepted camera permission,
A: The app once deployed, never asks for camera permission. but I forced enabled it in permissions settings

Q: marked ARCore as required
A: Dunno about this one

Q: installed ARCore on your device?
A: ArCore is installed. Built-in Sony apps work and also Google's ruler works

Q: restarted phone
A: Lost count of how many times

Q: tried other ARCore apps if they work (i.e. https://play.google.com/store/apps/details?id=com.arexperiments.justaline)?
A: Works

Q: please try and let me know if any of those helped
A: Done

**Comment by FUBAR2077** [comment]
Hi @DoomerDGR8 - 
- Please check if you have marked the ARCore Required checkbox in Edit>ProjectSettings>ARCore
if this does not help:
- please import the plugin to the new clean Unity Project and try to build one of the examples.
if this still does not work:
- please try with newest plugin version 1.5.0

**Comment by DoomerDGR8** [comment]
Positive progress has been made:

Q: Please check if you have marked the ARCore Required checkbox in Edit>ProjectSettings>ARCore
A: ARCore is set to required

Q: please import the plugin to the new clean Unity Project and try to build one of the examples.
A: Still doesn't work. Any of the demo scenes installed with ARCore SDK doesn't work

Optional: Installed a LogCat reader and the app I'm building doesn't log anything

Q: please try with newest plugin version 1.5.0
A: This may have done something

Latest:
Now the app runs and after the logo, the camera output appears for a second and then the app crashes. LogCat still doesn't log anything while in float windows (Logcat Extreme Pro)

**Comment by DoomerDGR8** [comment]
So, with v1.5.0, I see that all supplied demos are now working fine. So, something is amiss with my project which I'm sharing here in bare-essential format. I also upgraded to Unity 3D v2018.3.b3 in order to help myself. Forgive me. No going back.

Project: https://1drv.ms/f/s!AniVX60enXnSu6F0k8BnbqhWI90xEQ

**Comment by pablisho** [comment]
Hi @DoomerDGR8, is your problem solved? Maybe you had some inconsistencies when updating the version of the plugin? Let me know if this can be closed or you need more help.

**Comment by DoomerDGR8** [comment]
My issue is still open. I shared the simple problem project.

**Comment by HercullesGoulart** [comment]
I had the same problem,  vou can solve it on build settings change from gradle to internal build. Now the app will load.

**Comment by khalv** [comment]
A colleague of mine has the same problem. Crashes right after load screen.

**Comment by yKimisaki** [comment]
I has the same problem on IL2CPP, then I try adb logcat.
Logs are "code around pc: lib/arm/libarcore_unity_api.so" and "code around lr: ArCoreUnity_setArPrestoInitialized".
The HelloAR is run completely on Mono, Xperia XZ1(G8342), Android 8.0.0.

**Comment by khalv** [comment]
We tried reinstalling Android Studio, it now works for him.

**Comment by Storm-Develop** [comment]
@DoomerDGR8  So I downloaded your zip file shared on OneDrive. The project has missing prefab and ``UnityEditor.Collaboration.ICollabHistoryWindow' is inaccessible due to its protection level
` I would recommend is to shared the repo using GitHub and also check if you can clone and open the project.

In any way I found one mistake, please make sure to uncheck the Android TV Compability. So the issue mostlikely is not even related to GoogleARCore. I would reccomend to try to double check the deployment settings for Android device in Unity. https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html
![image](https://user-images.githubusercontent.com/11896104/50944744-41ca5480-1457-11e9-82b9-28a6e5ef9ab6.png)

**Comment by fredsa** [comment]
Closing this issue as it seems to be project specific and the provided SDK sample scene work.

**Comment by zestiros** [comment]
Remove Vulkan to activate ARCore

**Comment by aymusbond** [comment]
Even I am facing this problem on OnePlus 7.
