### ISSUE TITLE
Crash on Startup - Abort message: 'jni_helper.cc:19 'vm' Must be non NULL'

### ISSUE THREAD

**Issue by Goya-** [google-ar/arcore-unity-sdk#4]
My devices is Samsung SM-G9500. After build and run the helloAR scene, app cash and get some error from adb logcat. Why the cash happen?

08-30 10:06:54.317 17086 17086 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-30 10:06:54.318 17086 17086 F DEBUG   : Build fingerprint: 'samsung/dreamqltezc/dreamqltechn:7.0/NRD90M/G9500ZCU1AQF7:user/release-keys'
08-30 10:06:54.318 17086 17086 F DEBUG   : Revision: '12'
08-30 10:06:54.318 17086 17086 F DEBUG   : ABI: 'arm'
08-30 10:06:54.319 17086 17086 F DEBUG   : pid: 17021, tid: 17035, name: UnityMain  >>> com.hisceneyn.helloar <<<
08-30 10:06:54.319 17086 17086 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-30 10:06:54.326 17086 17086 F DEBUG   : Abort message: 'jni_helper.cc:19 'vm' Must be non NULL'
08-30 10:06:54.326 17086 17086 F DEBUG   :     r0 00000000  r1 0000428b  r2 00000006  r3 00000008
08-30 10:06:54.326 17086 17086 F DEBUG   :     r4 e6428978  r5 00000006  r6 e6428920  r7 0000010c
08-30 10:06:54.326 17086 17086 F DEBUG   :     r8 e6426d68  r9 e6426d64  sl 00000515  fp e6427078
08-30 10:06:54.326 17086 17086 F DEBUG   :     ip 00000054  sp e64268e8  lr e7c19ba7  pc e7c1c4a0  cpsr 200f0010
08-30 10:06:54.342 17086 17086 F DEBUG   :
08-30 10:06:54.342 17086 17086 F DEBUG   : backtrace:
08-30 10:06:54.342 17086 17086 F DEBUG   :     #00 pc 0004b4a0  /system/lib/libc.so (tgkill+12)
08-30 10:06:54.342 17086 17086 F DEBUG   :     #01 pc 00048ba3  /system/lib/libc.so (pthread_kill+34)
08-30 10:06:54.342 17086 17086 F DEBUG   :     #02 pc 0001e1b9  /system/lib/libc.so (raise+10)
08-30 10:06:54.343 17086 17086 F DEBUG   :     #03 pc 000197a5  /system/lib/libc.so (__libc_android_abort+34)
08-30 10:06:54.343 17086 17086 F DEBUG   :     #04 pc 00017540  /system/lib/libc.so (abort+4)
08-30 10:06:54.343 17086 17086 F DEBUG   :     #05 pc 00005bb5  /system/lib/liblog.so (__android_log_assert+112)
08-30 10:06:54.343 17086 17086 F DEBUG   :     #06 pc 00009e69  /data/app/com.hisceneyn.helloar-1/lib/arm/libtango_client_api2.so
08-30 10:06:54.343 17086 17086 F DEBUG   :     #07 pc 0001256d  /data/app/com.hisceneyn.helloar-1/lib/arm/libtango_client_api2.so
08-30 10:06:54.343 17086 17086 F DEBUG   :     #08 pc 00009247  /data/app/com.hisceneyn.helloar-1/lib/arm/libtango_client_api2.so (TangoService_isSupported+26)
08-30 10:06:54.343 17086 17086 F DEBUG   :     #09 pc 0000618c  <anonymous:c5302000>

**Comment by secondage** [comment]
what device do you run it? I met the same problem as you， my device is s8 GM9500, not include in the support list.

**Comment by GtoDair** [comment]
I met the same problem as you,my device is s8 GM9500 to, not include in the support list.

**Comment by GtoDair** [comment]
I met the same problem as you,my device is s8+ GM9550 to,

**Comment by nathanmartz** [comment]
Thank you for the bug report. Right now the ARCore technical preview does not support S8+ or the GM9500 variant of the S8, but I will share these issues to our device compat team.

**Comment by GtoDair** [comment]
Probably when can support S8+

**Comment by liortal53** [comment]
I also have this issue. Running on a Samsung S8 (which is in the supported device list). is there any update regarding this issue ?
