### ISSUE TITLE
ARCore update pace

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-unity-sdk#400]
Hello, I have an discussion topic here but an important one - 
I think that ARCore should proceed faster. I was quite disappointed with 1.5.0 update as ARKit is rapidly moving forward with its 2.0 update with features like:
- real time built cubemap for realistic reflections
- stable image tracking
- 3d object scanning
- integrated face tracking
- serialized world map for multiuser interactions

ARCore seems to be stagnated - no "breaking changes", some fixes but mainly invisible for the core of the experience.
This technology does not deserve to proceed so slowly as it can be The Next Big Thing, but currently the ARKit is overtaking ARCore by half lightyear. 

Sorry @pablisho for those words but I don't mean anything mean, just being honest and you are the only one who can pass my (our?) concerns to rest of the Google Team behind ARCore.

If there are not enough people in the R&D team maybe there is possibillity to let supervisors know that Google is behind Apple in this matter, they will be interested for sure and maybe add more fireteams to the case :)

**Comment by pablisho** [comment]
Thanks for the feature requests. For shared/multi user experiences take a look at Cloud Anchors https://developers.google.com/ar/develop/unity/cloud-anchors/overview-unity

**Comment by kolboch** [comment]
+1 and at the same time I quite understand Google. Apple has its ecosystem and is able to produce bug free soft faster, at the same time there is Google which ARCore support LG, Samsung, Xaomi, etc. You see the difference, but its true that it would be great if there would be more resources put into development and maintanace/ fixing existing bugs for ARCore.
When it comes to big thing I think hardware needs to adapt (wearables like google glass), as its one of few cases where software is way ahead of the technology it does need IMO.

**Comment by kolboch** [comment]
Maybe Google is closer to general super intelligence and put more resources into that. Just kidding do not take me serious :D @Tritaru I wish so too, more competition is better products, and talking about apple closed ecosystems i guess it would not be different with AR at some point from them ehhh...

**Comment by FUBAR2077** [comment]
I'll try to look up some contact to management from Google and see what we can do, this technology deserves better treatment for sure.

**Comment by chilton** [comment]
Google should OWN this space. The idea that Google doesn't have the resources to make this a competitor to Apple is hilarious. This is Google, not some indie software company. Android deserves better. 

Consider that Vuforia's image tracker has been the gold standard for years, and considering that Google's image recognition system is supposedly the best in the world, why they released image tracking as a barely capable solution is just weird. Is there no internal communication between groups in Google? This seems like something they solved years ago, but here we are. 

Google had Google Glasses AND Project Tango. So why does this constantly feel like they're just now catching up?

**Comment by fredsa** [comment]
The general request to "go faster" is understood and constructive feedback is always appreciated.

Marking this issue as closed in order to keep open issues focused on specific actionable bug reports and feature requests.
