### ISSUE TITLE
Samsung Galaxy Tab S3/S4 supported, but unable to install ARCore using Play Store

### ISSUE THREAD

**Issue by RYG81** [google-ar/arcore-unity-sdk#401]
With AR Core 1.5 my Galaxy Tab S3 is in the list of supported devices, WooHoo!

But when I tried to download the ARCore app on my Galaxy Tab S3 from play store it says my device is not compatible. What to do?
Please help
Rahul

**Comment by FUBAR2077** [comment]
With Xperia XZ2 Compact we had to update phone software to the newest one, check for updates and try to install newest ones - we had to update it few times until it finally got updated to the required one.

**Comment by pablisho** [comment]
Hi @RYG81, try updating to the latest version of Android.

**Comment by HolgerDurach** [comment]
I have the same problem with my tab S4. PlayStore says the arcore app is not supported on this device. I have the latest updated available in Germany installed.
My device's fingerprint is: samsung/dream2ltexx/dream2lte:8.0.0/R16NW/G955FXXU4CRI5:user/release-keys

**Comment by HolgerDurach** [comment]
jfyi, today i did (again) an restart of the device, and now all of a sudden, i was able to install arcore. There was no update to the device, so i guess they might have updated the arcore version in the appstore in germany. maybe all try to delete any cached files of the play store (via settings/app). good luck

**Comment by chaosemer** [comment]
It sounds like this is fixed and I verified you can install ARCore on the S3 and S4 locally, so I'm marking this "closed". Please reopen if you have a particular device that is unable to install ARCore.

**Comment by vr-lucky** [comment]
Google Arcore 

Installed the app Samsung Tab s3 no problem it's listed in the settings but the app does not show in the apps section  so can't open etc.

**Comment by chaosemer** [comment]
That's expected. ARCore is a library that enables other apps to function. Try installing apps such as [Measure](https://play.google.com/store/apps/details?id=com.google.tango.measure&hl=en_US) to try out ARCore functionality.
