### ISSUE TITLE
How to set AugmentedImageDatabase in ARCoreSeesion using code?

### ISSUE THREAD

**Issue by Learningm** [google-ar/arcore-unity-sdk#406]
Hi, all.
I am using UnityARInterface to build ARCore and ARKit application. In UnityARInterface, it will create the corresponding interface upon on your running platform, when it comes to ARCore, it will create a new ARCoreSession variable and configure it's properties manually.
I want to know how to specify the AugmentedImageDatabase property using code? Can I use files and paths to achieve it? If so, how to do it? **I have already created the database file.**

The code sample seems like:
if (m_ARCoreSessionConfig == null)
                m_ARCoreSessionConfig = ScriptableObject.CreateInstance<ARCoreSessionConfig>();

m_ARCoreSessionConfig.EnableLightEstimation = settings.enableLightEstimation;
m_ARCoreSessionConfig.MatchCameraFramerate = true;
m_ARCoreSessionConfig.CameraFocusMode = CameraFocusMode.Auto;
//how to config the database
**m_ARCoreSessionConfig.AugmentedImageDatabase = ????**

Thanks.

**Comment by Learningm** [comment]
I finally solved the problem by using the copyFrom method. Passing a defaultSessionConfig from Unity Editor to ARCoreInterface then copy it is ok.

**Comment by Phanou36** [comment]
Hello
I try to add image in runtime to my AugmentedImageDatabase.
I use the code below but nothing happen . In my code "camera" is my ARCoreSession.
 ```
public class test : MonoBehaviour {
 
     public Sprite monimage;
     public ARCoreSession masession;
     public List<AugmentedImage> m_TempAugmentedImages = new List<AugmentedImage>();
 
     void Start ()
     {
         AugmentedImageDatabase imageDatabase = (ScriptableObject.CreateInstance<AugmentedImageDatabase>());
        ARCoreSessionConfig sessionCongif = (ScriptableObject.CreateInstance<ARCoreSessionConfig>());
        
        int i = imageDatabase.AddImage("test", monimage.texture, 0);

        sessionCongif.AugmentedImageDatabase = imageDatabase;
        masession.SessionConfig = sessionCongif;

         Session.GetTrackables<AugmentedImage>(m_TempAugmentedImages, TrackableQueryFilter.Updated);
         Debug.Log(m_TempAugmentedImages.Count + " image in the AugmentedImageDatabase"); // ==0
     }
     
 }
```

**Comment by TammyMin** [comment]
> I try to add image in runtime to my AugmentedImageDatabase.
> I use the code below but nothing happen . In my code "camera" is my ARCoreSession.

HI Have you solved it?

**Comment by Learningm** [comment]
> Hello
> I try to add image in runtime to my AugmentedImageDatabase.
> I use the code below but nothing happen . In my code "camera" is my ARCoreSession.
> 
> ```
> public class test : MonoBehaviour {
> 
>     public Sprite monimage;
>     public ARCoreSession masession;
>     public List<AugmentedImage> m_TempAugmentedImages = new List<AugmentedImage>();
> 
>     void Start ()
>     {
>         AugmentedImageDatabase imageDatabase = (ScriptableObject.CreateInstance<AugmentedImageDatabase>());
>        ARCoreSessionConfig sessionCongif = (ScriptableObject.CreateInstance<ARCoreSessionConfig>());
>        
>        int i = imageDatabase.AddImage("test", monimage.texture, 0);
> 
>        sessionCongif.AugmentedImageDatabase = imageDatabase;
>        masession.SessionConfig = sessionCongif;
> 
>         Session.GetTrackables<AugmentedImage>(m_TempAugmentedImages, TrackableQueryFilter.Updated);
>         Debug.Log(m_TempAugmentedImages.Count + " image in the AugmentedImageDatabase"); // ==0
>     }
>     
> }
> ```

I have tried database assignment using similar code as you, and it didn't work.
sessionCongif.AugmentedImageDatabase = imageDatabase; // seems not work

I suggest you to use my method mentioned above, avoid to create an empty database, just use an existing database and add image at runtime, I think it will be ok.

Feel free to reopen the issue.
