### ISSUE TITLE
AugmentedImageDatabase.AddImage hangs

### ISSUE THREAD

**Issue by Noobay** [google-ar/arcore-unity-sdk#410]
i added an image image to an `AugmentedImageDatabase `using the `AugmentedImageDatabase.AddImage` method, and the application hangs, I was ready for some delay, but in this case i'd expect it to crash and/or return an error, is this intentional?

It hangs right after the external method `ExternApi.ArPrestoAugmentedImageDatabase_addImageAtRuntime` is called by `AddImageAtRuntime`.

**Comment by Noobay** [comment]
caused by a faulty conversion from ARGB32 to RGBA32

**Comment by pablisho** [comment]
Hi, thanks for the report. Could you provide the logcat of the issue? Even better, if you could provide a small repro project. Thanks!

**Comment by Noobay** [comment]
When i tried reproducing in an empty project, I got the error mentioned in 
#403.

However, in the original project with the bug, I created an `AugmentedImageDatabase` during the application's run-time.
when I went back and created an  `AugmentedImageDatabase`  in the editor (before building) and used it, addImage worked.
I will try to reproduce the error for the logcat output, but I can't seem to get a clean project with(just) the bug.

**Comment by Noobay** [comment]
is the AugmentedImageDB created during the application's runtime? can you paste the logcat data?

**Comment by alikanat001** [comment]
@Noobay no i created AugmentedImageDB in the editor. However, i was not using any Database in my ARSessionConfig. Apparently it causes problems i dont know why ?  Now i started using the database created in editor app in config, it does not hang anymore. Thanks

**Comment by tortoise00q** [comment]
I tried the solution mentioned by @Noobay and @alikanat001 but I still having the same problem. There  was not any error from the logcat, the app just hangs after the ExternApi.ArPrestoAugmentedImageDatabase_addImageAtRuntime is called.
