### ISSUE TITLE
Failed To host cloud anchor : ErrorNotAuthorized

### ISSUE THREAD

**Issue by kushal98** [google-ar/arcore-unity-sdk#413]
Actually, When I am running the cloud anchor example in my ARcore supported device and when i am hosting the anchor i am getting this error. Can someone help me with this??

I'm using ARcore 1.4.1

**Comment by pablisho** [comment]
Hi, did you follow the instructions here https://developers.google.com/ar/develop/unity/cloud-anchors/overview-unity? In particular did you set the API Key?

**Comment by Siddhant-pixel** [comment]
> Thanks a lot . I fixed it.

Hie! 
i am Facing the same issue ? Could you tell what you did to solve this thing

**Comment by Zumbalamambo** [comment]
@kushal98  how did you fix it bhaai?
