### ISSUE TITLE
Spawned models spawning a bit under the detected plane

### ISSUE THREAD

**Issue by KendrickMorales** [google-ar/arcore-unity-sdk#414]
Every time I spawn a model on a detected plane it spawns it a bit below the plane. I put the Andy prefab and it works great. Was I suppose to set the position something besides (0,0,0)?

**Comment by kolboch** [comment]
Please close, it is not ARCore problem guys. It is normal for every object, when its origin is in center of mass or wherever above lowest element it will be placed so it seems it's slightly below surface. You have to consider that in your code, like taking height of your object and making Z of transform half of that. But really it has nothing to do with ARCore, just google it.

**Comment by pablisho** [comment]
As other have mentioned, the problem is that you are placing the origin of your object (0,0,0) on the plane. The origin of your object is likely not on the base of your object, you have to either fix your model or account for that translation in your code.
