### ISSUE TITLE
This application requires the latest version of ARCore

### ISSUE THREAD

**Issue by ufukdemircivi** [google-ar/arcore-unity-sdk#417]
Hi friends. I have a question about ARCore. I'm developing an application for ARCore. But I want the app to run on devices that don't support Arcore. If I check the phone model and don't support ARCore, I'll open a partition that contains virtual reality. I'm checking the phone's model, redirecting it to a virtual reality partition, but when I'm forwarding a warning message, ARCore's latest version is installed and then redirects to the Play Store. How can I remove the warning message after I choose to redirect to a virtual reality partition?

**Comment by hansschaa** [comment]
How solucionated this problem?
