### ISSUE TITLE
ARCore Unity example is not working on Huawei Honor10

### ISSUE THREAD

**Issue by Lossdota** [google-ar/arcore-unity-sdk#419]
I'm running ARCore Unity example (https://developers.google.com/ar/develop/unity/quickstart-android#open_the_sample_scene) on my Huawei Honor10 (android 8.1 API Level 27). After building and running the project, it shows message "arcore encountered a problem connecting, please start app again" and closes itself. Here's the screenshot (https://pp.userapi.com/c851432/v851432906/215dd/XYsl31DGuPc.jpg)
I have tried many versions of Unity (newest one and the one thats required as minimum). I installed ARCore for my device at PlayMarket. Build settings in Unity have been changed as suggested in guide, that is:
Minimum API level: 7.0
Target API level : 8.1
ARCore supported: checked
I honestly cannot understand whats the problem. Could anyone come up with an answer?

**Comment by Lossdota** [comment]
I've ran into simillar problem after trying Android quickstart guide (https://developers.google.com/ar/develop/unity/quickstart-android#open_the_sample_scene)
After running the app screen goes black and I get "this device does not support AR" message (but it's listed in supported devices)
I also tried running some AR apps from PlayMarket and it worked :thinking:

**Comment by Lossdota** [comment]
@inio I've resolved it by updating OS on device (which is stange, because patch was about some protection fixes and nothing was said about AR stuff)

**Comment by tyrroncondo14** [comment]
@pablisho did you find any solutions?
