### ISSUE TITLE
Unchecking "Enable AR Background" from DefaultSessionConfig also disable tracking altogether.

### ISSUE THREAD

**Issue by quentinleguennec** [google-ar/arcore-unity-sdk#42]
All is in the title, I managed to fix by chanching `tangoConfig.enableColorCamera = sessionConfig.m_enableARBackground;` to `tangoConfig.enableColorCamera = true;` in "SessionComponent.cs". Not sure if it's affecting anything else though.

**Comment by chaosemer** [comment]
Thanks for the bug report! Your fix sounds correct.

I'm leaving this open so that other people will see this fix until the next release goes out.

**Comment by chaosemer** [comment]
This should now be resolved in Developer Preview 2. Please reopen if you still are having issues.
