### ISSUE TITLE
How to set the camera framerate to 60Hz or higher?

### ISSUE THREAD

**Issue by hukan008** [google-ar/arcore-unity-sdk#423]
HI, there.
   I tied ARCore with MI8 phone.  The camera of MI8 phone can recoding with 1280x720 resolution and 120 
fps. I want to run my ARCore app with a google DayDream headset, so I need the screen framerate be 90Hz or highter. becauce the 30fps made me dizz.  But I can not found a method to set the framerate of camera.
Is that ARCore sdk has a method can do this?

**Comment by vincentfretin** [comment]
@hukan008 The discussion in https://github.com/google-ar/arcore-android-sdk/issues/604 may interest you.

**Comment by pablisho** [comment]
Hi, currently ARCore tracking and background renderer cannot be set to 60Hz. As mentioned above see #337 for feature request.
