### ISSUE TITLE
"AR Core has stopped working" on Samsung S8

### ISSUE THREAD

**Issue by syedzainn** [google-ar/arcore-unity-sdk#424]
I'm trying to run Hello AR on Samsung Galaxy S8 and on launch it gives the error message.
Tried AR Core SDK 1.5 and 1.4
Please help

**Comment by alikanat001** [comment]
What is the error message ?

**Comment by syedzainn** [comment]
I don't know the exact error code, but it just gave a message that "AR Core has stopped working" when i ran the app, after a day, it stopped giving the error message itself

**Comment by alikanat001** [comment]
Does it work without building from Unity using instant preview ? i just bought a  S8 and it is working fine with my device.

**Comment by syedzainn** [comment]
I don't know the exact error code, but it just gave a message that "AR Core has stopped working" when i ran the app, after a day, it stopped giving the error message itself

**Comment by syedzainn** [comment]
No i didn't use instant preview

**Comment by pablisho** [comment]
Hi, this could be related to a fix it was recently released to the ARCore apk. Please feel free to comment or open a new issue if you experience this problem again.
