### ISSUE TITLE
Disable Image Tracking if one image gets tracked and re-enable after visualizer for that image is removed

### ISSUE THREAD

**Issue by shivamnyr** [google-ar/arcore-unity-sdk#425]
Hi

I want the image tracking to get disabled, if one image is already tracked and it's visualizer is on.
The tracking should get re-enabled once the visualizer of the previously tracked image is disabled.

In all, I want only one image to be tracked at once and once it is tracked, others should not be tracked.

Can you let me know how can this be achieved?

**Comment by pablisho** [comment]
Hi, you'll need to implement that logic on your side. I would save the name of the first tracked image and ignore the following ones. Let me know if this helps.
