### ISSUE TITLE
Ar core Insta Preview dont work on Note 9

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [google-ar/arcore-unity-sdk#427]
Ar core insta preview does not work on note 9 even when it is supported device for Arcore. Insta Preview launches but Unity Camera stays black..

In the ARCore Instant Preview app I can see "Press PLAY in Unity editor to stream", but after hitting the play button the screens turns black -> after 1 or 2 seconds it switches back to die initial app screen.

**Comment by pablisho** [comment]
Hi, thanks for the report. I added it to our internal tracker.

**Comment by fredsa** [comment]
Duplicate of #484
