### ISSUE TITLE
App crashes, if ARCore isn't installed

### ISSUE THREAD

**Issue by DmytroHreshchik** [google-ar/arcore-unity-sdk#43]
We want to handle case, when user doesn't have installed ARCore on device. I've checked where SessionConnectionState.DeviceNotSupported is used by the sdk, it is set in SessionComponent.Connect. But when I run the app with no ARCore installed on the device, the app crashes when I use SessionComponent.Connect. It looks like right now SessionConnectionState.DeviceNotSupported doesn't work.

Am I missing something? Is there a way to check, if ARCore is installed or supported on the device?

I've tested the app on Samsung Galaxy S8 and Samsung Galaxy S7 Edge.

**Comment by chaosemer** [comment]
Sorry about this. This is a known issue with the developer preview.

**Comment by Crashthatch** [comment]
Is there a workaround / way to detect or catch this?

"Atom Visualizer" (an app I installed through Google Play) gives me an error "Google ARCore Service is not installed" when I try to launch it, so it must be possible?

logcat logs:

`12-06 16:47:06.309  3710  5315 V WindowManager: Relayout Window{35a5e87d0 u0 com.arrowsd.whatsonthehorizon/com.unity3d.player.UnityPlayerActivity}: viewVisibility=0 req=2220x1080 WM.LayoutParams{(0,0)
(fillxfill) sim=#20 ty=1 fl=#81e90580 pfl=0x20000 fmt=-3 wanim=0x103046c vsysui=0x1716 needsMenuKey=2 naviIconColor=0}
12-06 16:47:06.320 26375 26375 D ViewRootImpl@92a5df[UnityPlayerActivity]: Relayout returned: oldFrame=[0,0][2220,1080] newFrame=[0,0][2220,1080] result=0x1 surface={isValid=true -551716864} surfaceGe
nerationChanged=false
12-06 16:47:06.327 26375 26398 F tango   : jni_helper.cc:19 'vm' Must be non NULL
--------- beginning of crash
12-06 16:47:06.327 26375 26398 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 26398 (UnityMain)
12-06 16:47:06.331  3127  3127 W         : debuggerd: handling request: pid=26375 uid=10325 gid=10325 tid=26398
12-06 16:47:06.441 26489 26489 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-06 16:47:06.442 26489 26489 F DEBUG   : Build fingerprint: 'samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQJ5:user/release-keys'
12-06 16:47:06.442 26489 26489 F DEBUG   : Revision: '10'
12-06 16:47:06.442 26489 26489 F DEBUG   : ABI: 'arm'
12-06 16:47:06.442 26489 26489 F DEBUG   : pid: 26375, tid: 26398, name: UnityMain  >>> com.arrowsd.whatsonthehorizon <<<
12-06 16:47:06.442 26489 26489 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-06 16:47:06.449 26489 26489 F DEBUG   : Abort message: 'jni_helper.cc:19 'vm' Must be non NULL'
12-06 16:47:06.450 26489 26489 F DEBUG   :     r0 00000000  r1 0000671e  r2 00000006  r3 00000008
12-06 16:47:06.450 26489 26489 F DEBUG   :     r4 d07ff978  r5 00000006  r6 d07ff920  r7 0000010c
12-06 16:47:06.450 26489 26489 F DEBUG   :     r8 d07fddb0  r9 d07fddac  sl 00000515  fp d07fe0c0
12-06 16:47:06.450 26489 26489 F DEBUG   :     ip 00000014  sp d07fd930  lr f0ca3f97  pc f0ca67f4  cpsr 200f0010
12-06 16:47:06.459 26489 26489 F DEBUG   :
12-06 16:47:06.459 26489 26489 F DEBUG   : backtrace:
12-06 16:47:06.459 26489 26489 F DEBUG   :     #00 pc 0004a7f4  /system/lib/libc.so (tgkill+12)
12-06 16:47:06.459 26489 26489 F DEBUG   :     #01 pc 00047f93  /system/lib/libc.so (pthread_kill+34)
12-06 16:47:06.459 26489 26489 F DEBUG   :     #02 pc 0001daad  /system/lib/libc.so (raise+10)
12-06 16:47:06.459 26489 26489 F DEBUG   :     #03 pc 00019231  /system/lib/libc.so (__libc_android_abort+34)
12-06 16:47:06.459 26489 26489 F DEBUG   :     #04 pc 0001714c  /system/lib/libc.so (abort+4)
12-06 16:47:06.460 26489 26489 F DEBUG   :     #05 pc 000058f9  /system/lib/liblog.so (__android_log_assert+112)
12-06 16:47:06.460 26489 26489 F DEBUG   :     #06 pc 00009e69  /data/app/com.arrowsd.whatsonthehorizon-1/lib/arm/libtango_client_api2.so
12-06 16:47:06.460 26489 26489 F DEBUG   :     #07 pc 0001256d  /data/app/com.arrowsd.whatsonthehorizon-1/lib/arm/libtango_client_api2.so
12-06 16:47:06.460 26489 26489 F DEBUG   :     #08 pc 00009247  /data/app/com.arrowsd.whatsonthehorizon-1/lib/arm/libtango_client_api2.so (TangoService_isSupported+26)
12-06 16:47:06.460 26489 26489 F DEBUG   :     #09 pc 00002eac  <anonymous:ca3c0000>`

**Comment by chaosemer** [comment]
This should now be resolved in Developer Preview 2. Please reopen if you still are having issues.
