### ISSUE TITLE
Instant Preview Close Unity after some seconds

### ISSUE THREAD

**Issue by gfreisz** [google-ar/arcore-unity-sdk#430]
Hi, 

I'm trying to use arcore instant preview via wirelless connection but after some seconds, unity close unespected. 

I'm using:
Unity version: 2018.2.10f1 pro
ArCore: 1.5
Windows 7
Samsung A8+ (2018)
Connection type: wirelless 
Project: HelloAR that comes inside .unitypackage

Also, i can't USB type because always say "Not Connect to Editor"

Thanks!

**Comment by chaosemer** [comment]
I was unable to reproduce your issue. A handful of major bugs in Instant Preview are getting fixed in ARCore 1.6, please reopen this if this issue still persists.

**Comment by fredsa** [comment]
If you still have issues with the 1.6.0 SDK, feel free to file a new issue.

**Comment by fredsa** [comment]
Marking as fixed.
