### ISSUE TITLE
Multiple Cloud Anchors In a single room

### ISSUE THREAD

**Issue by radhakrishna2014** [google-ar/arcore-unity-sdk#432]
The file RoomSharingServer.cs consists of : 
private Dictionary<int, XPAnchor> m_RoomAnchorsDict = new Dictionary<int, XPAnchor>();
which restricts to create only one anchor in one room as it needs to be unique. When we try to assign multiple anchors the app crashes, so I have tried to change the type dictionary, but the resolver faces the problem. Can there be any way to host multiple anchors in a single room?

**Comment by radhakrishna2014** [comment]
Thanks for the response @pablisho. Let me explain my case, I am trying to host two andy objects in a single room. I have taken 2 touch inputs and for the first touch input, I placed an anchor and first andy object on it. Now, when the second touch is made, I am not trying to create another anchor, but just recording the touch position and placing second andy object on it. And in the end, I am placing the anchor which is created for the first touch as a parent to second. Now when I am trying to resolve only one andy object is resolved.

**Comment by abudriaz** [comment]
> Hi, you can host as many cloud anchors as you wish. The "room" concept is something that allows the example to map the room number to the cloudAnchorId, so you can modify that logic to support multiple ones or use different numbers for each anchor. Let me know if this helps.

how to have multiple anchors can anyone of you share the code? :/

**Comment by chaosemer** [comment]
We generally don't recommend having multiple anchors in a single (physical) room as a single anchor is sufficient. We're updating our Cloud Anchor sample in a future release to show how to use Cloud Anchors to place multiple objects.

**Comment by radhakrishna2014** [comment]
Thanks chaosmer. Will close the issue.
