### ISSUE TITLE
ARCore Camera FOV

### ISSUE THREAD

**Issue by AbdullahBurhan** [google-ar/arcore-unity-sdk#434]
I am trying to control the field of view of the ARCore camera in unity, and according to the test I did,
the camera FOV cannot be changed when the app is running on my device. the question is 
1. How the camera FOV is being controlled?
2. How can I change the camera FOV at runtime?

**Comment by chaosemer** [comment]
The FOV of the camera is set to line up with the virtual camera's FOV. This is critical for good AR as it enables virtual objects to appear to stick to a point in the real world.

I'm curious, what effect are you trying to enable?

**Comment by AbdullahBurhan** [comment]
in my case, I am making a car simulation in AR and what I noticed is that when the car is getting far away from the camera it looks much smaller comparing to real physical cars that are near it, so my virtual car seems unrealistic,
and I think that happens because the FOV of the AR camera in unity that renders the virtual objects is not identical to the FOV of the physical camera that renders the background.
so I am really curious to know more about this topic, to solve my problem.

**Comment by small-potatoes** [comment]
Hi AbdullahBurhan@, this should not be the case.  If you would like us to take a look at the issue you could send us a simple repro project placing your car X meters away on a plane and give us the model of the device you are seeing this issue on.
