### ISSUE TITLE
CloudAnchor  ip address no correct

### ISSUE THREAD

**Issue by moishi** [google-ar/arcore-unity-sdk#435]
in sumple GoogleARCore > Examples > CloudAnchor > Scenes, if my device on wifi,  the ip address appear such ip of Mobile operator, not of wifi, This causes an error connecting devices, is dependence from CloudAnchorUIController.cs function culled _GetDeviceIpAddress.

**Comment by HandyP94** [comment]
Are you on Android or iOS? On Android this methods for aquiring the IP address works for me, but it doesn't on iOS. If you're on iOS try following [this tutorial](https://richardstechnotes.com/2018/07/20/accessing-the-ios-wifi-ip-address-within-a-unity-app/) to create a small plugin, that helps you get the correct IP address for the WIFI.

**Comment by HandyP94** [comment]
Weird. I'm using basically the same code on a Pixel 2 and I get the correct IP address.

**Comment by moishi** [comment]
Maybe it's a matter of definitions?

**Comment by chaosemer** [comment]
We're improving our Cloud Anchor sample in an upcoming release which will simplify this logic.

**Comment by kolboch** [comment]
@HandyP94 btw, I could not find answer in the web, can I build application using ARCore for iOS devices ? Thanks for response in advance

**Comment by moishi** [comment]
yes, in new devices have arcore support

‫בתאריך יום ה׳, 22 בנוב׳ 2018 ב-0:10 מאת ‪Karol‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by HandyP94** [comment]
@kolboch ARCore on iOS can only be used to host or resolve CloudAnchors. ARKit is still required for all the AR functionality like plane detection and placing anchors.

**Comment by tedruxpin** [comment]
Please take a look at the new sample in the ARCore 1.6 release.
