### ISSUE TITLE
Point cloud visualizer does not work during instant preview

### ISSUE THREAD

**Issue by alikanat001** [google-ar/arcore-unity-sdk#437]
Hi,

Sorry if i am missing something and asking a stupid question but i was really curious about the issue. I downloaded ARCore 1.5.0 package and checking HelloAR sample. When i hit play in editor i can see planes, instantiate blue and green andy objects with hit test but can not see feature points or the point cloud. Even though i can see them in scene view they are not visualized in game view or on my phone. However, if i build and run HelloAR on my phone i can see the feature points everything works fine. I have a Samsung Galaxy s8 device.

**Comment by chaosemer** [comment]
Instant Preview does not support point cloud points at this point in time. Sorry!

**Comment by alikanat001** [comment]
Ah sorry i did not know it is not supported. Thanks for the reply.

**Comment by fredsa** [comment]
Duplicate of #484

**Comment by fredsa** [comment]
Correction, I just tried the 1.5.0 and 1.6.0 SDKs and find that the point cloud is visualized in Instant Preview.
