### ISSUE TITLE
augmented_image_cli hangs when using uppercase file extensions — gives the message "Calculating..." but never shows final score

### ISSUE THREAD

**Issue by synthercat** [google-ar/arcore-unity-sdk#439]
I tried adding 5 images to a DB. One of them is a .PNG file (that uses alpha channel)
It's the only image that goes to page-2 of the DB. It's score is never revealed.

**Comment by ananthaks** [comment]
I am facing a similar issue. However, after some experimentation, I found that if the file ends in ".png" as opposed to ".PNG", the score gets calculated.

**Comment by fredsa** [comment]
Thanks for the report. Confirmed this is an issue in 1.6.0 SDK.

Best workaround for now is to make sure your filenames use lowercase extensions.

**Comment by small-potatoes** [comment]
This has been fixed in the [ARCore SDK for Unity version 1.7](https://github.com/google-ar/arcore-unity-sdk/releases) release.
