### ISSUE TITLE
resolving arcore cloud in new session

### ISSUE THREAD

**Issue by abudriaz** [google-ar/arcore-unity-sdk#443]
iam not being able to resolve the already saved cloud anchor after closing and reopening the app any help for this?

**Comment by chaosemer** [comment]
We are improving the Cloud Anchor example in an upcoming release, which should make it much clearer how to do this type of thing.

**Comment by small-potatoes** [comment]
Please take a look at the [ARCore 1.6 release](https://github.com/google-ar/arcore-unity-sdk/releases) for which this is fixed.
