### ISSUE TITLE
Feature Detector & Descriptor

### ISSUE THREAD

**Issue by markusfehr** [google-ar/arcore-unity-sdk#448]
Is it possible to let us know which feature detector ARCore use for the point detection? SIFT, SURF, ORB, FAST, BRIEF, BRISK or another one? And which descriptor is used? And is it possible (in the near future) to get access to the descriptor data?

**Comment by chaosemer** [comment]
We have tuned our algorithm for detecting features significantly, it is not just an off the shelf feature detector. We have no plans to expose the raw feature descriptors and will instead be exposing higher level concepts like Anchors, Planes, Images, and so on.
