### ISSUE TITLE
InstantPreview not work pixel3

### ISSUE THREAD

**Issue by azukizuki** [google-ar/arcore-unity-sdk#450]
When trying to use InstantPreview with Pixel 3, only the message "Searching for surface ..." is displayed on the white screen. I am running in example HelloAR scene.

SDK Version 1.5
Unity 2018.2.16f1

https://github.com/google-ar/arcore-unity-sdk/issues/357
It is written that this issue solved with 1.5, but it will be reproduced in my environment

It is a related log,

>  ARCoreUpdateManager: onSurfaceAvailable
11-19 17:55:20.424 14632 14711 I ARCoreUpdateManager: surface received.
11-19 17:55:20.425 14632 14711 I ARCoreUpdateManager: setSurface
11-19 17:55:20.492 14632 14711 E native  : status.cc:155 ArStatusErrorSpace::AR_ERROR_NOT_YET_AVAILABLE:
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: missed a cpu image
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: com.google.ar.core.exceptions.NotYetAvailableException
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:102)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.Frame.nativeAcquireCameraImage(Native Method)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.Frame.acquireCameraImage(Unknown Source:6)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager.sessionProc(ARCoreUpdateManager.java:135)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager.bridge$lambda$0$ARCoreUpdateManager(Unknown Source:0)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager$$Lambda$0.run(Unknown Source:2)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-19 17:55:20.493 14632 14711 W ARCoreUpdateManager: 	at java.lang.Thread.run(Thread.java:764)

>  ActivityManager: Activity pause timeout for ActivityRecord{62c2ccb u0 com.google.ar.core.instantpreview/.InstantPreviewLandscapeActivity t172}
11-19 17:53:32.899  8874  8921 I chatty  : uid=10162(com.google.ar.core.instantpreview) expire 230 lines
11-19 17:53:32.921  8874  8917 I com.google.ar.core.instantpreview.Decoder: releaseOutputSurfaceAndStop
11-19 17:53:32.921  8874  8874 W System.err: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager.onPause(ARCoreUpdateManager.java:55)
11-19 17:53:32.922  8874  8874 W System.err: 	at com.google.ar.core.instantpreview.InstantPreviewActivity.onPause(InstantPreviewActivity.java:603)
11-19 17:53:32.923  8874  8954 W System.err: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager.sessionProc(ARCoreUpdateManager.java:106)
11-19 17:53:32.923  8874  8954 W System.err: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager.bridge$lambda$0$ARCoreUpdateManager(Unknown Source:0)
11-19 17:53:32.923  8874  8954 W System.err: 	at com.google.ar.core.instantpreview.ARCoreUpdateManager$$Lambda$0.run(Unknown Source:2)
11-19 17:53:47.391   867   867 I Camera2ClientBase: Closed Camera 0. Client was: com.google.ar.core.instantpreview (PID 8874, UID 10162)

thank you

**Comment by chaosemer** [comment]
Thanks for the bug report. I'm looking into it.

**Comment by azukizuki** [comment]
It worked properly with version 1.6. Thank you !!

**Comment by fredsa** [comment]
Fixed in ARCore for Unity SDK 1.6.0
