### ISSUE TITLE
cloud anchor scale difference

### ISSUE THREAD

**Issue by flankechen** [google-ar/arcore-unity-sdk#457]
After host and resolve cloud anchor, attached object shows scale difference, position and rotation drift some times. 
I know it's quite difficult for a SLAM system to relocalize from different angle. Position and rotation drift maybe normal.
But for scale difference, it should be very stable for a mono and imu system, like arcore based ar ruler.

Any suggestion and discussion is welcome.

**Comment by chaosemer** [comment]
We have improved our Cloud Anchor sample to work better with Unity. I believe it will make it clearer how to keep the object's position synchronized.
