### ISSUE TITLE
Application crashes while trying to run ARCore and then Tensorflow Lite

### ISSUE THREAD

**Issue by chetu3319** [google-ar/arcore-unity-sdk#459]
Hi community, 
I'm working on an application which requires to change the camera from back camera to selfie camera, and run tensorflow Lite. For this the workflow adopted is as : 
- Start the scene
- Use ARCore 
- On Switch : Disable ARCore session by disabling the scripts -> enable front camera
- After waiting for Front camera feed, initialise tensorflow lite.  **Here the Applicaiton is Crashing down**

The application wroks properly if there is only ARCore, or if there is only TensorflowLite. Both together or even toggling them one after another is crashing the application. 

Any suggestion here will be appriciated. 

Thank you
Chaitnaya

ARCore Version : ARCoreSDK For Unity 1.5.0
Unity Version : Unity 2018.1.0f2
Tensorflow Lite: Experimental SDK build from the removed github repo. 

> Both the projects, seperatly built are working properly. But not together.

**Comment by fredsa** [comment]
Suggest reviewing `adb logcat` output to see what the cause of the crash is.
