### ISSUE TITLE
Augmented Images not supported in editor even though I don't use them

### ISSUE THREAD

**Issue by githubcatw** [google-ar/arcore-unity-sdk#465]
Hi.
I am creating an AR app.
I use Instant Preview to quickly test changes and identify errors.
Recently ARCore decided to update, and Instant Preview was broken. I updated the SDK in my project, but now get a warning that Augmented Images are not supportedin the editor. The problem is that I use ARCore for markerless tracking. Is there a way to get rid of the Augmented Images error?

**Comment by fredsa** [comment]
I think you mean the warning that is currently output by `AugmentedImageDatabaseApi`:

>             if (Application.isEditor)
>             {
>                 Debug.LogWarning("Augmented Images not supported in editor.\n" +
>                                  "To test your app, build and run on device.");
>             }
> 

If you avoid using this class, the warning should not appear. If you find the reminder warning a distraction, feel free to comment out in your project. Either way, this should not affect building and running your app on device.

**Comment by fredsa** [comment]
This will most likely be fixed by adding Augmented Images support to Instant Preview (issue #403).
