### ISSUE TITLE
Plane change material when object gets instantiate

### ISSUE THREAD

**Issue by platinio** [google-ar/arcore-unity-sdk#466]
Hi guys first sorry for my bad english, but today i am facing a really strange problem.

I am using unity 2018.2.10f1, the latest version of ARCore, and a Nokia 6.1 for testing.

So the steps to reproduce are really simple:
1) import the last version of ARCore
2) Open helloAR
3) In HelloARController change both Andy prefabs, for this model https://www.turbosquid.com/FullPreview/Index.cfm/ID/587372 a .t3d
4) build and spawn 2 objects and maybe you can get some like this pic

![screenshot_20181208-192705](https://user-images.githubusercontent.com/20730539/49691428-b93b5a00-fb20-11e8-8fb7-4ac07e9fd9ac.png)

it looks like there are many beers but there are just 2

if i try using a fbx model, it works as expected, so this is strange, i am missing something here?

Thanks for take you time to read, have a good day!

**Comment by fredsa** [comment]
This looks like it's either an issue with the 3D assets, or with the way that it's imported by Unity.

I don't think this is ARCore related, so closing for now. Can you try the same model in a Unity project without ARCore?
