### ISSUE TITLE
Stick objects when camera cover up

### ISSUE THREAD

**Issue by dmitrijnedopekin** [google-ar/arcore-unity-sdk#467]
### SPECIFIC ISSUE ENCOUNTERED

I placed some object to scene by static coordinate (coordinates don`t changing). When user cover up camera by chance or camera located near some objects (wall, table etc.) - i get "frozen" scene. (Scene moving with device (Objects sticked to camera))

Any help would be appreciated.

If you need more details, feel free to ask.

### VERSIONS USED
- Unity: 2017.4.6f1 
- ARCore SDK for Unity: v1.6
- Device manufacturer, model, and O/S:  Testing on Pixel 2 

### STEPS TO REPRODUCE THE ISSUE
 1. Place some primitive on scene
 2. Run app
 3. Find object in space
 4. Cover up camera
 5. Moving device with covered camera

**Comment by fredsa** [comment]
Please use anchors to place virtual assets in the scene. This ensures that they maintain their position in space as ARCore updates it's understanding of the world.

**Comment by vacoup95** [comment]
I have the same issue and I am using anchors.
