### ISSUE TITLE
Gradle builds can't access Tango libraries

### ISSUE THREAD

**Issue by kenny-uken** [google-ar/arcore-unity-sdk#47]
We're developing an ARCore mode as part of an existing game and adding the new java libs have hit the dex limit, forcing us to transition to building with Gradle. Unfortunately, it seems our Gradle builds can't find the "tango_client_api2" library that is installed separately with the arcore-preview APK. I've verified that the same project built with the standard build method doesn't have this issue; to get it to build without Gradle I had to remove a number of java libs that we can't ship without. Is there something I need to configure with Gradle to make it recognize those libs?

```
DllNotFoundException: tango_client_api2
GoogleARCoreInternal.TangoClientApi.CallsToConnectWithoutMatchingDisconnect () (at /Users/kenny/pool-unity/Assets/KingsOfPool/Features/AR/GoogleARCore/SDK/Scripts/Api/TangoClientApi.cs:130)
GoogleARCore.SessionComponent+<_AttemptRecoverIfInvalidState>c__Iterator0.MoveNext () (at /Users/kenny/pool-unity/Assets/KingsOfPool/Features/AR/GoogleARCore/SDK/Scripts/SessionComponent.cs:306)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
```

**Comment by chaosemer** [comment]
That sounds like a bug in Unity. Please report the bug to them as described here: https://unity3d.com/unity/qa/bug-reporting.

**Comment by kenny-uken** [comment]
When the ARCore SDK reaches 1.0, will users still have to manually download a separate APK with the tango libs in it? It's been my assumption that it's definitely not the case but I wanted to make sure. I suspect this wouldn't be an issue if not for the separate install of the libs that the game is trying to find at runtime.

**Comment by chaosemer** [comment]
We still need to have a services APK so that you don't end up with multiple copies of the ARCore libraries on your phone. But it won't be Tango, it'll be ARCore.

**Comment by rasmusblockzero** [comment]
@kenny-uken did you find a solution here? I'm trying to run the Unity Sample ARCore apps (on a ARCore but not Tango friendly device S8) and running into this.

**Comment by chaosemer** [comment]
If you're still running into an issue about "tango_client_api2", then you must still be on the original Developer Preview. Do you still have issues on Developer Preview 2?

**Comment by rasmusblockzero** [comment]
@chaosemer Thank you! I was on the Preview2, in my case the issue was an old unity version.

**Comment by kenny-uken** [comment]
I haven't been able to test because Preview 2 requires us to upgrade to 2017.3. 2017.3 drops support of ADT builds, and we had some kind of special set up to allow us to do multidex builds via that method (honestly doesn't make much sense to me because we were ultimately using gradle to make the build). The new gradle builds won't work at all for reasons unrelated to ARCore or Tango.

**Comment by chaosemer** [comment]
@kenny-uken, that's a shame. Unfortunately, we rely on hooks provided by 2017.3 to get access to low level Android events that are needed by DP2. You'll need to upgrade to 2017.3 to continue using ARCore.

**Comment by kenny-uken** [comment]
The build no longer crashes now... it seems to fail to connect the session on startup but this is also an issue when not using gradle and NOT an issue when building and running the HelloAR demo, so I would hesitantly consider this issue resolved.

**Comment by ufktvfk** [comment]
@kenny-uken Hi, how did you manage to get around this issue? I am having the same issue when I import my Unity ARCore project to Android studio as .aar library and open this Unity ARCore project inside my native android app. The log message is the same.

**Comment by kenny-uken** [comment]
I'm not sure if I'm doing exactly what you're doing, but this is what I'm doing now:

- Upgrade to ARCore Preview 2 (and install the new .apk on your device)
- Upgrade Unity to 2017.3.0p1 (newer than 2017.3.0f3)
- Set the Android build method to "Gradle"
- Uncheck "Export"
- Disable ProGuard by choosing "None" for all of the "Minify" options in Player Settings. It seems to be angry about some amazon payment libraries in UnityPurchasing that we don't even use.
- If you need multidex support, which is the whole reason we're using Gradle at all, check "Custom Gradle Template" and in the mainTemplate.gradle file that gets generated add "multiDexEnabled true" to "defaultConfig" and "compile 'com.android.support:multidex:1.0.1'" to "dependencies". The latter is required for supporting pre-Lollipop Android versions.
- If the build fails due to not having Gradle 2.1.0, change "classpath 'com.android.tools.build:gradle:2.1.0'" in mainTemplate.gradle to "classpath 'com.android.tools.build:gradle:2.3.0'" (don't ask me why 2.3.0 will magically make later gradle versions work, too)

**Comment by ufktvfk** [comment]
I am actually trying to embed my unity ARCore project within my native android app following steps in this tutorial: https://medium.com/@davidbeloosesky/embedded-unity-within-android-app-7061f4f473a.

I managed to open my unity project inside my native android app but it opens I get blue screen which means arcore session is not initialized. Here is the log message:`DllNotFoundException: tango_client_api2
                                                                 at (wrapper managed-to-native) GoogleARCoreInternal.TangoClientApi/ExternApi:CallsToConnectWithoutMatchingDisconnect ()
                                                               at GoogleARCoreInternal.TangoClientApi.CallsToConnectWithoutMatchingDisconnect () [0x00000] in <filename unknown>:0 
                                                               at GoogleARCore.SessionComponent+<AttemptRecoverIfInvalidState>c_Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
                                                               at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
                                                             UnityEngine.MonoBehaviour:StartCoroutine_Auto_Internal(IEnumerator)
                                                             UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
                                                             GoogleARCore.SessionComponent:Awake()`
So I will try your steps and let you know.Thanks

**Comment by ufktvfk** [comment]
Do we need to work with Android Studio 3.0+ ? Since Android Studio 3.0+ is suggested as development environment as described here: https://developers.google.com/ar/develop/java/getting-started
