### ISSUE TITLE
No option to switch connection type for instant preview on mirage solo.

### ISSUE THREAD

**Issue by sniejadlik** [google-ar/arcore-unity-sdk#472]
Trying to activate Instant Preview over Wifi on the Lenovo Mirage Solo does not provide the drop down interface to select connection type.  The interface says to hit the x button on the phone but the solo has no interface for that command.  So it never shows the connection drop down.  This was not a big issue until the new tracker interface requires the usb port to be occupied to supply power.  This means that I cannot have the headset plugged into my computer for previewing.  Please add the drop down for connection type to the instant preview main interface instead of having it as a part of the non VR screen.

### VERSIONS USED
- Unity: 2018.2.18f
- ARCore SDK for Unity: 
- Device manufacturer, model, and O/S: Lenovo Mirage Solo running latest patch OVR1.181126.005

### STEPS TO REPRODUCE THE ISSUE
 1. launch unity with instant preview app on device
 1. pause unity playback
 1. interface prompts to hit x button on device to switch conneciton modes (there is no physical or software x button)

### WORKAROUNDS (IF ANY)
none

### ADDITIONAL COMMENTS
This is necessary to build and debug with the new experimental interface.  Please provide a fix asap.

**Comment by fredsa** [comment]
This sounds related to the Google VR SDK:
https://github.com/googlevr/gvr-unity-sdk
