### ISSUE TITLE
POCO F1 Ar issue

### ISSUE THREAD

**Issue by thapliyalshivam** [google-ar/arcore-unity-sdk#473]
I am using unity and ARCORE to test Sample test HelloAr scene from codelaps.
Unfortunately, it always shows
"Failure to initialize!
your hardware doesn not support this application."
I have also downloaded ARcore from app store and tried everything.
any help would be appreciated.

**Comment by thapliyalshivam** [comment]
@tyrroncondo14  I updated my unity editor and that resolved my problem. Make sure you update it.
Also, make sure you update ARcore from play store. Hope this helps.

**Comment by tyrroncondo14** [comment]
@thapliyalshivam  It works! Thanks a lot dude!
