### ISSUE TITLE
ArDemo App Craches on Modded Mi 6

### ISSUE THREAD

**Issue by junglee372018** [google-ar/arcore-unity-sdk#475]
I have modded the Mi 6 and installed arcore sdk from playstore.

But when i make a build and execute it in the Mi6, I am always getting"Arcore could not connect" error and app craches.

Please help me out.

kindly waiting for your reply

**Comment by fredsa** [comment]
Please use only ARCore Supported Devices:
https://developers.google.com/ar/discover/supported-devices
