### ISSUE TITLE
Problem with CameraClearFlags.Depth

### ISSUE THREAD

**Issue by perceval1190** [google-ar/arcore-unity-sdk#476]
### SPECIFIC ISSUE ENCOUNTERED
I try to use Arcore with cardboard.
When I setup the camera to CameraClearFlags.Depth, I have duplicated images

### VERSIONS USED
- Unity: 2018.3.0f2
- ARCore SDK for Unity: 1.6
- Device manufacturer, model, and O/S: galaxy S8, Android 8.1

### STEPS TO REPRODUCE THE ISSUE
 1.On fist person camera remove ARCoreBackgroundRenderer script
 2.Player settings - Virtual reality supported - (cardboard or oculus) 
 3.Set fist person camera - Clear Flags to depth only.
 4. Build and run android

**Comment by ThatChocolateGuy** [comment]
I'm also interested in using ARCore passthrough with Mobile VR. Please let us know what you find!

**Comment by fredsa** [comment]
Unfortunately VR is not a supported use case. Closing for now.
