### ISSUE TITLE
PointCloudPoint ID - what is it for

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-unity-sdk#482]
I have a question about PointCloudPoint ID as I have noticed that PointCloudPoints are not persistent within frame updates - with new Frame.PointCloud.IsUpdatedThisFrame interval, new PointCloudPoints with new ID's come in, is this intended behaviour? Should they not persist from frame to frame if they are "old ones"?

I have a dictionary with ID's and when the ID is already in dictionary then it should update the CloudPointView I have created, but the PointCloudPoint with the same ID actually never comes in even in Runtime (I know that ID's are currently not supported in editor).

```

private Dictionary<int, CloudPointView> idViewDictionary;

    private void Awake()
    {
        idViewDictionary = new Dictionary<int, CloudPointView>();
    }

    private void Update()
    {
        if (Frame.PointCloud.IsUpdatedThisFrame)
        {
            UpdateCloudPoints();
        }
    }

    private void UpdateCloudPoints()
    {
        int cloudPointsCount = Frame.PointCloud.PointCount;

        for (int i = 0; i < cloudPointsCount; i++)
        {
            PointCloudPoint cloudPoint = Frame.PointCloud.GetPointAsStruct(i);

if !UNITY_EDITOR
            if (cloudPoint.Id == PointCloudPoint.InvalidPointId) continue;
endif


if !UNITY_EDITOR
                if (idViewDictionary.ContainsKey(cloudPoint.Id))
                {
                    print("Contains ID " + cloudPoint.Id + ". Updating");
                    idViewDictionary[cloudPoint.Id].UpdateView(cloudPoint);
                }
                else
                {
endif
            if (cloudPoint.Confidence > 0.75f)
            {
                CloudPointView cloudPointView = Instantiate(cloudPointViewPrefab);
                cloudPointView.SetUpView(cloudPoint);
            }
if !UNITY_EDITOR
                }
endif
        }
    }
```

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Unity version
- ARCore SDK for Unity version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`
