### ISSUE TITLE
Can we use arcore anchor with hololens ?

### ISSUE THREAD

**Issue by nandantal** [google-ar/arcore-unity-sdk#485]
Is there any way to use arcore with hololens ?Also can we use cloud anchor with hololens ?

**Comment by MohsenneChaverdie** [comment]
As far as I know, no. HoloLens has its own anchor sharing mechanics that works only between Mixed Reality Devices.

**Comment by fredsa** [comment]
HoloLens is not supported. List of supported devices can be found here:
https://developers.google.com/ar/discover/supported-devices
