### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#49]
Is there anyway to use autofocus? This is to do additional detection and CV work, but the resolution is quite poor without autofocus

**Comment by chaosemer** [comment]
The ARCore camera focal distance is set to a fixed focus tuned for motion tracking. There is not an API that  allows you to adjust the focus as that would impact the tracking quality. Sorry!

**Comment by iBicha** [comment]
Makes sense, I think it should be possible in theory, to work with a variable focal length, but I have no idea where to go from here. I'll close this for now, feel free to open it back up if there are new leads. Thanks!

**Comment by stefanseibert** [comment]
+1 for implementing this feature in a future release. We try to work on enhancing ARCore to be able to use custom tracking markers, it is hard to do computer vision on the unfocused imagery.

**Comment by achuvm** [comment]
Now that ARCore 1.2 has AugmentedImage support (Image Recognition), was this added to the API?

https://developers.google.com/ar/reference/c/group/augmented-image

**Comment by ZeroLu** [comment]
+1 Would be really great to have auto focus(or tap to focus) and improve the image quality to 1080p, just like ARKit.

**Comment by re-cheid** [comment]
+1 
We are trying to detect certain features, but we are currently very limited in terms of the feature's size and detail level, which makes it unusable for our use case.

**Comment by breiting** [comment]
That is an urgent issue, please fix it. Detecting codes is currently not possible with ARCore

**Comment by Terked** [comment]
+1 auto-focus (or tap to focus) would greatly increase the tracking quality that we need in our app

**Comment by dvlee1024** [comment]
+1 auto-focus.  the quality of  backgroundimage is not good enough. It has an influence on my  image processing

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity v1.4.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.0) has been released and [Autofocus](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/ARCoreSessionConfig.cs#L77) has been added to it.

**Comment by gurujeya14** [comment]
[This](https://stackoverflow.com/a/56540497/5858147) comment might be useful to set auto-focus mode in camera.
