### ISSUE TITLE
Session.CheckApkAvailability() wrongly returns ApkAvailabilityStatus.SupportedNotInstalled

### ISSUE THREAD

**Issue by AllBecomesGood** [google-ar/arcore-unity-sdk#490]
Since the last issue was closed without a fix and there was no answer in 10 days I am thinking it might've went under the radar. Here's the link to the unresolved issue:
https://github.com/google-ar/arcore-unity-sdk/issues/428

Sorry if you are on to this and I'm just creating spam.

**Comment by fredsa** [comment]
Thanks for the followup. If you're still experiencing issues:

1. Please check that your device is in fact listed as an [ARCore Supported Devices](https://developers.google.com/ar/discover/supported-devices)
2. Make sure that your device is running the minimum required version of Android
3. Your device has a working internet connection

If `Session.CheckApkAvailability()` still returns `ApkAvailabilityStatus.SupportedNotInstalled`, please create a new issue, and include the requested information, including device fingerprint (`adb shell getprop ro.build.fingerprint`).
