### ISSUE TITLE
CloudAnchor Unity : The replaced prefab only renders in Host

### ISSUE THREAD

**Issue by richard5635** [google-ar/arcore-unity-sdk#493]
### SPECIFIC ISSUE ENCOUNTERED
Hi, I am having issues with CloudAnchor Unity. I tried replacing the default Star prefab with my own model (I tried two different ones, made sure they are small enough and are in the origin), but they seem to only render in the host. I tried spawning from the client, but the object also renders only in the host. The client stays empty. Is there anything I did wrong?

Here is the screenshot for the issue.
https://drive.google.com/open?id=1knE50gGwafoXYG26folIwmZn-65nvLc4

Thanks!

### VERSIONS USED
- Unity: 2018.3.1f1
- ARCore SDK for Unity:  1.6.0
- Device manufacturer, model, and O/S: Huawei PAR-LX9, Samsung Galaxy S8
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Replace the Star prefab in LocalPlayerController Component inside the Player prefab 
 1. Build CloudAnchor to both devices and try spawning the prefab after the anchor has been placed
 1.

**Comment by julianmateu** [comment]
Did you add a [`NetworkIdentity`](https://docs.unity3d.com/Manual/class-NetworkIdentity.html) component to your prefab? Did you register it in the [`NetworkManager`](https://docs.unity3d.com/Manual/UNetManager.html) game object in the scene as a Spawnable Prefab? Take a look to the [Unity Manual](https://docs.unity3d.com/Manual/UNetOverview.html) documentation for more info.

Hope this helps.
