### ISSUE TITLE
Static Variable does not get changed

### ISSUE THREAD

**Issue by reubenkcoutinho** [google-ar/arcore-unity-sdk#5]
I've created a static bool variable isCreated to check if the Andy prefab is created.

In the following check 
`if (Session.Raycast (m_firstPersonCamera.ScreenPointToRay (touch.position), raycastFilter, out hit))` , I've set the variable to be true and then put another check here 
```
if (Input.touchCount < 1 || (touch = Input.GetTouch (0)).phase != TouchPhase.Began || isCreated) {
					return;
				}
```

But for some reason, the variable is never gets set to true. 
I've also notice [this error](https://github.com/google-ar/arcore-unity-sdk/issues/3) in the logs, and can't help but wonder if it somehow prevents it from getting set.

**Comment by nathanmartz** [comment]
It looks like a bug in your code. I think you want touch == Input in that second block of code. Right now you are assigning to it,  not checking it.

**Comment by reubenkcoutinho** [comment]
@nathanmartz , you'll notice that the assignment is `(touch = Input.GetTouch (0)).phase != TouchPhase.Began`

**Comment by jguomoto** [comment]
Where are you setting `isCreated` to false? From looking at the code, it will only work for the first touch. 

Also, if `Input.touchCount < 1` is done after `Session.Raycast`, how do you know `touch.position` is not a null? 

I think it might be easier to follow the [sample code's logic](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/HelloARExample/Scripts/HelloARController.cs#L123) to detect touch.

**Comment by reubenkcoutinho** [comment]
@jguomoto I have modified the same script.

**Comment by small-potatoes** [comment]
Hi Reuben,

I took your example script, commented out lines relating to the "info" variable, compiled and ran it.  The result was logging worked as expected and set your static variable.  My theory: you did not attach the Text element to ExampleController GameObject.  But that is just a guess; in any case, I think there is not a problem with the ARCore SDK here.  You might also try a fresh project and retracing your steps.  I hope that helps.

-Matt

**Comment by reubenkcoutinho** [comment]
Hi Matt ( @small-potatoes ),
I removed the info variable, but it still does not work as expected. Note that I am using a Pixel XL. What device did you use?
