### ISSUE TITLE
Render with update mode "BLOCKING"

### ISSUE THREAD

**Issue by henningboat** [google-ar/arcore-unity-sdk#50]
Is it possible to change the update mode of the session to "BLOCKING", to only update ones a new camera image is ready, as described in the [ARCore Android SDK documentation](https://developers.google.com/ar/reference/java/com/google/ar/core/Config.UpdateMode)? 
I am curious to try out how this would affect game feel.

**Comment by jguomoto** [comment]
Now we release DP2 with both options available in Unity. If you would like to have AR (pose tracking + color camera), you will need to use the BLOCKING mode ("Match Camera Framerate" on your session config in Unity). This mode ensures the pose and color camera is synchronized. 

If the experience doesn't involve the color camera and you would like to get the pose tracking as fast as possible, you could use LATEST_CAMERA_IMAGE mode (uncheck the "Match Camera Framerate" on your session config).
