### ISSUE TITLE
Cannot run HelloAR example on S9+ (Failure to initialize)

### ISSUE THREAD

**Issue by AndreaOsorio** [google-ar/arcore-unity-sdk#500]
I just downloaded the ARCore SDK for Unity 1.6.0 and gave Unity 2017.4.2 installed which is supported for AR Core. I just imported the Unity package and build for Android. 
I'm using a Samsung Galaxy S9+ and have the Android 8.0.0. 
Under player settings, I did check the box AR Core Supported in XR Settings.

When I build into my phone it builds successfully but when I run the application it displays a message saying "Failure to initialize! Your hardware does not support this application, sorry!"
 
The Galaxy S9+ does support AR Core, I've used it for Pokemon Go, but still doesn't work for the demo.
 
Does anyone now a fix around this?

Thank you!

**Comment by hhung516** [comment]
try 2018.2

**Comment by fredsa** [comment]
Please see https://developers.google.com/ar/develop/unity/quickstart-android for the minimum version of Unity that's supported.

**Comment by unnam2** [comment]
I did all options, but popup same error message in 2018.1

**Comment by fredsa** [comment]
Please make sure you're on an [ARCore Support Device](https://developers.google.com/ar/discover/supported-devices).
