### ISSUE TITLE
Augmented Faces not work

### ISSUE THREAD

**Issue by ljimenez29** [google-ar/arcore-unity-sdk#503]
Hi, the examples of Augmented Faces in Unity and Android do not work. When the app runs, the front camera does not activate and the screen goes black. I tested it with Sony Xperia XZ1. I did another test with a Samsung Galaxy J5 Pro, and the front camera is activated but it does not detect the face and the camera gets very slow when moving it

Thanks

**Comment by fredsa** [comment]
Can you please provide:

Version info:
- Unity:
- ARCore SDK for Unity: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 


Few things to check
- Verify the minimum version of Unity: https://developers.google.com/ar/develop/unity/quickstart-android
- Check that 'XR Settings > ARCore Supported' is checked in your project
- That camera permission was not denied when prompted
