### ISSUE TITLE
Tango Core has stopped - Samsung Note 8 (UK)

### ISSUE THREAD

**Issue by gak2** [google-ar/arcore-unity-sdk#51]
Hi all,

I'm getting "Tango Core has stopped" / "Tango Core keeps stopping" on the UK Samsung Note 8. Any suggestions?

Thanks!

**Comment by gak2** [comment]
Further info - this is a Duos model: Samsung Galaxy Note 8 SM-N950FZKDBTU (Dual-SIM)

Any info on ARCore compatibility greatly appreciated!

Thanks

**Comment by jguomoto** [comment]
Hi @gak2 ARCore doesn't work on Note8 for now. The list of of supported devices is [here](https://github.com/google-ar/arcore-unity-sdk/releases).
