### ISSUE TITLE
Tracking Jittering - Samsung galaxy tab s4

### ISSUE THREAD

**Issue by luruke** [google-ar/arcore-unity-sdk#512]
### SPECIFIC ISSUE ENCOUNTERED
The tracking seems not precise.
See screencast: https://photos.app.goo.gl/VrLnZwT24dHTAGRRA

Is it intended to work like this?

### VERSIONS USED
- Unity: 2018.3.0f2
- ARCore SDK for Unity: 1.7
- Device manufacturer, model, and O/S: 
Samsung galaxy tab s4 (t830) – android 8.1.0
- ARCore: 
`versionName=1.7.190128066`

- Output of `adb shell getprop ro.build.fingerprint`: 
`samsung/gts4lwifixx/gts4lwifi:8.1.0/M1AJQ/T830XXU2ARK4:user/release-keys`

### STEPS TO REPRODUCE THE ISSUE
 1. Running the official example scene `AugmentedImage`
 2. Notice jittering on tracking

## ADDITIONAL COMMENTS
I wanted to try other AR apps, and I noticed:
- `Measure` app from Google also seems not stable and precise.
- `IKEA Place`, crashes at launch.

Do you know any other "mainstream" ARCore apps I can test?

**Comment by luruke** [comment]
I was also able to reproduce similar issues with the "native" sample in Java.

https://github.com/google-ar/arcore-android-sdk/issues/720

**Comment by fredsa** [comment]
Thanks for the report. Since you're issue does not appear to be Unity specific, let's use https://github.com/google-ar/arcore-android-sdk/issues/720 to track this.
