### ISSUE TITLE
Anchors for moving Game Objects

### ISSUE THREAD

**Issue by radhakrishna2014** [google-ar/arcore-unity-sdk#516]
As per the documentation below:
https://developers.google.com/ar/develop/developer-guides/anchors
Anchors can be created in the context of Trackable and ARCore Session. This works perfectly only if the object is not moving, as the object moves a few meters away from the anchor, anchors don't work. If I try to move the game objects in the real environment without creating anchors, as soon as, ARCore tracking adjusts with the environment, the position of the moving game object is also affected. Is there any way to even have anchors for moving game objects in the real environment or a way that game object doesn't drift when ARCore tracking updates?

**Comment by fredsa** [comment]
Thanks for the request. Likely best addressed by #299
