### ISSUE TITLE
Random crash on Samsung Galaxy S7

### ISSUE THREAD

**Issue by Ursanon** [google-ar/arcore-unity-sdk#518]
### SPECIFIC ISSUE ENCOUNTERED
After random time (0-xyz minutes) app crashes.
Backtrace shows last `pc` in ARCore lib (/data/app/com.google.ar.core-vXvgWLHB6fKaabOtyAGPhA==/lib/arm/libarcore_c.so).

### VERSIONS USED
- Unity: 2018.3.5f1, 2018.3.6f, 2017.4.22f (Mono builds, .Net 4.0)
- ARCore SDK for Unity: 1.7.0
- Device manufacturer, model, and O/S: 
    Samsung, SM-G930F, Android 8.0.0
- ARCore: 
    versionName=1.7.190128146
- Output of `adb shell getprop ro.build.fingerprint`: 
    samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXS3ERLF:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Run examples (especially ObjectManipulation scene).
 2. Wait x minutes to crash (really random)

### WORKAROUNDS (IF ANY)
I haven't found any 😞 

### ADDITIONAL COMMENTS
The same error occurs with [ARFoundation samples](https://github.com/Unity-Technologies/arfoundation-samples)

Logcat from this device:
[03-07-arcore_sample_logcat_samsung_s7 2.txt](https://github.com/google-ar/arcore-unity-sdk/files/2941112/03-07-arcore_sample_logcat_samsung_s7.2.txt)

**Comment by Ursanon** [comment]
This bug can be reproduced on Xiaomi POCO F1.
Will ship more info if needed.

**Comment by fredsa** [comment]
@Ursanon Please attached the output of `adb logcat` that includes the crash. Also, please provide the output of `adb shell getprop ro.build.fingerprint`

**Comment by Ursanon** [comment]
@fredsa logcat and fingerprint are in [first comment](https://github.com/google-ar/arcore-unity-sdk/issues/518#issue-418311752)

Unfortunately I don't have access to POCO F1's logs, sorry

**Comment by fredsa** [comment]
Thanks, @Ursanon. Let us know if you do get access to another device and are able to share `adb logcat` and device fingerprint of that other device.

**Comment by FUBAR2077** [comment]
@fredsa - you have more information in this issue - I assume they are connected:
https://github.com/google-ar/arcore-unity-sdk/issues/553

**Comment by Ursanon** [comment]
Unfortunately, I haven't found any workaround yet

**Comment by fredsa** [comment]
This looks like https://github.com/google-ar/arcore-android-sdk/issues/291
Let's track the issue there.

**Comment by linojon** [comment]
hi, I'm also having a random crash on Galaxy S7 with Android 8.0.0. Could you confirm if its related to this issue and the #291 one, or not? thanks.

Logcat:
[logsF.txt](https://github.com/google-ar/arcore-unity-sdk/files/3217619/logsF.txt)

$ adb shell getprop ro.build.fingerprint
Verizon/hero2qltevzw/hero2qltevzw:8.0.0/R16NW/G935VVRS9CSC1:user/release-keys

**Comment by linojon** [comment]
note, i found that if i disable the ARCoreBackgroundRenderer component on the camera (after completing the spatial scanning), my app does not incur the crashes.

**Comment by Ursanon** [comment]
Cause high CPU usage triggers in some cases this deadlock. See this: https://github.com/google-ar/arcore-android-sdk/issues/291
