### ISSUE TITLE
TrackedPlaneManager uses Time.time instead of Time.unscaledTime

### ISSUE THREAD

**Issue by henningboat** [google-ar/arcore-unity-sdk#52]
In TrackedPlaneManager.cs:79 to 85 `Time.time` should be replaced with  `Time.unscaledTime`. 
A lot of games set Time.timeScale to zero if the player enters the pause menu, which affects  `Time.time`, but not `Time.unscaledTime`.

**Comment by jguomoto** [comment]
This is changed in DP2, we don't use Time anymore.
