### ISSUE TITLE
There are different results for camera texture in the editor and mobile environment.

### ISSUE THREAD

**Issue by khseob0715** [google-ar/arcore-unity-sdk#520]
### SPECIFIC ISSUE ENCOUNTERED
I need a real world texture without argumented object, formerly using the method of erase UI and taking a capture.

but it was so slow that I found Fram.CameraImage.Texture
It worked normally in a Unity Editor environment.

But if you build it on your phone and check it out, Texture is null.
I know this problem is because the CPU is inaccessible on mobile phones.

So I found another way, and I found this one, AcquireCameraImageBytes().

https://stackoverflow.com/questions/55159113/loadrawtexturedata-not-enough-data-provided-error-in-unity

There were as many problems as in the previous question, but the problem was solved when the YUV format was converted to RGB format.

However, it works normally only in Unity Editor, and when built with a mobile phone, a gray image is output.

![그림1](https://user-images.githubusercontent.com/22340876/54412736-3cc7a100-4737-11e9-9982-5813734ec479.png)

this is my full code

````
    namespace GoogleARCore
     {
        using System;
        using UnityEngine;
        using UnityEngine.UI;

        public class TestFrameCamera : MonoBehaviour
        {
            private Texture2D m_TextureRender;

            private void Update()
            {
                using (var image = Frame.CameraImage.AcquireCameraImageBytes())     { 
                    if(!image.IsAvailable)
                    {
                        return;
                    }

                    _OnImageAvailable(image.Width, image.Height, image.Y, image.Width * image.Height);
                }

            }
            private void _OnImageAvailable(int width, int height, IntPtr pixelBuffer, int bufferSize)
            {

                m_TextureRender = new Texture2D(width, height, TextureFormat.RGBA32, false, false);
                byte[] bufferYUV = new byte[width * height * 3 / 2];
                bufferSize = width * height * 3 / 2;
                System.Runtime.InteropServices.Marshal.Copy(pixelBuffer, bufferYUV, 0, bufferSize);
                Color color = new Color();
                for (int y = 0; y < height; y++)
                {
                    for (int x = 0; x < width; x++)
                    {

                        float Yvalue = bufferYUV[y * width + x];
                        float Uvalue = bufferYUV[(y / 2) * (width / 2) + x / 2 + (width * height)];
                        float Vvalue = bufferYUV[(y / 2) * (width / 2) + x / 2 + (width * height) + (width * height) / 4];
                        color.r = Yvalue + (float)(1.37705 * (Vvalue - 128.0f));
                        color.g = Yvalue - (float)(0.698001 * (Vvalue - 128.0f)) - (float)(0.337633 * (Uvalue - 128.0f));
                        color.b = Yvalue + (float)(1.732446 * (Uvalue - 128.0f));

                        color.r /= 255.0f;
                        color.g /= 255.0f;
                        color.b /= 255.0f;

                        if (color.r < 0.0f)
                            color.r = 0.0f;
                        if (color.g < 0.0f)
                            color.g = 0.0f;
                        if (color.b < 0.0f)
                            color.b = 0.0f;

                        if (color.r > 1.0f)
                            color.r = 1.0f;
                        if (color.g > 1.0f)
                            color.g = 1.0f;
                        if (color.b > 1.0f)
                            color.b = 1.0f;

                        color.a = 1.0f;
                        m_TextureRender.SetPixel(width - 1 - x, y, color);
                    }
                }


                m_TextureRender.Apply();
                this.GetComponent<RawImage>().texture = m_TextureRender;
            }
        }
    }
````
I'm just testing this script by adding it to an object that contains Rawimage in the ARCore sample code.

why...?

### VERSIONS USED
- Unity: 2017.4.10f1 
- ARCore SDK for Unity:  1.5.0
- Device manufacturer, model, and O/S:  Android Note 9

**Comment by khseob0715** [comment]
**Unity Editor Environment**
image.Width = 480
image.Height= 640
image.YRowStride = 480
image.UVRowStride = 240

**mobile Environment 
image.Width = 640
image.Height = 480
image.YRowStride = 640
image.UVRowStride = 640

Due to the above differences, the conversion from YUV 420 888 format to RGB format seems to cause problems.

How should I change to RGB format?

**Comment by khseob0715** [comment]
In mobile environments, NV21 or YUV420SP formats are obtained.
So it's possible to find an RGB conversion source in NV21 format, and I succeeded.

![Screenshot_20190319-135551_CV U3D](https://user-images.githubusercontent.com/22340876/54581206-ffbd2080-4a4e-11e9-86f5-48cb0e91122c.png)

**Comment by DerrickBarra** [comment]
@khseob0715 : Would you mind posting your working code for this conversion?

**Comment by khseob0715** [comment]
@DerrickBarra Sure, Why not? But help me one thing.
The code you want is on the link to the question below.
Can you give me an answer to that question?

https://stackoverflow.com/questions/55351640/image-format-conversion-optimization-rgb-in-unity-c-sharp

**Comment by serbelga** [comment]
> In mobile environments, NV21 or YUV420SP formats are obtained.
> So it's possible to find an RGB conversion source in NV21 format, and I succeeded.
> 
> ![Screenshot_20190319-135551_CV U3D](https://user-images.githubusercontent.com/22340876/54581206-ffbd2080-4a4e-11e9-86f5-48cb0e91122c.png)

Could you please post the code for this?

**Comment by serbelga** [comment]
> > In mobile environments, NV21 or YUV420SP formats are obtained.
> > So it's possible to find an RGB conversion source in NV21 format, and I succeeded.
> > ![Screenshot_20190319-135551_CV U3D](https://user-images.githubusercontent.com/22340876/54581206-ffbd2080-4a4e-11e9-86f5-48cb0e91122c.png)
> 
> Could you please post the code for this?

Finally I can achieve this by using TextureReader component. 

![preview](https://user-images.githubusercontent.com/26246782/60758877-b522dc80-a01c-11e9-94de-480e271054b5.gif)

https://github.com/serbelga/ARCoreOpenCV
