### ISSUE TITLE
Microphone doesn't work with ARCore enabled

### ISSUE THREAD

**Issue by kimberlysiva** [google-ar/arcore-unity-sdk#53]
Unity 2017.3.0f2
Android API level 25
Google Pixel 2

With ARCore Supported checked under XR Settings we get the following error:

"Starting Microphone failed. result=33 (An error occured that wasn't supposed to.  Contact support. )"

Unchecking ARCore Supported fixes the problem.

**Comment by kimberlysiva** [comment]
Ah-ha! For some reason the microphone permission prompt isn't being displayed when ARCore is enabled. We can manually grant the microphone permission in settings and everything works.

**Comment by chaosemer** [comment]
Yup, that is correct. You can manually request permission granting with the [AndroidPermissionManager class](https://developers.google.com/ar/reference/unity/class/GoogleARCore/AndroidPermissionsManager) in our SDK.
