### ISSUE TITLE
ARCore Augmented Faces. 3D mesh instead of fox Example

### ISSUE THREAD

**Issue by Russel1** [google-ar/arcore-unity-sdk#532]
How can I display the 3D mesh generated by ARCore like here?

https://1.bp.blogspot.com/-nUNmjUY0kwo/XIGaggwn58I/AAAAAAAAD4A/tA3S0Tgu5N4rbjlaNEbr_I5GuHbQwHyRgCEwYBhgL/s400/image6.gif

**Comment by patrickscheper** [comment]
There's already a 'canonical_face_mesh' object inside of the Examples folder that you could use I think. Everything else from that picture is just shaders.

**Comment by Russel1** [comment]
Thanks a lot, unfortunately a part of the canonical_face_mesh disappears every time I get closer or turn my head. What can I do to avoid such problems with the Z coordinate?

**Comment by bopangzz** [comment]
To display the face mesh its self, you will need to use some mesh wireframe renderer along with the [ARCoreAugmentedFaceMeshFilter](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/AugmentedFaces/Scripts/ARCoreAugmentedFaceMeshFilter.cs) to provide the face mesh data.

**Comment by Russel1** [comment]
Thank you @bopangzz and @patrickscheper , now it works with a wireframe renderer :).

**Comment by Russel1** [comment]
One more question, shouldn't the vertices change? For example, if I open my mouth. At the moment the mesh doesn't change. @bopangzz

**Comment by timneill40** [comment]
Hi Russel1. What wire renderer did you use? Thank you!

**Comment by Russel1** [comment]
Hi @timneill40,

I used this one https://github.com/miguel12345/UnityWireframeRenderer :)

**Comment by timneill40** [comment]
Thanks Russel!

**Comment by pancar** [comment]
Why eye blinking aren't updated? 

https://youtu.be/pB3_jlaMwyI 

is that video fake?
