### ISSUE TITLE
When will Google Support ARCore for S8+ (SM-G955U)?

### ISSUE THREAD

**Issue by JOESIDinc** [google-ar/arcore-unity-sdk#54]
Hi Everyone,

I say this because I'm excited to start development for ARCore but I'm finding it really hard to wait. :) I bought my S8+ (SM-G955U) back in April with the intent of development for ARCore. I'm on the verge of trading it in for an S8 for this very reason. Is there any estimate of time you can give us that would indicate when the support would arrive for S8+? Since the news announcement in October 2017 I haven't heard a word. People are resorting to using this modded version https://github.com/tomthecarrot/arcore-for-all It works to an extent but it's a bit jittery so I'm assuming its because its not the actual version. I switched gears back recently to work on Vuforia, GearVR, and GoogleVR for the time being. You can see my progress in this field here: http://www.joesid.com. Please release as soon as possible even if it's a beta release. My email is JOESIDinc@gmail.com if this is possible.

Thanks - Joe

**Comment by chaosemer** [comment]
Developer preview 2 does not support the S8+. If you want to develop on top of the developer preview SDK, you'll need to switch to one of the support S8 models, or a Pixel or Pixel2. If you want to also support GearVR, the S8 is your best best as it supports ARCore, GoogleVR, GearVR, and Vuforia.

I'm glad your enthusiastic about AR and VR, we **ar**e too!
