### ISSUE TITLE
Plane Detection Visualizer not working after Android SDK update

### ISSUE THREAD

**Issue by Oscheibe** [google-ar/arcore-unity-sdk#543]
### SPECIFIC ISSUE ENCOUNTERED
After updating to the latest "ARCore by Google" version 1.8.0 in the Android Play Store, the "DetectedPlaneGenerator" script with the "DetectedPlaneVisualizer" prefabs don't work anymore. 

### VERSIONS USED
- Unity: 2018.3.6f1
- ARCore SDK for Unity: 1.8.0
- ARCore SDK for Android: 1.8.0
- Device manufacturer, model, and O/S: Huawei P20 Pro, Android 9.0

### STEPS TO REPRODUCE THE ISSUE
(Following the ARCore Introduction codelab project by Google)
 1. Add the ARCore Device and Environmental Light prefab to the scene
 1. Add an EventController GameObject
 1. Add a SceneController GameObject and attach the scene controller script as shown in the codelab
 1. Add DetectedPlaneGenerator to the SceneController GameObject
 1. Add DetectedPlaneVisualizer to the DetectedPlaneGenerator script
 1. Build the unity project

### WORKAROUNDS
Uninstall the "ARCore by Google" version 1.8.0 in the Play Store and install ARCore SDK for Android v1.7.0 from github.

**Comment by FUBAR2077** [comment]
Did anyone else experience it? I was thinkin about updating SDK but I don't know if I should

**Comment by Oscheibe** [comment]
> Did anyone else experience it? I was thinkin about updating SDK but I don't know if I should

It seems to be a Huawei P20 Pro related issue. See this issue: https://github.com/google-ar/arcore-android-sdk/issues/758

**Comment by Oscheibe** [comment]
The Issue is not present anymore with ARCore version 1.9.0
