### ISSUE TITLE
ArPresto_setDeviceCameraDirection Error

### ISSUE THREAD

**Issue by Snrasha** [google-ar/arcore-unity-sdk#546]
>     (Filename:  Line: 451)
> E/Unity: EntryPointNotFoundException: ArPresto_setDeviceCameraDirection
>         at (wrapper managed-to-native) GoogleARCoreInternal.ARCoreAndroidLifecycleManager+ExternApi.ArPresto_setDeviceCameraDirection(GoogleARCoreInternal.ApiPrestoDeviceCameraDirection)
>       at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._SetCameraDirection (GoogleARCore.DeviceCameraDirection cameraDirection) [0x00079] in <a7d073156d834947bb45f40d6f8ca73c>:0 
>       at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._OnEarlyUpdate () [0x00045] in <a7d073156d834947bb45f40d6f8ca73c>:0 
>       at GoogleARCoreInternal.ARPrestoCallbackManager._EarlyUpdateTrampoline () [0x00011] in <a7d073156d834947bb45f40d6f8ca73c>:0 

- Unity: 2018.3.6f1 Personal
- ARCore SDK for Unity:  1.8.0
- Device: Android Galaxy S10
- ARCore: Recent

### STEPS TO REPRODUCE THE ISSUE
 1. Export Unity Project with 1.8.0 Arcore version on Android java project
 2. Run the project on Android studio
 3. Get the crash.

### ADDITIONAL COMMENTS
I have decided to put my issue here because this is a issue with Arcore Unity, not arcore android(like i do not use it)
The bug is not visible on Unity, if you build & run the project.
The bug has not be present on the 1.7.0 Arcore. (But downgrade do not seems to resolve my problem)

I have got the problem just after have upgraded my version of Arcore 1.7.0 to 1.8.0

**Comment by Snrasha** [comment]
Stupid error of my part, i have not updated the libs on Android Java project. Sometimes than i have not update when i export my java project.

**Comment by Meghna-Anam** [comment]
How did you solve this problem!?I have the same issue

**Comment by Snrasha** [comment]
After have updated ArCore on Unity, you export your project on a project
Java?
But then, you use part of it for your true project java?

If yes, you need to move the libs on the exported project and put them on
your true project java.

Sorry for be late and i do not think this is your problem.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 19 sept. 2019 à 19:45, Meghna-Anam <notifications@github.com> a
écrit :

**Comment by Meghna-Anam** [comment]
Actually i got below error in adb logcat when i run my unity project in my Android device with USB cable:
E/Unity: EntryPointNotFoundException: ArPresto_setDeviceCameraDirection
at (wrapper managed-to-native) GoogleARCoreInternal.ARCoreAndroidLifecycleManager+ExternApi.ArPresto_setDeviceCameraDirection(GoogleARCoreInternal.ApiPrestoDeviceCameraDirection)
at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._SetCameraDirection (GoogleARCore.DeviceCameraDirection cameraDirection) [0x00079] in :0
at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._OnEarlyUpdate () [0x00045] in :0
at GoogleARCoreInternal.ARPrestoCallbackManager._EarlyUpdateTrampoline () [0x00011] in :0

Unity version:2019.2.5f
Sdk version:1.12
Android device: OnePlus 5T

When i export my project in Android studio and run it on my Android device..the logo 'made with unity' appears, then application get crashed

How i solve this issue

**Comment by Meghna-Anam** [comment]
Actually i got below error in adb logcat when i run my unity project in my Android device with USB cable:
E/Unity: EntryPointNotFoundException: ArPresto_setDeviceCameraDirection
at (wrapper managed-to-native) GoogleARCoreInternal.ARCoreAndroidLifecycleManager+ExternApi.ArPresto_setDeviceCameraDirection(GoogleARCoreInternal.ApiPrestoDeviceCameraDirection)
at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._SetCameraDirection (GoogleARCore.DeviceCameraDirection cameraDirection) [0x00079] in :0
at GoogleARCoreInternal.ARCoreAndroidLifecycleManager._OnEarlyUpdate () [0x00045] in :0
at GoogleARCoreInternal.ARPrestoCallbackManager._EarlyUpdateTrampoline () [0x00011] in :0

Unity version:2019.2.5f
Sdk version:1.12
Android device: OnePlus 5T

When i export my project in Android studio and run it on my Android device..the logo 'made with unity' appears, then application get crashed

How to solve this issue!

**Comment by Snrasha** [comment]
I am not sure to help you anymore, but i am pretty sure than Unity 2019 has
some issues with Android? Or the last Sdk version of Arcore on Unity.
I am pretty sure than yes there are 1-2 months, but now?

I have used Unity 2018 and 1.10 for the sdk arcore.  For the Android
device, well i got not problem with a One Plus 7(S10) or with a S8.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le sam. 21 sept. 2019 à 13:39, Meghna-Anam <notifications@github.com> a
écrit :

**Comment by Meghna-Anam** [comment]
Okay.. thanks for reply
