### ISSUE TITLE
SDK Preview 2: Computer Vision Example

### ISSUE THREAD

**Issue by Saicopate** [google-ar/arcore-unity-sdk#55]
I downloaded and tested the new preview v.2 (unity edition) and was very excited to see Computer Vision example. However as it turned out, the example is only a camera feed with applied edge detection + shader effects.

I noticed that in the archive there is a zip file unused by Unity, named "arcore_camera_utility.zip" with some C/C++ files (?) and a annotation to use Android NDK to apply the code. How to do it exactly? Through Android Studio? Is there a guide/documentation anywhere?

**Comment by chaosemer** [comment]
In the Computer Vision sample, all the processing is done on the CPU directly on a byte pointer, see the [OnImageAvailable callback in ComputerVisionController.cs](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/ComputerVision/Scripts/ComputerVisionController.cs#L86-L109). This pointer could equally well be passed into any computer vision library, such as OpenCV or the Google Mobile Vision API.

Most of the code in arcore_camera_utility is OpenGL programming directly in C code. If you're not familiar with OpenGL development or have not done Android NDK programming before, I suggest starting from an NDK tutorial, such as the [one on the Android dev site](https://developer.android.com/ndk/guides/index.html).

**Comment by Saicopate** [comment]
Thank you. That make it clear regarding the preview example. 

Are you aware of any publicly available example (with code) where ARCore was actually used together with OpenCV or Vision API?
