### ISSUE TITLE
How to Build a Project with the Preview?

### ISSUE THREAD

**Issue by iHzm** [google-ar/arcore-unity-sdk#56]
Hi, I have had this question for a long time, but I thought that it would be soon solved. 

When I build the project in Unity, how do I include the ARCore Preview with the APK?

**Comment by chaosemer** [comment]
Developer Preview 2 does not currently support distribution yet. ARCore 1.0 will support additional APIs to install ARCore preview from within your app so you can distribute cleanly on the Play Store.

**Comment by iHzm** [comment]
Are there any 'hacks' that you know of that can let you do so?

**Comment by chaosemer** [comment]
Creating apps for distribution is something we do not officially support. Like I said, we're on it -- there will be a solution for 1.0.

**Comment by fredsa** [comment]
Documentation for how to publish ARCore based apps will be included in the 1.0 release.
