### ISSUE TITLE
An error occur and the camera may not start up

### ISSUE THREAD

**Issue by TakuKobayashi** [google-ar/arcore-unity-sdk#59]
Hi,When I build and run the project I currently create, the camera does not start up, and a dark screen is displayed.
I got a log using the Logcat and investigated the situation where this phenomenon occurred and found the following error logs.

```
12-18 19:19:22.845 765-9456/? E/eglc2d: Grid warp program has been set
12-18 19:19:22.845 765-9456/? E/eglc2d: Grid split warp program has been set
```

If I am using the "GridLayout" of Unity, it seems that this kind of phenomenon will occur. (The camera screen is now displayed when building without actually using GridLayout)
Do you know the reasons?
Thanks.

**Comment by chaosemer** [comment]
We haven't seen this before. Can you please verify you are using the latest Unity beta and Developer Preview 2? You need to be using Unity 2017.3.0f2 or later to work with Developer Preview 2.

**Comment by TakuKobayashi** [comment]
Yes, this will happen on Unity 2017.3.0f2 and ARCore Developer Preview 2.
And also, the verified device is the Android 8.1 version of Pixel 2.
Incidentally, in ARCore Developer Preview 1, this phenomenon did not occur.

**Comment by chaosemer** [comment]
Okay, sounds like you found a bug. Could you please send a simplified repro project that we can investigate on? Thanks for your help here.

**Comment by TakuKobayashi** [comment]
I have created a new project where this phenomenon occurs.
This is the project's repository.
https://github.com/TakuKobayashi/ARCoreReport

**Comment by TakuKobayashi** [comment]
After further investigation it turned out that it seems that some additional conditions are necessary to occur.

 * Include japanese in the UI.
 * Include ScrollView and GridLayout.

This is conditions to occur.

**Comment by chucknology** [comment]
Check your log for AR_ERROR_NOT_YET_AVAILABLE - this seems to be a lifecycle bug related to the camera taking an unexpectedly long time to start up.

**Comment by chucknology** [comment]
I have a fix for these symptoms. I don't know if it will help you:
https://github.com/google-ar/arcore-unity-sdk/issues/70

**Comment by chaosemer** [comment]
ARCore 1.0 is out on the Play Store and here.
