### ISSUE TITLE
HelloAR crashing on Quit in IL2CPP builds

### ISSUE THREAD

**Issue by atul109** [google-ar/arcore-unity-sdk#591]
ARCore IL2CPP build crashing on back button pressed. Mono build (.NET 3.5) has no issues, but new Google play regulations need 64 bit which require IL2CPP builds.

Crash log will start like this and 
`E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000034`

### VERSIONS USED
- Unity: 2018.2.20f1, MacOS 10.14.5 (It will crash on any Unity till 2019.1)
   Also tested on Unity 2018.2.20f1, Windows 10
- ARCore SDK for Unity: 1.6.0, 1.10 (All ARCore Unity SDKs might show this issue)
- Device manufacturer, model, and O/S: Samsung S9+, Android 9.0

### STEPS TO REPRODUCE THE ISSUE
In ARCore supported phones
 1. Import ARCore sdk to unity, and add build HelloAR scene with IL2CPP scripting backend
 2. Press back button to see crash

In non ARCore phones
 1. Import ARCore sdk to unity.
 2. Open HelloAR and disable all GameObjects and then add a camera with a script just to quit app on pressing back button.
 3. Build HelloAR scene with IL2CPP scripting backend
 4. Press back button to see crash

**Comment by atul109** [comment]
Issue got fixed when changed Target API level to Android 9.0. The errors were obtained when Target API level was Android 8.1.

**Comment by sandeepkiks** [comment]
This issue still occurs even if Target API level is set to Android 9.0 on Unity 2019.2.xx versions
