### ISSUE TITLE
Can't test any example

### ISSUE THREAD

**Issue by Soncomander** [google-ar/arcore-unity-sdk#60]
Hello! I just pulled the Preview 2 and now I can't open any example on Android, even Hello AR.
I didn't change anything on build configs, just hit build & run and the app returned "ARCore encountered a problem connecting. Please start the app again.";
I started again and keep returning this message.

This problem didn't occurred in Preview 1.

> Using Galaxy S8 -- SM-G950F

**Comment by chaosemer** [comment]
What version of Unity are you running on? Developer Preview 2 requires Unity 2017.3.0f2 or higher to run (you can get it from unity3d.com/beta)

**Comment by brucevang** [comment]
I'm using Unity 2017.3.0f2 and I don't have any problems. Pixel XL v1

**Comment by cgydev** [comment]
Tested with Unity 2017.3.0f2 & Pixel 2 XL , both examples work fine.

**Comment by Soncomander** [comment]
@chaosemer 
I'm using Unity 2017.3.0f2

**Comment by geetves** [comment]
I am getting same error in 2017.3.0f2.

**Comment by Bezarius** [comment]
12-20 18:45:07.881  9934  9951 D Unity   : Loading ARCore V1+ path.
12-20 18:45:07.892  9934  9951 I Unity   : ArCoreUnity_onUnityPlayerInitialize
12-20 18:45:07.893  9934  9951 I Unity   : ArCoreUnity_getARCoreSupportStatus, expected_api_level=1, supported_api_level=1
12-20 18:45:07.893  9934  9951 I Unity   : ArCoreUnity_onUnityPlayerResume
12-20 18:45:07.920  9934  9951 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 8, Memory = 3459mb
12-20 18:45:07.920  9934  9951 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 240), 4 little (mask: 15)
12-20 18:45:07.920  9934  9951 I Unity   : ApplicationInfo com.google.ar.core.examples.unity.helloar version 1.0 build 2878076c-59fd-418d-a54f-c34345ba2877
12-20 18:45:07.920  9934  9951 I Unity   : Built from '2017.3/staging' branch, Version '2017.3.0f3 (a9f86dcd79df)', Build type 'Release', Scripting Backend 'mono'
12-20 18:45:08.022  9934  9951 E Unity   : Unable to find unitygar
12-20 18:45:08.103  9934  9951 D Unity   :  GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_
12-20 18:45:08.103  9934  9951 D Unity   : to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_shader_non_constant_global_initializers GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EX
12-20 18:45:08.103  9934  9951 D Unity   : T_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures
12-20 18:45:10.764  9934  9951 I Unity   : ArCoreUnity_createSession
12-20 18:45:10.777  9934  9951 E Unity   : Could not create an ARCore session.
12-20 18:45:10.788  9934  9951 E Unity   : ARCore failed to create a session.
12-20 18:45:10.788  9934  9951 E Unity   :
12-20 18:45:10.788  9934  9951 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-20 18:45:10.788  9934  9951 E Unity   :
12-20 18:45:10.800  9934  9951 E Unity   : Could not create an ARCore session.  The current Unity Editor may not support this version of ARCore.
12-20 18:45:10.800  9934  9951 E Unity   :    at GoogleARCore.ARCoreSession.Awake()
12-20 18:45:10.800  9934  9951 E Unity   :
12-20 18:45:10.800  9934  9951 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-20 18:45:10.800  9934  9951 E Unity   :
12-20 18:45:11.711  9934  9934 I Unity   : ArCoreUnity_onUnityPlayerPause
12-20 18:45:15.713  9934  9934 W Unity   : Timeout while trying to pause the Unity Engine.

**Comment by iBicha** [comment]
The ARCore service for preview 2 is a different apk, and needs to be installed from [here](https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview2/arcore-preview2.apk)

See [getting-started](https://developers.google.com/ar/develop/unity/getting-started)

**Comment by qinzitan** [comment]
I'm getting the same error:
Samsung S8
Unity 2017.3.0f3

**Comment by qinzitan** [comment]
Solved the issue by installing preview2.apk

**Comment by chucknology** [comment]
You can test with Atom Visualizer (except on Pixel phones - the build of ARCore in the Play Store for AR Stickers is older than the ARCore Preview 2 service APK on the developer site).
https://play.google.com/store/apps/details?id=com.signalgarden.atomvisualizer

**Comment by chaosemer** [comment]
We were unable to reproduce your error on our S8 (model SM-G950F). It sounds like you may not have arcore-preview2.apk installed. It'll appear as "ARCore" in the all apps menu on your phone.

If you're still having issues, please capture a bug report via adb bugreport immediately after running the app.

**Comment by geetves** [comment]
Installing preview2.apk solved my issue too

**Comment by chucknology** [comment]
Awesome!
We're gonna share our fixes with Jared for the whole community. The new regime means technically "they don't support GitHub pull requests" but there are Easter Eggs like ... (for my students that find this comment) ...why the Unity frame class has never been static when all its components are static with a private constructor.
For everyone that sees this:
If you think you can do better than Google - you can. Have faith in yourself.
It doesn't matter about your schooling, how you identify, what you believe.
When you're right, you're right.

**Comment by chucknology** [comment]
I love you.

**Comment by chaosemer** [comment]
Bug reports are greatly appreciated. I like to say "all code has bugs", so if you find one, please share the details.

**Comment by chucknology** [comment]
New repo here: https://github.com/chucknology/ARCorePixelFix
Atom Visualizer has been updated with this solution
https://play.google.com/store/apps/details?id=com.signalgarden.atomvisualizer

**Comment by vettorazi** [comment]
installing the new preview2.apk worked for me! thanks guys

**Comment by stars66** [comment]
I can't install arcore-preview2.apk in my phone (SM G-950F)  "App not installed". What's the problem?

**Comment by iBicha** [comment]
@stars66 ARCore is out of preview, the actual library is on play store now.
https://play.google.com/store/apps/details?id=com.google.ar.core

**Comment by stars66** [comment]
Atom visualizer is working, What is difference?

**Comment by iBicha** [comment]
@stars66 There has been few changes between versions (previews had different apks etc)
You are better off following the Quick start here https://developers.google.com/ar/develop/unity/quickstart
