### ISSUE TITLE
How to detect Face parts Eyes, nose etc.

### ISSUE THREAD

**Issue by vinayak-vc** [google-ar/arcore-unity-sdk#602]
Hi there, 

Title says itself 
Does anyone know how can we get the data about the position of eyes, nose, etc in ARfoundation or in ARCore?

or Where should we dig to achieve this task?

**Comment by miyagin15** [comment]
Hi
Did you look  this page ?(https://github.com/google-ar/sceneform-android-sdk/issues/563) 

I think it will help you

**Comment by ManuelTS** [comment]
As said by @miyagin15, #563 will help you to get all the single meshes with their coordinates, triangle indices and normals for the whole face. Just use the correct mesh indices sufficient for your needs.
