### ISSUE TITLE
Frame delay introduced in 1.10

### ISSUE THREAD

**Issue by stephen-systemfriend** [google-ar/arcore-unity-sdk#605]
### SPECIFIC ISSUE ENCOUNTERED
Upon upgrading the ARCore Version to 1.10, we notice a delay in the frame capture time of around 36ms, which was not present in previous ARCore Versions.

### VERSIONS USED
- Unity: 2017.4.6f1
- ARCore SDK for Unity: 1.10.0 
- Device manufacturer, model, and O/S: Sony Xperia something android 8.0
- ARCore: 1.10.0

### ADDITIONAL COMMENTS
We are simultaneously using a feed from another hardware resource, so this frame delay is breaking the alignment, and delaying the other feed by 36ms constitutes an undesirable degradation of performance. 

Is there any setting or similar that can be changed to stop this delay?

**Comment by dnnkeeper** [comment]
This happens only if Image Tracking database is set, right? I assume it is a side effect of the moving markers tracking feature that appeared in 1.9

I'd be glad to disable this feature if it would reduce frame buffering delay because I'm working with stationary markers
