### ISSUE TITLE
UI Canvas Camera mode doesn't work with ARCore Camera

### ISSUE THREAD

**Issue by roycho111** [google-ar/arcore-unity-sdk#606]
When I use canvas as camera mode and put ARCore camera as canvas camera, UI disappears from screen.

It seems like ARCore camera's projection matrix is affecting canvas size when using camera mode.

Would there be any solution to this?

**Comment by joaoparis** [comment]
Hello. Same problem. Do you know the fix?
Ty

**Comment by roycho111** [comment]
I just used rendertexture for arcamera and assigned it to raw image.
