### ISSUE TITLE
Change grid color when a plane is detected

### ISSUE THREAD

**Issue by ljimenez29** [google-ar/arcore-unity-sdk#611]
Hi, in ARCore for Unity, is there a way to know when a plane is detected if it is horizontal or vertical through the color of the detected plane? 

What I want is for the grid to have a color when the plane is horizontal and change color when the plane is vertical

### VERSIONS USED
- Unity: 2019.1.6f1
- ARCore SDK for Unity: v1.10.0
- Device manufacturer, model, and O/S: Sony Xperia XZ1. Android 9.0 and Samsung Galaxy J5 Pro

**Comment by radhakrishna2014** [comment]
To assign different colors to the horizontal and vertical detected planes, you can access the DetectedPlaneVisualizer.cs  script and makes changes to read-only variable k_PlaneColors and reduce the number of colors to 2, as we need to assign 2 different colors based on the type. Then, change the Initialize method like below.

`     public void Initialize(DetectedPlane plane)
        {
            m_DetectedPlane = plane;
            if (m_DetectedPlane.PlaneType == DetectedPlaneType.Vertical)
            {
                m_MeshRenderer.material.SetColor(
                    "_GridColor", k_PlaneColors[0]);             
            }
            else
            {
                m_MeshRenderer.material.SetColor(
                 "_GridColor", k_PlaneColors[1]);
            }

            m_MeshRenderer.material.SetFloat("_UvRotation", Random.Range(0.0f, 360.0f));
            Update();
        }`

Now, when you deploy you can have one unique color for Horizontal and Vertical detected planes.

**Comment by ljimenez29** [comment]
> To assign different colors to the horizontal and vertical detected planes, you can access the DetectedPlaneVisualizer.cs script and makes changes to read-only variable k_PlaneColors and reduce the number of colors to 2, as we need to assign 2 different colors based on the type. Then, change the Initialize method like below.
> 
> ```
>         public void Initialize(DetectedPlane plane)  
>         {  
>              m_DetectedPlane = plane;
>              if (m_DetectedPlane.PlaneType == DetectedPlaneType.Vertical)
>              {
>                    m_MeshRenderer.material.SetColor(
>                        "_GridColor", k_PlaneColors[0]);             
>              }
>              else
>              {
>                    m_MeshRenderer.material.SetColor(
>                      "_GridColor", k_PlaneColors[1]);
>              } 
>             m_MeshRenderer.material.SetFloat("_UvRotation", Random.Range(0.0f, 360.0f));
>             Update();
>         }
> ```
> 
> Now, when you deploy you can have one unique color for Horizontal and Vertical detected planes.

Thanks, it worked
