### ISSUE TITLE
External USB camera for ARCore

### ISSUE THREAD

**Issue by kinectsources** [google-ar/arcore-unity-sdk#635]
How can I use external USB camera for ARCore? Is it possible with ARCore? Is any external SDK support for it?

**Comment by Zumbalamambo** [comment]
+1

**Comment by elblogbruno** [comment]
That would be awesome

**Comment by Noreir** [comment]
U can use the Unity Remote 5, ARCore Instant Preview (it installs itself) and configure the ADB drivers and sdk.

**Comment by githubcatw** [comment]
It would be really nice. If a phone can run the AI powering ARCore then why a PC can't?

**Comment by StartNight** [comment]
I also need such function, can you refer to the tutorial? Thank you

**Comment by vantony1** [comment]
+1

**Comment by mylawacad** [comment]
+1

**Comment by jtfrom9** [comment]
+1

**Comment by AndrewBloom** [comment]
This would be amazing for devices like the NReal Glasses for example. They expose USB Cameras as:

USB DEVICE MANAGER :: usb device id /dev/bus/usb/001/006
USB DEVICE MANAGER :: usb device product USB Camera-OV580
USB DEVICE MANAGER :: usb device content 0
USB DEVICE MANAGER :: usb device class 239
USB DEVICE MANAGER :: usb device class 2
USB DEVICE MANAGER :: usb device class 2
USB DEVICE MANAGER :: usb device id /dev/bus/usb/001/005
USB DEVICE MANAGER :: usb device product Nreal Light Audio
USB DEVICE MANAGER :: usb device content 0
USB DEVICE MANAGER :: usb device class 0
USB DEVICE MANAGER :: usb device class 0
USB DEVICE MANAGER :: usb device id /dev/bus/usb/002/002
USB DEVICE MANAGER :: usb device product USB Camera
USB DEVICE MANAGER :: usb device content 0
USB DEVICE MANAGER :: usb device class 239
USB DEVICE MANAGER :: usb device class 2
USB DEVICE MANAGER :: usb device class 2
USB DEVICE MANAGER :: usb device id /dev/bus/usb/001/007
USB DEVICE MANAGER :: usb device product NREAL GLASSES
USB DEVICE MANAGER :: usb device content 0
USB DEVICE MANAGER :: usb device class 0
USB DEVICE MANAGER :: usb device class 0

So if you could connect ARCore to those cameras we would have best tracking / plane recognition. At the moment this is pretty bad on NReal. Furthermore, there are other products that are coming on the market with same characteristics, (glasses connected through usb) so it would make sense to expand ARCore supporting those devices. Especially cause the computations are done on smartphones already.

**Comment by kinectsources** [comment]
I am indie developer. I made custom hardware with Intel Realsense depth camera with Android OS. So, Can I send for certification process?

**Comment by mimming** [comment]
> I am indie developer. I made custom hardware with Intel Realsense depth camera with Android OS. So, Can I send for certification process?

I'm afraid not.  It'd be something we'd undertake with the camera manufacturer, in this case Intel.  Additionally, external cameras are not a use case we plan to support.  I realize this probably isn't the answer that you want to hear.  Sorry!

**Comment by esteimle** [comment]
@mimming Is it possible to get Android AR headsets accepted into AR Core OEM device certification program you linked? We'd love to give it a try and can provide all calibration data needed.
