### ISSUE TITLE
EarlyUpdate.TangoUpdate taking 15-20 msecs per frame

### ISSUE THREAD

**Issue by uffeflarup** [google-ar/arcore-unity-sdk#638]
While profiling our game I noticed that EarlyUpdate.TangoUpdate is taking 15-20 msecs per frame, on a Samsung Galaxy S8 device. Also, when testing the HelloAR scene in the ARCore SDK unity package I noticed that even in the HelloAR scene it takes about 15-20 msecs per frame.

Here's some info about the project:

ARCore SDK 1.11.0
Unity 2019.1.14
Samsung Galaxy S8 device
IL2CPP scripting backend
64 bit builds
Match camera framerate have been disabled in config
Light estimation disabled
Depth sensor usage disabled

Anyone knows why TangoUpdate is taking so much time?

Thank you very much in advance for all help.

Kind regards,
Uffe Flarup

**Comment by uffeflarup** [comment]
Downgrading from SDK 1.11.0 to 1.9.0 improved it a bit, and lowered it to 5-10 msecs per frame for EarlyUpdate.TangoUpdate on a Samsung Galaxy S8 device.

But still, is ARCore expected to take so much CPU time?

It's worth noticing that it typically takes less time in the beginning of the scene, and then it increases after a short while (maybe due to more feature points being tracked).

**Comment by fredsa** [comment]
This issue is also being discussed here
https://forum.unity.com/threads/arcore-earlyupdate-tangoupdate-15-20-msecs-per-frame.740327/

**Comment by uffeflarup** [comment]
Have just tested with ARCore SDK 1.3, but are unfortunately still seeing performance problems on Samsung devices. For more information see the latest post in the above thread:

https://forum.unity.com/threads/arcore-earlyupdate-tangoupdate-15-20-msecs-per-frame.740327/#post-4982237

**Comment by uffeflarup** [comment]
ARCore SDK 1.14.0 fixes this. Thanks!
