### ISSUE TITLE
ArCoreUnity_destroySession locks UI thread for 5 seconds

### ISSUE THREAD

**Issue by renaudbedard** [google-ar/arcore-unity-sdk#64]
Calling `Session.Destroy();` seems to lock the game for 5 second until the `I/native: session_c_api.cc:308 Deleted ArSession.` message finally appears, and the game becomes responsive again.

Does that mean one should not destroy the AR session if you're going out of and back into AR? Is there a way to pause and resume tracking?

**Comment by chaosemer** [comment]
There is no way currently to just disconnect from ARCore. I understand that five second stalls are a big deal, we will have a solution for the 1.0 release.

**Comment by renaudbedard** [comment]
Understood, thanks!

**Comment by Crashthatch** [comment]
Does anyone happen to have a workaround for this in the mean time?

**Comment by chaosemer** [comment]
We have not been able to reproduce this in ARCore 1.0.
