### ISSUE TITLE
ISSUES WITH OBJECT MANIPULATION SCRIPT

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [google-ar/arcore-unity-sdk#660]
hi,

I tried the object manipulation scene and is unable to move the instantiated object across the scene as well as elevate the object.

And another issue I felt was, when I tap on a location that already has an object another new object is being instantiated. Should this be possible?

Also is there a size limit on how much we can increase the size of an object?

**Comment by HdSonu** [comment]
Hey bro i have same issue for Translate and elevate , 
but if you want to change scale limit follow this 

>> Select Pawn Generator >> PawnManipulator>> Manipulator Prefab 
find prefab and you will get all scripts there , change limit as you want !!

<img width="458" alt="Screenshot 2019-11-20 at 2 30 13 PM" src="https://user-images.githubusercontent.com/22346761/69224287-49dc4000-0ba2-11ea-9ea2-671fa309b506.png">
