### ISSUE TITLE
Multiple errors: "The type or namespace name ['x'] does not exist"

### ISSUE THREAD

**Issue by robrtoprz** [google-ar/arcore-unity-sdk#664]
### SPECIFIC ISSUE ENCOUNTERED
When I start a new project in Unity and import the ARCore Unity SDK v1.13.0, I get multiple errors.

### VERSIONS USED
- Unity: 2019.2.9f1
- ARCore SDK for Unity: 1.13.0

### STEPS TO REPRODUCE THE ISSUE
 1. Start a new project in Unity Hub.
 2. Switch Platform to Android
 3. Import ARCore Unity SDK v1.13.0
 4. In Console you will get 17 errors.

### ADDITIONAL COMMENTS
Also since the version 1.12.0 I get this errors, these are the errors that I get in the console:
1. Assets\GoogleARCore\SDK\InstantPreview\Scripts\InstantPreviewManager.cs(33,23): error CS0234: The type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
2. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(32,37): error CS0246: The type or namespace name 'NetworkBehaviour' could not be found (are you missing a using directive or an assembly reference?)
3. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(99,30): error CS0115: 'AnchorController.OnStartClient()': no suitable method found to override
4. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(46,10): error CS0246: The type or namespace name 'SyncVarAttribute' could not be found (are you missing a using directive or an assembly reference?)
5. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(46,10): error CS0246: The type or namespace name 'SyncVar' could not be found (are you missing a using directive or an assembly reference?)
6. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(46,18): error CS0246: The type or namespace name 'hook' could not be found (are you missing a using directive or an assembly reference?)
7. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(141,10): error CS0246: The type or namespace name 'CommandAttribute' could not be found (are you missing a using directive or an assembly reference?)
8. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\AnchorController.cs(141,10): error CS0246: The type or namespace name 'Command' could not be found (are you missing a using directive or an assembly reference?)
9. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(31,47): error CS0246: The type or namespace name 'NetworkManager' could not be found (are you missing a using directive or an assembly reference?)
10. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(49,46): error CS0246: The type or namespace name 'NetworkConnection' could not be found (are you missing a using directive or an assembly reference?)
11. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(73,49): error CS0246: The type or namespace name 'NetworkConnection' could not be found (are you missing a using directive or an assembly reference?)
12. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(49,30): error CS0115: 'CloudAnchorsNetworkManager.OnClientConnect(NetworkConnection)': no suitable method found to override
13. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(73,30): error CS0115: 'CloudAnchorsNetworkManager.OnClientDisconnect(NetworkConnection)': no suitable method found to override
14. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\LocalPlayerController.cs(30,42): error CS0246: The type or namespace name 'NetworkBehaviour' could not be found (are you missing a using directive or an assembly reference?)
15. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\LocalPlayerController.cs(46,30): error CS0115: 'LocalPlayerController.OnStartLocalPlayer()': no suitable method found to override
16. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\LocalPlayerController.cs(82,10): error CS0246: The type or namespace name 'CommandAttribute' could not be found (are you missing a using directive or an assembly reference?)
17. Assets\GoogleARCore\Examples\CloudAnchors\Scripts\LocalPlayerController.cs(82,10): error CS0246: The type or namespace name 'Command' could not be found (are you missing a using directive or an assembly reference?)

I tried to find a post of this issues but I couldn't found, so maybe this issue is only for me or maybe someone else have this issue too. Thank you.

**Comment by robrtoprz** [comment]
So, I did something, now I have 8 errors. In Package Manager I upgrade Rider Editor, Test Framework and Visual Studio Code Editor, and all the errors of ARCore were gone, but now I have 8 errors coming from Rider Editor:

![rider](https://user-images.githubusercontent.com/31904585/68431610-44313400-0178-11ea-9e6f-54bdd0de0c27.PNG)

**Comment by secondage** [comment]
use Window > Package Manager to install the Multiplayer HLAPI and XR Legacy Input Helpers packages.

**Comment by robrtoprz** [comment]
When I try, I will update the post, thank you!

**Comment by piginhat** [comment]
It works for me thanks :-)

**Comment by white-panda01** [comment]
> 
> 
> use Window > Package Manager to install the Multiplayer HLAPI and XR Legacy Input Helpers packages.

Cheers! worked for me too. Wasted a whole day trying to fix this issue manually

**Comment by nongzhang** [comment]
good job！I import ARCore SDK for Unity v1.18.0 into Unity 2019.4.2f1, too many errors: "The type or namespace name ['x'] does not exist"occur. it's fixed by the method above.

**Comment by chiragpranami** [comment]
> use Window > Package Manager to install the Multiplayer HLAPI and XR Legacy Input Helpers packages.

It worked...Thank you

**Comment by dndat97** [comment]
I use Unity 2020.2.0b2 and I cannot find Multiplayer HLAPI and XR Legacy Input Helpers packages in Package Manager. Could someone help me please?

**Comment by AndreFoxVR** [comment]
> I use Unity 2020.2.0b2 and I cannot find Multiplayer HLAPI and XR Legacy Input Helpers packages in Package Manager. Could someone help me please?

For Unity 2020, I used Window > Package Manager and pressed the + (plus) sign: Add Package from git URL and set it to:

com.unity.multiplayer-hlapi
and

com.unity.xr.legacyinputhelpers
as it was recommended here: https://medium.com/@jeffreymlynch/where-are-the-missing-preview-packages-in-unity-2020-3ad0935e4193

**Comment by cardosohs** [comment]
@AndreFoxVR worked like a charm for me. Thanks a bunch!

**Comment by EvanThomasKaduthanam** [comment]
> I use Unity 2020.2.0b2 and I cannot find Multiplayer HLAPI and XR Legacy Input Helpers packages in Package Manager. Could someone help me please?

In Unity 2018.4.29f1 I cannot Find It. i cannot find the upload from git option too

**Comment by hrushikesh26** [comment]
Missing XR Legacy Input Helpers in Package Manager. Unity Version 2020.3.5f1
