### ISSUE TITLE
What happened to the PointCloud points?

### ISSUE THREAD

**Issue by cxbxmxcx** [google-ar/arcore-unity-sdk#68]
I am currently writing a book on ARCore and have worked with several of the examples building demos etc. 
 
Recently I noticed after updating to Preview 2 that the PointCloud points have all but disappeared.  Previously, I was seeing 10s of points consistently, but now it typically only renders a single point.  I did some debugging and noticed that it does occasionally pick 50 or so points but quickly reverts back to 0 or a single point.  

I noticed that I needed to upgrade the service APK to Preview 2 on the device to get the new sample to work but never encountered any other issues.

It looks like the configuration changed, is there a new setting that needs to be set?

Cheers.

**Comment by chaosemer** [comment]
I am unable to reproduce your issue. I added this line to HelloARController.cs `Debug.LogFormat("Num points: {0}", Frame.PointCloud.PointCount);` and I consistently see between 30 and 50 points.

Are you certain you're on the ARCore APK Dev Preview 2 from our download page and not the one from the Play Store? If so, could you please create a repro project? Thanks!

**Comment by JeremiePetitjean** [comment]
I have the same issue here.
Samsung GS 950FD
Unity 2017.3.0f3.
I add a text field to watch the point count. I have 30 - 50 point during short time but after that nothing or 4 points...

I try to uninstall reinstall the preview core 2. I also uninstalled the Tango Core(preview1).
I tried the Java demo app.
Still the same result.
I try the ARCore GR app . (with preview 1) and I had a lot of points in the same condition.

Do you have any idea?

**Comment by Zeraphil** [comment]
I'm having the same issue here as well. Note this is using a Pixel 1 with Unity 2017.3.0f3. Point clouds are extremely sparse, returning 1-4 points usually. Performing circular movements will sometimes generate 10-12. Trying to get even a simple mesh that isn't a plane is not possible right now.

**Comment by cxbxmxcx** [comment]
I can confirm, I tried this again with a Preview 2 project on Samsumg
GS950FD and saw the same results, only 1-4 points.

If I revert to a Preview 1 project on the same device the point cloud
renders as expected, lots of points.

Hope that helps...

M


.

**Comment by chaosemer** [comment]
Sorry, I've been unable to reproduce this locally, I'm going to need more information:
1. Does this happen on HelloAR? If not, can you please share a project that reproduces the issue?
2. Can you tell me the version of ARCore installed? You can see it in the App info screen.

**Comment by fredsa** [comment]
Closing as more information is needed and we're unable to reproduce using the provided information.
