### ISSUE TITLE
Preview2 throws exception with Unity IL2CPP, OK with Mono

### ISSUE THREAD

**Issue by reed-alpert** [google-ar/arcore-unity-sdk#69]
Using Unity 2017.3.0p1 with ARCore Preview2 on a Pixel XL/8.1.0 I see this error with an IL2CPP build. Works fine with Mono build. The error prevents the AR from starting up.

`12-24 18:42:53.803 29826 29826 E Unity   : NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code.
12-24 18:42:53.803 29826 29826 E Unity   :   at GoogleARCoreInternal.NativeApi+ExternApi.ArCoreUnity_resumeSession (GoogleARCoreInternal.EarlyUpdateCallback earlyUpdate) [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at GoogleARCore.ARCoreSession+<_ResumeSession>c__AnonStorey1.<>m__0 () [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at GoogleARCore.AsyncTask.OnUIThread () [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
12-24 18:42:53.803 29826 29826 E Unity   :   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy p
`

**Comment by chaosemer** [comment]
Thank you for the bug report! I've added this to our internal tracker.

**Comment by iBicha** [comment]
[Here's a fix](https://github.com/iBicha/arcore-unity-sdk/tree/il2cpp) (I remember someone asking about it)

**Comment by kbobnis** [comment]
We at Uken have also asked for it. 

Your fix is working, thank you very much.

**Comment by chaosemer** [comment]
This has been fixed in ARCore 1.0.
