### ISSUE TITLE
Number of potential Android model spawns is unlimited (unlike Android ARCore sample)

### ISSUE THREAD

**Issue by aornelas** [google-ar/arcore-unity-sdk#7]
I noticed that on the Android ARCore sample app you can **only spawn 16 "Andy"s**, yet on the Unity ARCore sample **there is no limit**.

Since my 1.5 and 3.5 year-old daughters are having a blast with the ARCore sample, having this limit is critical otherwise they just saturate the screen with Andy's 😅 

I fixed this issue in my own fork in case you (or others) want to apply it: https://github.com/google-ar/arcore-unity-sdk/compare/master...aornelas:limit-andy-count

For reference; here's where this limit is implemented on [the Android sample](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/java_arcore_hello_ar/app/src/main/java/com/google/ar/core/examples/java/helloar/HelloArActivity.java#L239).

Thanks and looking forward to build with ARCore!

Andrés

**Comment by nathanmartz** [comment]
Thanks for the note, but we're actually planning to remove this limit from the Java sample to simplify things. Besides, as your daughters obviously know, there is no such thing as too many androids :)

**Comment by aornelas** [comment]
![gif](https://media.giphy.com/media/u9e7fk2rL5njy/giphy.gif)
