### ISSUE TITLE
FIX: Black camera feed on Pixel devices with AR Stickers installed

### ISSUE THREAD

**Issue by chucknology** [google-ar/arcore-unity-sdk#70]
https://github.com/chucknology/ARCorePixelFix

Sharing the fixes we developed for Atom Visualizer:
https://play.google.com/store/apps/details?id=com.signalgarden.atomvisualizer

**Comment by chucknology** [comment]
Sharing this workaround we developed for Atom Visualizer.

**Comment by chaosemer** [comment]
The Unity ARCore SDK is not compatible with the ARCore on the Play Store. While they are very close, there are multiple important bug fixes in the APK available on our [download page](https://developers.google.com/ar/develop/downloads). Please update to that version.

I'm going to leave this open so that everyone else is aware of this limitation.

**Comment by chucknology** [comment]
That's right. In particular apps built with ARCore Preview 2 Unity SDK will not initialize the camera correctly on Pixel devices with the Play Store version of ARCore.
This fix is provided for developers shipping ARCore apps while the Play Store ARCore release has not been updated. Please see the README in the repo for more details.

**Comment by fredsa** [comment]
Marking as 'invalid' because the behavior is expected for the developer preview.

**Comment by WazzaMo** [comment]
Actually I find I get a black screen on my Pixel when the device overheats.
Sometimes cooling fixes it. Sometimes I need to start the Android camera
app to re-initialise the cam sensor.

At worst, I've had to reboot to make it work

**Comment by chaosemer** [comment]
This workaround is no longer relevant with ARCore 1.0 out.

**Comment by yoavgrosswild** [comment]
i sometimes get the "black screen of death" when i open the AR Core introduction app on Galaxy S7.
Camera also doesn't work afterwards. Only reboot helps at that point.
