### ISSUE TITLE
How to install ARCore app in pixel xl android O

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-unity-sdk#71]
I have pixel xl phone when i go plastore and tab to install ARCore app the message shown in play store as "Your device isn't compatible with this version" iam using android version 8.0.0

**Comment by chucknology** [comment]
ARCore is only available via Play Store for devices running Android Oreo 8.1. Prepare your device for development by installing the ARCore Preview 2 service library APK from here:
https://developers.google.com/ar/develop/downloads#arcore-app

**Comment by ArigarasuthanRepo** [comment]
Thank You.

**Comment by chaosemer** [comment]
Glad this got addressed!
