### ISSUE TITLE
Depth API low resolution

### ISSUE THREAD

**Issue by reneschulte** [google-ar/arcore-unity-sdk#729]
### SPECIFIC ISSUE ENCOUNTERED
The ARCore Depth map texture has only a resolution of 160x90. 
I assume this is due to the computervision model being used. Is there a way to request higher res depth textures for devices with a ToF sensor? AFAIK my S20 5G has a ToF sensor with VGA resolution, so I'd like to use that. Getting access to the raw map is fine, it doesn't have to be processed further for my use case but this low res texture is a bit too low res.

### VERSIONS USED
- Unity: 2019.4.1f
- ARCore SDK for Unity: 1.18
- Device manufacturer, model, and O/S: Samsung S20+ 5G

**Comment by devbridie** [comment]
Devices with a ToF sensor should now see a higher resolution in depth textures.

**Comment by reneschulte** [comment]
Hi @devbridie that sounds great. Unfortunately I can't see thatwe can access the higher res depth map in the release notes. Can you point to a commit where this was added? Also, can I just build from that commit if I don't want to wait for a new release?

**Comment by devbridie** [comment]
I don't think there would be a mention in the release notes-- you don't need an updated SDK to get the higher resolution. You should see the higher resolution in your current setup.
