### ISSUE TITLE
Errors as soon as in imported into unity

### ISSUE THREAD

**Issue by vishwah13** [google-ar/arcore-unity-sdk#738]
### VERSIONS USED
- Unity:2019.3.14f1<DX11>
- ARCore SDK for Unity: 1.18.0
- Device manufacturer, model, and O/S: windows 10

### THE ISSUE
Assets\arcore-unity-sdk-master\Assets\GoogleARCore\Examples\CloudAnchors\Scripts\CloudAnchorsNetworkManager.cs(73,49): error CS0246: The type or namespace name 'NetworkConnection' could not be found (are you missing a using directive or an assembly reference?)

### WORKAROUNDS (IF ANY)
just imported

**Comment by dziemich** [comment]
Same thing happened to me. There is a fix for that here: https://github.com/google-ar/arcore-unity-sdk/issues/664

**Comment by vishwah13** [comment]
https://github.com/google-ar/arcore-unity-sdk/issues/664#issuecomment-570450566 it worked
