### ISSUE TITLE
Question: Why TextureReader's texture is flipped?

### ISSUE THREAD

**Issue by dzak83** [google-ar/arcore-unity-sdk#74]
Hi,
I have a question related to the texture I am getting from TextureReader. It seems to be mirrored and rotated. I see its original form when I modify the shader (disable interpolation on uv coords) from ComputerVisionController  example:
```
void main()
{
	#ifdef SHADER_API_GLES3
	//vec2 uvTop = mix(_UvTopLeftRight.xy, _UvTopLeftRight.zw, gl_MultiTexCoord0.x);
	//vec2 uvBottom = mix(_UvBottomLeftRight.xy, _UvBottomLeftRight.zw, gl_MultiTexCoord0.x);
	//textureCoord = mix(uvTop, uvBottom, gl_MultiTexCoord0.y);

	vec2 texcoord = gl_MultiTexCoord0.xy;
	textureCoord = vec2(texcoord.x, texcoord.y);

	gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
	#endif
}
```

So as shader is doing adjustments for us to render correctly, if I would like to do some processing (e.g. run OpenCV on the texture), then TextureReader's texture is wrong and it's not the same as what it's on the screen. Is there a way to fix the texture on CPU (ideally from OnImageAvailable(..))? I would like to get it the same way as it shows on the screen.

I tried Graphics.Blit(m_TextureToRender, renderTexture, BackgroundRenderer.BackgroundMaterial); but it's pretty ugly in my opinion. 

Thanks,
Jacek

**Comment by chaosemer** [comment]
I actually think the most straightforward way to solve this would be to orientation lock your screen to the camera sensor's orientation. The underlying texture is *usually but not guaranteed to be* rotated 90 degrees from Portrait mode because it follows the orientation of the camera sensor.

That said, it is very possible to do this in the TextureReader itself -- you'd do the rotation and cropping in the texture reader's shader. You'll need to be comfortable with OpenGL for this type of change.

**Comment by dzak83** [comment]
Thanks for the suggestion! I will give it a try. 

For now I used opencv to rotate and flip the texture, so it's working fine. I probably miss the cropping (0.1, 0.9) but can live without it.

**Comment by Nightro** [comment]
> I actually think the most straightforward way to solve this would be to orientation lock your screen to the camera sensor's orientation. The underlying texture is _usually but not guaranteed to be_ rotated 90 degrees from Portrait mode because it follows the orientation of the camera sensor.
> 
> That said, it is very possible to do this in the TextureReader itself -- you'd do the rotation and cropping in the texture reader's shader. You'll need to be comfortable with OpenGL for this type of change.

Could you elaborate on this? Where can I access the shader for the TextureReader?
