### ISSUE TITLE
Instant Preview 17 BROKEN and Unity editor CRASH

### ISSUE THREAD

**Issue by EyezLee** [google-ar/arcore-unity-sdk#742]
**Version Data**

- Unity 2019.3.6f1, 2019.3.0f6, 2019.2.14f1

- Device info: Google Pixel 3, Android 10 (build number QQ3A.200705.002)

- ARCore version: 1.18.0 
                             https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.18.0

**How to Reproduce**

- Follow ARcore instruction: https://developers.google.com/ar/develop/unity/instant-preview
- Open HelloAR scene in GoogleARCore
- Hit play in Unity editor

**Crash info**
![image](https://user-images.githubusercontent.com/18374192/89044994-bb050180-d385-11ea-9480-5529bfee9515.png)

#361 @fredsa

**Comment by Gjohnson6** [comment]
Hi EyezLee,

This issue should be fixed once the 1.19 SDK is released.

**Comment by EyezLee** [comment]
@Gjohnson6 Thank you! when will 1.19 SDK be released?
