### ISSUE TITLE
60fps - list of devices

### ISSUE THREAD

**Issue by svbasavaraj** [google-ar/arcore-unity-sdk#744]
Hello

In which all devices arcore supports 60fps? 
Does this feature is limited to Pixel phone only?

**Comment by jadware** [comment]
Check this page for any phone that says "60 fps"
https://developers.google.com/ar/discover/supported-devices

**Comment by b29b** [comment]
the phones that say "60 fps":
Pixel 2, Pixel 2 XL, Pixel 3, Pixel 3 XL, Pixel 3a, Pixel 3a XL, Pixel 4, Pixel 4 XL

**Comment by mimming** [comment]
https://developers.google.com/ar/discover/supported-devices is indeed the source of truth for device and feature support.
