### ISSUE TITLE
How to augment on point bassic on Face using arcorree unity

### ISSUE THREAD

**Issue by BijayanBhattarai** [google-ar/arcore-unity-sdk#748]
### VERSIONS USED
- Unity:
- ARCore SDK for Unity: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by mimming** [comment]
Closing due to lack of clear description.  Feel free to reopen with more details.
