### ISSUE TITLE
v.1.19.0 15 fatal errors with Unity2020.2 and 2020.1

### ISSUE THREAD

**Issue by EyezLee** [google-ar/arcore-unity-sdk#758]
Overview: Once imported **v.1.19.0** in newly created 3D project in **Unity2020.2.0b2** or **2020.1.4f1**, 15 fatal errors appear immediately. 

Screenshot: 
![image](https://user-images.githubusercontent.com/18374192/92944252-b9535100-f48e-11ea-9cd2-8592c4de037f.png)
![image](https://user-images.githubusercontent.com/18374192/92944345-d0923e80-f48e-11ea-8623-530edabbe2f8.png)

SDK: **v.1.19.0**
Unity: **Unity2020.2.0b2** , **2020.1.4f1**

**Comment by EyezLee** [comment]
Fixed by install HLAPI and xr legacy package from package manager.

**Comment by cjwills** [comment]
How?  Those packages aren't available in the 2020 package manager...

**Comment by EyezLee** [comment]
> How? Those packages aren't available in the 2020 package manager...

They hide them. Follow and instruction here [https://medium.com/@jeffreymlynch/where-are-the-missing-preview-packages-in-unity-2020-3ad0935e4193](url)
