### ISSUE TITLE
AR content reliability, comparing to Google 'ARCore Elements' app

### ISSUE THREAD

**Issue by clifflinmao** [google-ar/arcore-unity-sdk#764]
We are using ARCore to create AR content. But we noticed that it's hard to achieve the **same reliability as in Google's demo app "ARCore Elements"**. When **shaking** the phone, AR content would drift away easily, whereas in 'ARCore Elements', the island is pretty stable unless you shake really hard. We guess that 'shaking' would make trouble to the IMU sensors. But we are wondering why and how the same can be achieved?  There is no document mentioned about this. This kind of reliability is very important for those making AR as industrial app than just games.

BTW. Is it possible to find the source code of 'ARCore Element'? somewhere? I suppose that should be part of ARCore SDK as a sample but it's not.

**Comment by mimming** [comment]
Sorry for the delayed reply.

ARCore Elements is not open source, so I cannot share it.

Are you using [anchors](https://developers.google.com/ar/develop/developer-guides/anchors) in your AR scene?  These should reduce the amount of drift that you are observing.
