### ISSUE TITLE
Question: Does the framework support tablet devices?

### ISSUE THREAD

**Issue by NinjaDanz3r** [google-ar/arcore-unity-sdk#77]
Hi!
What the title says, with the addendum that I'm particularly interested if this works on the Galaxy S3 line of tablets.

**Comment by tomdupont** [comment]
At this point in time the Galaxy S3 is not supported. Currently the only supported devices during the SDK preview releases are:

- Google Pixel
- Google Pixel XL
- Google Pixel 2
- Google Pixel 2 XL
- Samsung S8

However Google said this on their blog:

> In the coming months, we’ll launch ARCore v1.0, with support for over 100 million devices.

And there isn't really a reason that a tablet with a good camera wouldn't be able to run ArCore.

**Comment by fredsa** [comment]
For future reference, a list of currently supported devices is kept up to date here:
https://developers.google.com/ar/discover/#supported_devices

**Comment by lockey25** [comment]
So when is the wide support for ARcore going to be made available?

**Comment by robinbonnes** [comment]
Also looking forward to see ARCore on any tablet device. Especially with the new features announced during this years Google I/O.

**Comment by pnduffy** [comment]
Need Samsung S3 support.  Any idea when?

**Comment by TerraSame** [comment]
Yes... Yes... Yes...
Please make usable on Galaxy Tab 3 with next release...
Thanks
Paul
:)
www.terrasame.com

**Comment by sambuev** [comment]
I told my client that I can develop AR same as ARKIT for tablets such as Samsung. How do I develop it then? Does it mean I should stick with ARKIT and iPad?

**Comment by schmigel** [comment]
Any news? Still waiting support for Tab s3.......

**Comment by TerraSame** [comment]
Its all working...

**Comment by pnduffy** [comment]
@TerraSame , You have ARCore working on the S3? Please give details.

**Comment by pnduffy** [comment]
@TerraSame , Vuforia is required to run ARCore on S3?  This is a bit confusing, as my understanding was Vuforia is a competing API to ARCore. Why do you need Vuforia if you are using ARCore?

**Comment by TerraSame** [comment]
The new versions I mentioned work together in unity and will then allow you
to compile to Android and I Phone with AR Core firing up on proper devices
as per Android and I Phone stats.
I have been following along with all the software suppliers and the process
I mentioned is farthest along... Works great....
If through your research you find I have mis-spoken... Please correct me....

**Comment by ShaatLa** [comment]
Is there some news about S3 ARCore support?

**Comment by small-potatoes** [comment]
Please refer to https://developers.google.com/ar/discover/#supported_devices for all updates on supported devices.
