### ISSUE TITLE
 'SpatialTracking' does not exist 

### ISSUE THREAD

**Issue by Zumbalamambo** [google-ar/arcore-unity-sdk#777]
### SPECIFIC ISSUE ENCOUNTERED

It throws the following code while building,

`Assets/GoogleARCore/SDK/InstantPreview/Scripts/InstantPreviewManager.cs(33,23): error CS0234: The type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
`
### VERSIONS USED
- Unity: 2020.2.5f1
- ARCore SDK for Unity: 1.23.0
- Device manufacturer, model, and O/S:  Android

**Comment by petpetpeter** [comment]
Still facing this problem in Unity 2020 is there any solution?

**Comment by devbridie** [comment]
`arcore-unity-sdk` does not support Unity 2020: see https://developers.google.com/ar/develop/unity/quickstart-android.

Please migrate to [Unity's AR Foundation](https://developers.google.com/ar/develop/unity-arf) or downgrade to Unity 2019.
