### ISSUE TITLE
Crash on ArSession_configure on OPPO CPH2135 device

### ISSUE THREAD

**Issue by josefgrunig** [google-ar/arcore-unity-sdk#780]
### SPECIFIC ISSUE ENCOUNTERED
We are experiencing a crash with our production application [HoppAR](https://hoppar.app/store) on a specific device only: OPPO CPH2135. We do not own directly the phone, but are in contact with the customer with such issue. He reports crashes when we try to start the AR Session, sometimes it does not crash but camera is black. 
The app is built on top of ARFoundation framework.
We do not have similar crash reports on other phones

### VERSIONS USED
- Unity: 2019.3.12f1
- ARCore SDK for Unity: ARFoundation 4.0.2, ARCore XR Plugin: 4.0.4
- Device manufacturer, model, and O/S: Android 10 / OPPO CPH2135
- Device Fingerprint: OPPO/CPH2135EEA/OP4EFDL1:10/QKQ1.200614.002/1617278010:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Install HoppAR: [https://hoppar.app/store](https://hoppar.app/store)
 1. Launch AR Session

### WORKAROUNDS (IF ANY)
None

### ADDITIONAL COMMENTS
See attached Crashlytics report and screenshot of device info
[crash_report.txt](https://github.com/google-ar/arcore-unity-sdk/files/6440006/crash_report.txt)
![Screenshot_2021-04-25-23-45-37-00](https://user-images.githubusercontent.com/32868530/117418057-45811f80-af1b-11eb-8cd5-a77ea8306cff.jpg)
<img width="1048" alt="Screenshot 2021-05-07 at 09 59 43" src="https://user-images.githubusercontent.com/32868530/117418291-87aa6100-af1b-11eb-98a6-99f5b39a661f.png">

**Comment by srvsingh1962** [comment]
Hi @josefgrunig ,
Saw your issue and find out that OPPO CPH2135 (Oppo A53s) does not support the ARCore. You can check out the list of supported devices at https://developers.google.com/ar/devices. This can be the reason for the crash your customer is facing.

With regards
Sourav Singh

**Comment by josefgrunig** [comment]
Thank you for your response @srvsingh1962 
I understand, how could the user install the application if I added the AR-Core requirement? Google Play is letting him install the app and telling him it is compatible. Is there a way to report this to the Store Team, if it's the proper place to do it?
Thank you.

**Comment by srvsingh1962** [comment]
Welcome @josefgrunig 
Just tried HoppAR. It's pretty awesome. Sometimes store does allow you to download and install but when you will run the app it will pop up the notification for ARcore support and then this crash thing happens. Also, the requirement of ARcore is to run only the application and the user can download & install it can't run if AR Core is not supported. You may contact store support for the same issue they might have some solution to restrict the download on unsupported devices. Also, you can see if other apps out in the market facing the same or what they use to cope up.
