### ISSUE TITLE
In Unity SDK, PointCloud data does not contain the associated confidence value

### ISSUE THREAD

**Issue by arghyasur1991** [google-ar/arcore-unity-sdk#9]
Currently PointCloud has only one api GetPoint for getting a point and it returns a Vector3 position only, not the confidence. Whereas, in Android Studio Sdk, it does return the confidence value in the FloatBuffer. What is the reason for this discrepancy?

**Comment by small-potatoes** [comment]
This is a valid observation of a discrepancy between the two Api's.  For now, the confidence values can be accessed if you are willing to modify our Api slightly:

[PointCloud.m_rawPointCloud.points is a Vector4 where the 4th value is confidence.](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/PointCloud.cs#L42)

If you have a compelling reason for this to be exposed in future versions of the SDK, we would love to learn about your use case.

**Comment by stella3d** [comment]
Hi !  I too have this need.  
I'd like to be able to cull points below a confidence threshold for a few reasons.
I'm doing serialization & revisualization of the data, and want to experiment with some bundle adjustment of the data to produce 3d meshes.  this sort of reconstruction will work much better if i can strip low-confidence values.

**Comment by eisenbruch** [comment]
I think this should definitely be exposed in future versions of the SDK. I too would like to create a similar app.

**Comment by nydej2** [comment]
Hi! 
The "GetPoint()" method now returns a vector4. However this value is always 0.0 for each point in each frame. Does anyone have the same problem?
