### ISSUE TITLE
[Enhancement] Barcode/QR scanning

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#92]
Afaik, Tango had qr code scanning built-in, which was a great feature to have bundled.
I suggest this could be a widely used feature for these reasons:

- Load content related to a physical location through scanning of a qr code
- Can be used in conjunction with pose estimation (Ransac or something) which would allow loading AR content in the correct physical space
- Can also be used to sync poses between different devices, allowing real time sharing of virtual spaces

In one of the projects, I did implement this myself. I had terrible results because of the camera focus. (which reminds me to bring up #49 since without it, most additional CV work would simply fail. PS: someone else did it https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2942262-isautofocusenabled)

Edit: this is not related only to the Unity SDK

**Comment by chaosemer** [comment]
Thanks for the feature request.

**Comment by chaosemer** [comment]
Camera focus control is not currently available in ARCore. Like I mentioned in #49, the focus is currently fixed to a distance tuned for motion tracking.

**Comment by thomasflynn** [comment]
Seconding the feature request.  Wrote my own code to render the camera preview to an FBO, read it back and feed it to zxing.  Worked fine before moving to ARCore.  With ARCore, the camera image is too blurry to do any detection.

**Comment by yoavgrosswild** [comment]
#3 for this feature request

**Comment by pablisho** [comment]
Hi, **Augmented Images** has been released as part of [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0)

**Comment by pablisho** [comment]
Hi @iBicha. Adding images at runtime is not currently supported in the ARCore SDK for Unity because we had the assumption that most users would have the images they want to track at build time in Unity. But other ARCore SDKs support it, so I could take it as a feature request.

**Comment by iBicha** [comment]
I just realised that adding images at runtime is possible, with `ArAugmentedImageDatabase_addImage`, it was just not implemented in the SDK

**Comment by re-cheid** [comment]
Another way to obtain a `Color32` array from the camera is to create a second camera with the `ARCoreBackgroundRenderer` and `TrackedPoseDriver` attached. Set its culling mask to `Nothing` and let it render to a RenderTexture.

Reading the color array can be done as follows:

```
var texture2D = new Texture2D (bgRenderTexture.width, bgRenderTexture.height, TextureFormat.RGB24, false);
var rectReadPicture = new Rect (0, 0, bgRenderTexture.width, bgRenderTexture.height);

RenderTexture.active = bgRenderTexture;

texture2D.ReadPixels (rectReadPicture, 0, 0);
texture2D.Apply();
RenderTexture.active = null;

Color32[] color32s = texture2D.GetPixels32();
```

Maybe this is helpful for someone trying to feed that into a third party library. 
However, this does not fix the problem of having poor quality because of the fixed focus.

**Comment by iBicha** [comment]
@re-cheid that is slow to run every frame, because you'll be syncing between the CPU and the GPU.
There's an API to get the camera pixel buffer: https://developers.google.com/ar/reference/unity/class/GoogleARCore/Frame/CameraImage#classGoogleARCore_1_1Frame_1_1CameraImage_1a6772bc2188315a4be9452be629a4f080

**Comment by lxg13** [comment]
I Made it 
https://pan.baidu.com/s/1TKdZwZJFGrae4T232n7Dhw

**Comment by fredsa** [comment]
@iBicha Thank you for the feature request.

Unfortunately, we currently have no plans to add barcode / QR code scanning functionality as part of the ARCore SDK for Unity.

However, the camera image is accessible for for CPU processing.
See the **ComputerVision* sample for how to access the image:
https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples


Closing this issue for now, although we can consider reopening it in the future

**Comment by rasamaya** [comment]
Also requesting this feature

**Comment by fredsa** [comment]
One more note, since "fixed focus" and "blurry image" were mentioned several times above:

[Auto Focus support](https://github.com/google-ar/arcore-unity-sdk/issues/49#issuecomment-410057859) was added in version `1.4.0`.

@thomasflynn If you're unable to access the camera image with Auto Focus enabled as you mentioned [above](https://github.com/google-ar/arcore-unity-sdk/issues/92#issuecomment-371006881), please feel free to file a new issue.
