### ISSUE TITLE
Failed to run Samsung Galaxy Note 8..

### ISSUE THREAD

**Issue by gegabal** [google-ar/arcore-unity-sdk#95]
Hi dear

Device : Samsung Galaxy Note8 (SM-N950N)
Unity Version : 2017.3.1f1 Personal

I Imported  arcore-unity-sdk-preview2.unitypackage and build HelloAR.apk example.
And I Installed arcore-preview2.apk , HelloVR.apk on Galaxy Note8.
When I run the app, I get popuped messages that ARCore will terminate abnormally.
Then the HelloVR.apk screen pops up very briefly, shows the message, and exits immediately.
"ARCore encountered a problem connecting. Please start the app again. "

The same installation file works when installed on Samsung GalaxyS8 .

Are there known compatibility issues with Note8?

**Comment by Crashthatch** [comment]
Yes. ARCore developer preview only supports Pixel 1, 2 (& XL) and Samsung Galaxy S8. [Full list](https://developers.google.com/ar/discover/#supported_devices)

Google have not yet announced what devices will be compatible, or when v1 will be released, only that "in the coming months we will add compatibility for 100 million devices".

**Comment by drinikol** [comment]
Note 8 is already supported but it still crashes on my Note 8 as well.  "Tango Core keeps stopping"[this is the screenshot.](https://imgur.com/a/vCv7Nl)

**Comment by chaosemer** [comment]
The Note 8 is now officially supported in ARCore 1.0. Please reopen if you are still having issues.
