### ISSUE TITLE
Tracking is stopped when a second ARCoreSession is instantiated 

### ISSUE THREAD

**Issue by henningboat** [google-ar/arcore-unity-sdk#96]
When a second AR Core Session is instantiated, it destroys itself automatically, which makes a lot of sense. However, that causes ARCoreSession.OnDestroy() to be called, which calls Frame.Destroy() and Session.Destroy(). 
I am sure this is not intended :)

**Comment by chaosemer** [comment]
Yeah, we don't currently support having switching between ARCore sessions. This will be addressed in a future release.

**Comment by chaosemer** [comment]
We believe this is no longer happening in ARCore 1.0; we rewrote this to prevent our session management to prevent type of issue.
