### ISSUE TITLE
How can i use Virtual Positioning Service with Arcore?

### ISSUE THREAD

**Issue by diegoarx** [google-ar/arcore-unity-sdk#97]
I have seen a video with a demo showing the VPS with ArCore but i dont see any way to use it in the api for Unity

**Comment by chaosemer** [comment]
There's nothing available right now. Stay tuned!

**Comment by juanmajr93** [comment]
I am very interested about VPS. Do you when it must be available to add in our developments?

**Comment by chaosemer** [comment]
Unfortunately, there's no timelines I can share right now.

**Comment by pablisho** [comment]
Hi, **Cloud Anchors** has been released as part of [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0)

**Comment by juanmajr93** [comment]
Hi all
I have a question related to cloud anchors utility. I have a 3D model that must appear at the same place in my room. I suppose that cloud anchors help me in order to locate the object or are cloud anchors the 3D models directly?

**Comment by chaosemer** [comment]
Cloud Anchors allow you to have a shared multi-user experience so that multiple people will see the 3D model in the same place during a session.

**Comment by lionelonline** [comment]
Is Virtual Positioning Service/VPS now Cloud Anchors?

**Comment by chaosemer** [comment]
Cloud Anchors is the API surface. VPS is an implementation detail. :)
