### ISSUE TITLE
MatchCameraFramerate causes "ghost frames"

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#98]
This is a minor issue, but I want to bring the attention to how this option is not really useful, or a bit flawed.

It says that when this is true, the background rendering matches the frame rate of 3d rendering, which is fine.

When this setting it set to false, The scene can render multiple times before the background renders. The issue is, since the camera clear flag is set to `depth`, previous frames are overlapped, until it is time to draw the background again. (the `ARBackgroundRenderer` sets the clear flag of the camera to depth)

Supposing the `MatchCameraFramerate` is set to false, here is a sequence of how it is happening :

1. Frame 1:
- 1 - the camera clears its depth buffer
- 2 - the background renders 
- 3 - 3d content renders
1. Frame 2:
- 1 - the camera clears its depth buffer
- 2 - the background is not going to render in this frame 
- 3 - 3d content renders on top of the old frame <= "ghost frames"

Normally, the clear flag is set to depth, because there is no need to clear the pixel buffer, since the rendering of the background clears/hides the previous frame. But when the rendering of the background doesnt happen (skips a frame), the rendering of the 3d content happens on a dirty canvas.

**Comment by chaosemer** [comment]
This is surprising, the ARBackgroundRenderer is drawing every frame (even if there's no new image). Are you able to reproduce this with HelloAR?

**Comment by iBicha** [comment]
I know, it doesnt make much sense to me either, but it seems to be the case for Unity-Technologies/experimental-ARInterface with the `ARFocusSquare` demo scene, the one I tested so far.
Will try to reproduce with HelloAR.

**Comment by iBicha** [comment]
Finally I ported the `ARFocusSquare` to work with the `HelloAR` scene, no `double vision` which got me even more confused (because setting the `MatchCameraFramerate` does fix the problem for the `UnityARInterface`, but it does not matter when used in `HelloAR`)
I guess I will close this until I get hold of this. If you have any comments, please, because I really want to understand what's going on.
Cheers.

**Comment by chaosemer** [comment]
I suggest reporting this bug there -- it's probably an issues with their integration layer.
